CREATE OR REPLACE 
PACKAGE PKG_APP_DETAIL_TM06DKQT
  IS
  PROCEDURE PROC_TM06DKQT_INSERT
(
    P_APPCODE IN APP_DETAIL_TM06DKQT.APPCODE % TYPE,
    P_APP_HEADER_ID IN APP_DETAIL_TM06DKQT.APP_HEADER_ID % TYPE,
    P_LANGUAGE IN APP_DETAIL_TM06DKQT.LANGUAGE % TYPE,
    P_APPNO IN APP_DETAIL_TM06DKQT.APPNO % TYPE,
    P_THANHVIEN_ND_TC IN APP_DETAIL_TM06DKQT.THANHVIEN_ND_TC % TYPE,
    P_LOGOURL IN APP_DETAIL_TM06DKQT.LOGOURL % TYPE,
    P_DON_GIAY_DKNHCS IN APP_DETAIL_TM06DKQT.DON_GIAY_DKNHCS % TYPE,
    P_REF_APPNO IN APP_DETAIL_TM06DKQT.REF_APPNO % TYPE,
    P_COUNTRY_ID01 IN APP_DETAIL_TM06DKQT.COUNTRY_ID01 % TYPE,
    P_COUNTRY_ID02 IN APP_DETAIL_TM06DKQT.COUNTRY_ID02 % TYPE,
    P_COUNTRY_ID03 IN APP_DETAIL_TM06DKQT.COUNTRY_ID03 % TYPE,
    P_COUNTRY_ID04 IN APP_DETAIL_TM06DKQT.COUNTRY_ID04 % TYPE,
    P_COUNTRY_ID05 IN APP_DETAIL_TM06DKQT.COUNTRY_ID05 % TYPE,
    P_COUNTRY_ID06 IN APP_DETAIL_TM06DKQT.COUNTRY_ID06 % TYPE,
    P_COUNTRY_ID07 IN APP_DETAIL_TM06DKQT.COUNTRY_ID07 % TYPE,
    P_COUNTRY_ID08 IN APP_DETAIL_TM06DKQT.COUNTRY_ID08 % TYPE,
    P_LEPHI IN APP_DETAIL_TM06DKQT.LEPHI % TYPE,
    P_RETURN OUT NUMBER
);

PROCEDURE PROC_TM06DKQT_UPDATE
(
P_ID IN APP_DETAIL_TM06DKQT.ID % TYPE,
P_APPCODE IN APP_DETAIL_TM06DKQT.APPCODE % TYPE,
P_APP_HEADER_ID IN APP_DETAIL_TM06DKQT.APP_HEADER_ID % TYPE,
P_LANGUAGE IN APP_DETAIL_TM06DKQT.LANGUAGE % TYPE,
P_APPNO IN APP_DETAIL_TM06DKQT.APPNO % TYPE,
P_THANHVIEN_ND_TC IN APP_DETAIL_TM06DKQT.THANHVIEN_ND_TC % TYPE,
P_LOGOURL IN APP_DETAIL_TM06DKQT.LOGOURL % TYPE,
P_DON_GIAY_DKNHCS IN APP_DETAIL_TM06DKQT.DON_GIAY_DKNHCS % TYPE,
P_REF_APPNO IN APP_DETAIL_TM06DKQT.REF_APPNO % TYPE,
P_COUNTRY_ID01 IN APP_DETAIL_TM06DKQT.COUNTRY_ID01 % TYPE,
P_COUNTRY_ID02 IN APP_DETAIL_TM06DKQT.COUNTRY_ID02 % TYPE,
P_COUNTRY_ID03 IN APP_DETAIL_TM06DKQT.COUNTRY_ID03 % TYPE,
P_COUNTRY_ID04 IN APP_DETAIL_TM06DKQT.COUNTRY_ID04 % TYPE,
P_COUNTRY_ID05 IN APP_DETAIL_TM06DKQT.COUNTRY_ID05 % TYPE,
P_COUNTRY_ID06 IN APP_DETAIL_TM06DKQT.COUNTRY_ID06 % TYPE,
P_COUNTRY_ID07 IN APP_DETAIL_TM06DKQT.COUNTRY_ID07 % TYPE,
P_COUNTRY_ID08 IN APP_DETAIL_TM06DKQT.COUNTRY_ID08 % TYPE,
P_LEPHI IN APP_DETAIL_TM06DKQT.LEPHI % TYPE,
P_RETURN OUT NUMBER
);
END;
/


CREATE OR REPLACE 
PACKAGE BODY PKG_APP_DETAIL_TM06DKQT
IS
 PROCEDURE PROC_TM06DKQT_INSERT
(
    P_APPCODE IN APP_DETAIL_TM06DKQT.APPCODE % TYPE,
    P_APP_HEADER_ID IN APP_DETAIL_TM06DKQT.APP_HEADER_ID % TYPE,
    P_LANGUAGE IN APP_DETAIL_TM06DKQT.LANGUAGE % TYPE,
    P_APPNO IN APP_DETAIL_TM06DKQT.APPNO % TYPE,
    P_THANHVIEN_ND_TC IN APP_DETAIL_TM06DKQT.THANHVIEN_ND_TC % TYPE,
    P_LOGOURL IN APP_DETAIL_TM06DKQT.LOGOURL % TYPE,
    P_DON_GIAY_DKNHCS IN APP_DETAIL_TM06DKQT.DON_GIAY_DKNHCS % TYPE,
    P_REF_APPNO IN APP_DETAIL_TM06DKQT.REF_APPNO % TYPE,
    P_COUNTRY_ID01 IN APP_DETAIL_TM06DKQT.COUNTRY_ID01 % TYPE,
    P_COUNTRY_ID02 IN APP_DETAIL_TM06DKQT.COUNTRY_ID02 % TYPE,
    P_COUNTRY_ID03 IN APP_DETAIL_TM06DKQT.COUNTRY_ID03 % TYPE,
    P_COUNTRY_ID04 IN APP_DETAIL_TM06DKQT.COUNTRY_ID04 % TYPE,
    P_COUNTRY_ID05 IN APP_DETAIL_TM06DKQT.COUNTRY_ID05 % TYPE,
    P_COUNTRY_ID06 IN APP_DETAIL_TM06DKQT.COUNTRY_ID06 % TYPE,
    P_COUNTRY_ID07 IN APP_DETAIL_TM06DKQT.COUNTRY_ID07 % TYPE,
    P_COUNTRY_ID08 IN APP_DETAIL_TM06DKQT.COUNTRY_ID08 % TYPE,
    P_LEPHI IN APP_DETAIL_TM06DKQT.LEPHI % TYPE,
    P_RETURN OUT NUMBER
)
IS
V_ID NUMBER;
BEGIN
    P_RETURN:= 0;
    SELECT SEQ_APP_DETAIL_TM06DKQT.NEXTVAL INTO V_ID FROM DUAL;
    INSERT INTO APP_DETAIL_TM06DKQT
    (
      ID, APPCODE, APP_HEADER_ID, LANGUAGE, APPNO, THANHVIEN_ND_TC, LOGOURL,
      DON_GIAY_DKNHCS, REF_APPNO,  COUNTRY_ID01, COUNTRY_ID02,
      COUNTRY_ID03, COUNTRY_ID04, COUNTRY_ID05, COUNTRY_ID06, COUNTRY_ID07,
      COUNTRY_ID08, LEPHI   )
    VALUES
    (
    V_ID, P_APPCODE, P_APP_HEADER_ID, P_LANGUAGE, P_APPNO, P_THANHVIEN_ND_TC,
    P_LOGOURL, P_DON_GIAY_DKNHCS, P_REF_APPNO,  P_COUNTRY_ID01,
    P_COUNTRY_ID02, P_COUNTRY_ID03, P_COUNTRY_ID04, P_COUNTRY_ID05, P_COUNTRY_ID06,
    P_COUNTRY_ID07, P_COUNTRY_ID08, P_LEPHI);

P_RETURN := V_ID;

EXCEPTION
WHEN OTHERS THEN
RAISE;
   P_RETURN := -1;

END;



--2.UPDATE

PROCEDURE PROC_TM06DKQT_UPDATE
(
P_ID IN APP_DETAIL_TM06DKQT.ID % TYPE,
P_APPCODE IN APP_DETAIL_TM06DKQT.APPCODE % TYPE,
P_APP_HEADER_ID IN APP_DETAIL_TM06DKQT.APP_HEADER_ID % TYPE,
P_LANGUAGE IN APP_DETAIL_TM06DKQT.LANGUAGE % TYPE,
P_APPNO IN APP_DETAIL_TM06DKQT.APPNO % TYPE,
P_THANHVIEN_ND_TC IN APP_DETAIL_TM06DKQT.THANHVIEN_ND_TC % TYPE,
P_LOGOURL IN APP_DETAIL_TM06DKQT.LOGOURL % TYPE,
P_DON_GIAY_DKNHCS IN APP_DETAIL_TM06DKQT.DON_GIAY_DKNHCS % TYPE,
P_REF_APPNO IN APP_DETAIL_TM06DKQT.REF_APPNO % TYPE,
P_COUNTRY_ID01 IN APP_DETAIL_TM06DKQT.COUNTRY_ID01 % TYPE,
P_COUNTRY_ID02 IN APP_DETAIL_TM06DKQT.COUNTRY_ID02 % TYPE,
P_COUNTRY_ID03 IN APP_DETAIL_TM06DKQT.COUNTRY_ID03 % TYPE,
P_COUNTRY_ID04 IN APP_DETAIL_TM06DKQT.COUNTRY_ID04 % TYPE,
P_COUNTRY_ID05 IN APP_DETAIL_TM06DKQT.COUNTRY_ID05 % TYPE,
P_COUNTRY_ID06 IN APP_DETAIL_TM06DKQT.COUNTRY_ID06 % TYPE,
P_COUNTRY_ID07 IN APP_DETAIL_TM06DKQT.COUNTRY_ID07 % TYPE,
P_COUNTRY_ID08 IN APP_DETAIL_TM06DKQT.COUNTRY_ID08 % TYPE,
P_LEPHI IN APP_DETAIL_TM06DKQT.LEPHI % TYPE,
P_RETURN OUT NUMBER
)
IS
BEGIN
P_RETURN := 0;
UPDATE APP_DETAIL_TM06DKQT SET
APPCODE = P_APPCODE,
APP_HEADER_ID = P_APP_HEADER_ID,
APPNO = P_APPNO,
THANHVIEN_ND_TC = P_THANHVIEN_ND_TC,
LOGOURL = P_LOGOURL,
DON_GIAY_DKNHCS = P_DON_GIAY_DKNHCS,
REF_APPNO = P_REF_APPNO,
COUNTRY_ID01 = P_COUNTRY_ID01,
COUNTRY_ID02 = P_COUNTRY_ID02,
COUNTRY_ID03 = P_COUNTRY_ID03,
COUNTRY_ID04 = P_COUNTRY_ID04,
COUNTRY_ID05 = P_COUNTRY_ID05,
COUNTRY_ID06 = P_COUNTRY_ID06,
COUNTRY_ID07 = P_COUNTRY_ID07,
COUNTRY_ID08 = P_COUNTRY_ID08,
LEPHI = P_LEPHI
WHERE APP_HEADER_ID = P_ID AND LANGUAGE = P_LANGUAGE;

P_RETURN :=0;
EXCEPTION
WHEN OTHERS THEN

P_RETURN := -1;
RAISE;
END;


PROCEDURE PROC_TM06DKQT_GETBYID
(
  P_ID IN APP_DETAIL_TM06DKQT.ID % TYPE,
  P_CURSOR OUT PKG_COMMON.t_cursor
)
IS
 BEGIN
OPEN P_CURSOR FOR SELECT APP_DETAIL_TM06DKQT.* FROM APP_DETAIL_TM06DKQT WHERE ID = P_ID;

 EXCEPTION
 WHEN OTHERS THEN
 RAISE;
 ROLLBACK;
 END;
END;
/

