PROCEDURE PROC_APP_04NH_SEARCH
(
 P_STATUS IN VARCHAR2,
 P_CURSOR OUT PKG_COMMON.T_CURSOR
)
IS
BEGIN
   OPEN P_CURSOR FOR SELECT A.* FROM APP_DETAIL_04NH A INNER JOIN APPLICATION_HEADER B ON A.APP_HEADER_ID = B.ID
   WHERE B.DELETED = 0 AND B.STATUS = TO_NUMBER(P_STATUS);
EXCEPTION WHEN OTHERS THEN
RAISE; 
END;