-- Start of DDL Script for Package LEGALTECH.PKG_APP_GET_DATA
-- Generated 09/06/2018 12:02:29 AM from LEGALTECH@LOCAL

CREATE OR REPLACE 
PACKAGE pkg_app_get_data
  IS

PROCEDURE PROC_APP_TM04NH_GET_BY_ID
(
    P_APP_HEADER_ID IN VARCHAR2,
    P_LANGUAGE IN VARCHAR2,
    P_STATUS IN NUMBER ,
    P_CURSOR OUT PKG_COMMON.T_CURSOR  ,
    P_C_DOC OUT  PKG_COMMON.T_CURSOR ,
    P_C_OTHER OUT  PKG_COMMON.T_CURSOR ,
    P_C_CLASS_DETAIL OUT  PKG_COMMON.T_CURSOR ,
    P_C_FEE OUT  PKG_COMMON.T_CURSOR
);


END; -- PACKAGE SPEC
/


CREATE OR REPLACE 
PACKAGE BODY pkg_app_get_data
IS

PROCEDURE PROC_APP_TM04NH_GET_BY_ID
(
    P_APP_HEADER_ID IN VARCHAR2, 
    P_LANGUAGE IN VARCHAR2,
    P_STATUS IN NUMBER ,
    P_CURSOR OUT PKG_COMMON.T_CURSOR  ,
    P_C_DOC OUT  PKG_COMMON.T_CURSOR ,
    P_C_OTHER OUT  PKG_COMMON.T_CURSOR ,
    P_C_CLASS_DETAIL OUT  PKG_COMMON.T_CURSOR ,
    P_C_FEE OUT  PKG_COMMON.T_CURSOR
)
IS
BEGIN

    OPEN  P_CURSOR FOR SELECT A.* , B.* FROM APPLICATION_HEADER A LEFT JOIN APP_DETAIL_04NH B ON A.ID = B.APP_HEADER_ID
                        WHERE   A.LANGUAGUE_CODE =P_LANGUAGE   AND  APP_HEADER_ID = P_APP_HEADER_ID  AND STATUS = P_STATUS AND
                        DELETED =0 ;
    --LAY DANH SACH CAC TAI LIEU DINH KEM
    OPEN  P_C_DOC FOR SELECT  * FROM APP_DOCUMENT A  WHERE  app_header_id = P_APP_HEADER_ID AND  language_code = P_LANGUAGE ;
    --LAY DANH SACH CAC TAI LIEU KHAC DINH KEM
    OPEN  P_C_OTHER FOR SELECT  * FROM APP_DOCUMENT_OTHERS A  WHERE  app_header_id = P_APP_HEADER_ID AND  language_code = P_LANGUAGE AND DELETED =0;
    -- LAY THONG TIN CHI TIET
    OPEN  P_C_CLASS_DETAIL FOR SELECT  * FROM APP_CLASS_DETAIL A  WHERE  app_header_id = P_APP_HEADER_ID AND  language_code = P_LANGUAGE ;

    OPEN   P_C_FEE FOR SELECT * FROM  APP_FEE_FIX  WHERE  app_header_id= P_APP_HEADER_ID ;

EXCEPTION WHEN OTHERS THEN
    RAISE;
END  ;

   -- ENTER FURTHER CODE BELOW AS SPECIFIED IN THE PACKAGE SPEC.
END;
/


-- End of DDL Script for Package LEGALTECH.PKG_APP_GET_DATA

