-- Start of DDL Script for Package LEGALTECH.PKG_APP_DETAIL_04NH
-- Generated 20/06/2018 12:16:52 AM from LEGALTECH@LOCAL

CREATE OR REPLACE 
PACKAGE pkg_app_detail_04nh
  IS
 PROCEDURE PROC_APP_DETAIL_04NH_INSERT
(
    P_APP_HEADER_ID IN APP_DETAIL_04NH.APP_HEADER_ID % TYPE,
    P_APPCODE IN APP_DETAIL_04NH.APPCODE % TYPE,
    P_LANGUAGE_CODE IN APP_DETAIL_04NH.LANGUAGE_CODE % TYPE,
    P_APPNO IN APP_DETAIL_04NH.APPNO % TYPE,
    P_DUADATE IN APP_DETAIL_04NH.DUADATE % TYPE,
    P_LOGOURL IN APP_DETAIL_04NH.LOGOURL % TYPE,
    P_DACTICHHANGHOA IN APP_DETAIL_04NH.DACTICHHANGHOA % TYPE,
    P_COLOR IN APP_DETAIL_04NH.COLOR % TYPE,
    P_DESCRIPTION IN APP_DETAIL_04NH.DESCRIPTION % TYPE,
    P_HUONGQUYENUUTIEN IN APP_DETAIL_04NH.HUONGQUYENUUTIEN % TYPE,
    P_SODON_UT IN APP_DETAIL_04NH.SODON_UT % TYPE,
    P_NGAYNOPDON_UT IN APP_DETAIL_04NH.NGAYNOPDON_UT % TYPE,
    P_NUOCNOPDON_UT IN APP_DETAIL_04NH.NUOCNOPDON_UT % TYPE,
    P_NGUONGOCDIALY IN APP_DETAIL_04NH.NGUONGOCDIALY % TYPE,
    P_CHATLUONG IN APP_DETAIL_04NH.CHATLUONG % TYPE,
    P_DACTINHKHAC IN APP_DETAIL_04NH.DACTINHKHAC % TYPE,
    P_CDK_NAME_1 IN APP_DETAIL_04NH.CDK_NAME_1 % TYPE,
    P_CDK_ADDRESS_1 IN APP_DETAIL_04NH.CDK_ADDRESS_1 % TYPE,
    P_CDK_PHONE_1 IN APP_DETAIL_04NH.CDK_PHONE_1 % TYPE,
    P_CDK_FAX_1 IN APP_DETAIL_04NH.CDK_FAX_1 % TYPE,
    P_CDK_EMAIL_1 IN APP_DETAIL_04NH.CDK_EMAIL_1 % TYPE,
    P_CDK_NAME_2 IN APP_DETAIL_04NH.CDK_NAME_2 % TYPE,
    P_CDK_ADDRESS_2 IN APP_DETAIL_04NH.CDK_ADDRESS_2 % TYPE,
    P_CDK_PHONE_2 IN APP_DETAIL_04NH.CDK_PHONE_2 % TYPE,
    P_CDK_FAX_2 IN APP_DETAIL_04NH.CDK_FAX_2 % TYPE,
    P_CDK_EMAIL_2 IN APP_DETAIL_04NH.CDK_EMAIL_2 % TYPE,
    P_CDK_NAME_3 IN APP_DETAIL_04NH.CDK_NAME_3 % TYPE,
    P_CDK_ADDRESS_3 IN APP_DETAIL_04NH.CDK_ADDRESS_3 % TYPE,
    P_CDK_PHONE_3 IN APP_DETAIL_04NH.CDK_PHONE_3 % TYPE,
    P_CDK_FAX_3 IN APP_DETAIL_04NH.CDK_FAX_3 % TYPE,
    P_CDK_EMAIL_3 IN APP_DETAIL_04NH.CDK_EMAIL_3 % TYPE,
    P_CDK_NAME_4 IN APP_DETAIL_04NH.CDK_NAME_4 % TYPE,
    P_CDK_ADDRESS_4 IN APP_DETAIL_04NH.CDK_ADDRESS_4 % TYPE,
    P_CDK_PHONE_4 IN APP_DETAIL_04NH.CDK_PHONE_4 % TYPE,
    P_CDK_FAX_4 IN APP_DETAIL_04NH.CDK_FAX_4 % TYPE,
    P_CDK_EMAIL_4 IN APP_DETAIL_04NH.CDK_EMAIL_4 % TYPE,
    P_USED_SPECIAL IN APP_DETAIL_04NH.USED_SPECIAL % TYPE ,
    P_LOAINHANHIEU IN VARCHAR2 ,
    P_RETURN OUT NUMBER
);

PROCEDURE PROC_APP_DETAIL_04NH_UPDATE
(
    P_ID IN APP_DETAIL_04NH.ID % TYPE,
    P_APP_HEADER_ID IN APP_DETAIL_04NH.APP_HEADER_ID % TYPE,
    P_APPCODE IN APP_DETAIL_04NH.APPCODE % TYPE,
    P_LANGUAGE_CODE IN APP_DETAIL_04NH.LANGUAGE_CODE % TYPE,
    P_APPNO IN APP_DETAIL_04NH.APPNO % TYPE,
    P_DUADATE IN APP_DETAIL_04NH.DUADATE % TYPE,
    P_LOGOURL IN APP_DETAIL_04NH.LOGOURL % TYPE,
    P_DACTICHHANGHOA IN APP_DETAIL_04NH.DACTICHHANGHOA % TYPE,
    P_COLOR IN APP_DETAIL_04NH.COLOR % TYPE,
    P_DESCRIPTION IN APP_DETAIL_04NH.DESCRIPTION % TYPE,
    P_HUONGQUYENUUTIEN IN APP_DETAIL_04NH.HUONGQUYENUUTIEN % TYPE,
    P_SODON_UT IN APP_DETAIL_04NH.SODON_UT % TYPE,
    P_NGAYNOPDON_UT IN APP_DETAIL_04NH.NGAYNOPDON_UT % TYPE,
    P_NUOCNOPDON_UT IN APP_DETAIL_04NH.NUOCNOPDON_UT % TYPE,
    P_NGUONGOCDIALY IN APP_DETAIL_04NH.NGUONGOCDIALY % TYPE,
    P_CHATLUONG IN APP_DETAIL_04NH.CHATLUONG % TYPE,
    P_DACTINHKHAC IN APP_DETAIL_04NH.DACTINHKHAC % TYPE,
    P_CDK_NAME_1 IN APP_DETAIL_04NH.CDK_NAME_1 % TYPE,
    P_CDK_ADDRESS_1 IN APP_DETAIL_04NH.CDK_ADDRESS_1 % TYPE,
    P_CDK_PHONE_1 IN APP_DETAIL_04NH.CDK_PHONE_1 % TYPE,
    P_CDK_FAX_1 IN APP_DETAIL_04NH.CDK_FAX_1 % TYPE,
    P_CDK_EMAIL_1 IN APP_DETAIL_04NH.CDK_EMAIL_1 % TYPE,
    P_CDK_NAME_2 IN APP_DETAIL_04NH.CDK_NAME_2 % TYPE,
    P_CDK_ADDRESS_2 IN APP_DETAIL_04NH.CDK_ADDRESS_2 % TYPE,
    P_CDK_PHONE_2 IN APP_DETAIL_04NH.CDK_PHONE_2 % TYPE,
    P_CDK_FAX_2 IN APP_DETAIL_04NH.CDK_FAX_2 % TYPE,
    P_CDK_EMAIL_2 IN APP_DETAIL_04NH.CDK_EMAIL_2 % TYPE,
    P_CDK_NAME_3 IN APP_DETAIL_04NH.CDK_NAME_3 % TYPE,
    P_CDK_ADDRESS_3 IN APP_DETAIL_04NH.CDK_ADDRESS_3 % TYPE,
    P_CDK_PHONE_3 IN APP_DETAIL_04NH.CDK_PHONE_3 % TYPE,
    P_CDK_FAX_3 IN APP_DETAIL_04NH.CDK_FAX_3 % TYPE,
    P_CDK_EMAIL_3 IN APP_DETAIL_04NH.CDK_EMAIL_3 % TYPE,
    P_CDK_NAME_4 IN APP_DETAIL_04NH.CDK_NAME_4 % TYPE,
    P_CDK_ADDRESS_4 IN APP_DETAIL_04NH.CDK_ADDRESS_4 % TYPE,
    P_CDK_PHONE_4 IN APP_DETAIL_04NH.CDK_PHONE_4 % TYPE,
    P_CDK_FAX_4 IN APP_DETAIL_04NH.CDK_FAX_4 % TYPE,
    P_CDK_EMAIL_4 IN APP_DETAIL_04NH.CDK_EMAIL_4 % TYPE,
    P_USED_SPECIAL IN APP_DETAIL_04NH.USED_SPECIAL % TYPE ,
    P_LOAINHANHIEU IN VARCHAR2 ,
    P_RETURN OUT NUMBER
);



PROCEDURE PROC_APP_DETAIL_04NH_DELETE (

    P_APP_HEADER_ID IN APP_DETAIL_04NH.APP_HEADER_ID % TYPE,
    P_APPCODE IN APP_DETAIL_04NH.APPCODE % TYPE,
    P_LANGUAGE_CODE IN APP_DETAIL_04NH.LANGUAGE_CODE % TYPE,
    P_RETURN OUT NUMBER
);

END; -- PACKAGE SPEC
/


CREATE OR REPLACE 
PACKAGE BODY pkg_app_detail_04nh
IS

PROCEDURE PROC_APP_DETAIL_04NH_INSERT
(
    P_APP_HEADER_ID IN APP_DETAIL_04NH.APP_HEADER_ID % TYPE,
    P_APPCODE IN APP_DETAIL_04NH.APPCODE % TYPE,
    P_LANGUAGE_CODE IN APP_DETAIL_04NH.LANGUAGE_CODE % TYPE,
    P_APPNO IN APP_DETAIL_04NH.APPNO % TYPE,
    P_DUADATE IN APP_DETAIL_04NH.DUADATE % TYPE,
    P_LOGOURL IN APP_DETAIL_04NH.LOGOURL % TYPE,
    P_DACTICHHANGHOA IN APP_DETAIL_04NH.DACTICHHANGHOA % TYPE,
    P_COLOR IN APP_DETAIL_04NH.COLOR % TYPE,
    P_DESCRIPTION IN APP_DETAIL_04NH.DESCRIPTION % TYPE,
    P_HUONGQUYENUUTIEN IN APP_DETAIL_04NH.HUONGQUYENUUTIEN % TYPE,
    P_SODON_UT IN APP_DETAIL_04NH.SODON_UT % TYPE,
    P_NGAYNOPDON_UT IN APP_DETAIL_04NH.NGAYNOPDON_UT % TYPE,
    P_NUOCNOPDON_UT IN APP_DETAIL_04NH.NUOCNOPDON_UT % TYPE,
    P_NGUONGOCDIALY IN APP_DETAIL_04NH.NGUONGOCDIALY % TYPE,
    P_CHATLUONG IN APP_DETAIL_04NH.CHATLUONG % TYPE,
    P_DACTINHKHAC IN APP_DETAIL_04NH.DACTINHKHAC % TYPE,
    P_CDK_NAME_1 IN APP_DETAIL_04NH.CDK_NAME_1 % TYPE,
    P_CDK_ADDRESS_1 IN APP_DETAIL_04NH.CDK_ADDRESS_1 % TYPE,
    P_CDK_PHONE_1 IN APP_DETAIL_04NH.CDK_PHONE_1 % TYPE,
    P_CDK_FAX_1 IN APP_DETAIL_04NH.CDK_FAX_1 % TYPE,
    P_CDK_EMAIL_1 IN APP_DETAIL_04NH.CDK_EMAIL_1 % TYPE,
    P_CDK_NAME_2 IN APP_DETAIL_04NH.CDK_NAME_2 % TYPE,
    P_CDK_ADDRESS_2 IN APP_DETAIL_04NH.CDK_ADDRESS_2 % TYPE,
    P_CDK_PHONE_2 IN APP_DETAIL_04NH.CDK_PHONE_2 % TYPE,
    P_CDK_FAX_2 IN APP_DETAIL_04NH.CDK_FAX_2 % TYPE,
    P_CDK_EMAIL_2 IN APP_DETAIL_04NH.CDK_EMAIL_2 % TYPE,
    P_CDK_NAME_3 IN APP_DETAIL_04NH.CDK_NAME_3 % TYPE,
    P_CDK_ADDRESS_3 IN APP_DETAIL_04NH.CDK_ADDRESS_3 % TYPE,
    P_CDK_PHONE_3 IN APP_DETAIL_04NH.CDK_PHONE_3 % TYPE,
    P_CDK_FAX_3 IN APP_DETAIL_04NH.CDK_FAX_3 % TYPE,
    P_CDK_EMAIL_3 IN APP_DETAIL_04NH.CDK_EMAIL_3 % TYPE,
    P_CDK_NAME_4 IN APP_DETAIL_04NH.CDK_NAME_4 % TYPE,
    P_CDK_ADDRESS_4 IN APP_DETAIL_04NH.CDK_ADDRESS_4 % TYPE,
    P_CDK_PHONE_4 IN APP_DETAIL_04NH.CDK_PHONE_4 % TYPE,
    P_CDK_FAX_4 IN APP_DETAIL_04NH.CDK_FAX_4 % TYPE,
    P_CDK_EMAIL_4 IN APP_DETAIL_04NH.CDK_EMAIL_4 % TYPE,
    P_USED_SPECIAL IN APP_DETAIL_04NH.USED_SPECIAL % TYPE ,
    P_LOAINHANHIEU IN VARCHAR2 ,
    P_RETURN OUT NUMBER
)
IS
V_ID NUMBER  ;

BEGIN

    P_RETURN:= PKG_COMMON.SUCESS ;
    SELECT SEQ_APP_DETAIL_01.NEXTVAL INTO V_ID FROM DUAL;

    INSERT INTO APP_DETAIL_04NH
    (
            ID, APP_HEADER_ID, APPCODE,  LANGUAGE_CODE, APPNO, DUADATE, LOGOURL, DACTICHHANGHOA,
            COLOR, DESCRIPTION, HUONGQUYENUUTIEN, SODON_UT, NGAYNOPDON_UT, NUOCNOPDON_UT, NGUONGOCDIALY, CHATLUONG,
            DACTINHKHAC, CDK_NAME_1, CDK_ADDRESS_1, CDK_PHONE_1, CDK_FAX_1, CDK_EMAIL_1, CDK_NAME_2, CDK_ADDRESS_2,
            CDK_PHONE_2, CDK_FAX_2, CDK_EMAIL_2, CDK_NAME_3, CDK_ADDRESS_3, CDK_PHONE_3, CDK_FAX_3, CDK_EMAIL_3,
            CDK_NAME_4, CDK_ADDRESS_4, CDK_PHONE_4, CDK_FAX_4, CDK_EMAIL_4, USED_SPECIAL ,
            LOAINHANHIEU
    )
    VALUES
    (
        V_ID, P_APP_HEADER_ID, P_APPCODE, P_LANGUAGE_CODE, P_APPNO, TRUNC(P_DUADATE), P_LOGOURL, P_DACTICHHANGHOA,
        P_COLOR, P_DESCRIPTION, P_HUONGQUYENUUTIEN, P_SODON_UT, TRUNC(P_NGAYNOPDON_UT), P_NUOCNOPDON_UT, P_NGUONGOCDIALY, P_CHATLUONG,
        P_DACTINHKHAC, P_CDK_NAME_1, P_CDK_ADDRESS_1, P_CDK_PHONE_1, P_CDK_FAX_1, P_CDK_EMAIL_1, P_CDK_NAME_2, P_CDK_ADDRESS_2,
        P_CDK_PHONE_2, P_CDK_FAX_2, P_CDK_EMAIL_2, P_CDK_NAME_3, P_CDK_ADDRESS_3, P_CDK_PHONE_3, P_CDK_FAX_3, P_CDK_EMAIL_3,
        P_CDK_NAME_4, P_CDK_ADDRESS_4, P_CDK_PHONE_4, P_CDK_FAX_4, P_CDK_EMAIL_4, P_USED_SPECIAL ,
        P_LOAINHANHIEU
    );

--COMMIT; KHONG COMMIT DANG DUNG TRACSACTION
EXCEPTION WHEN OTHERS THEN
RAISE;
  P_RETURN:= PKG_COMMON.ERROR ;
END;




PROCEDURE PROC_APP_DETAIL_04NH_UPDATE
(
    P_ID IN APP_DETAIL_04NH.ID % TYPE,
    P_APP_HEADER_ID IN APP_DETAIL_04NH.APP_HEADER_ID % TYPE,
    P_APPCODE IN APP_DETAIL_04NH.APPCODE % TYPE,
    P_LANGUAGE_CODE IN APP_DETAIL_04NH.LANGUAGE_CODE % TYPE,
    P_APPNO IN APP_DETAIL_04NH.APPNO % TYPE,
    P_DUADATE IN APP_DETAIL_04NH.DUADATE % TYPE,
    P_LOGOURL IN APP_DETAIL_04NH.LOGOURL % TYPE,
    P_DACTICHHANGHOA IN APP_DETAIL_04NH.DACTICHHANGHOA % TYPE,
    P_COLOR IN APP_DETAIL_04NH.COLOR % TYPE,
    P_DESCRIPTION IN APP_DETAIL_04NH.DESCRIPTION % TYPE,
    P_HUONGQUYENUUTIEN IN APP_DETAIL_04NH.HUONGQUYENUUTIEN % TYPE,
    P_SODON_UT IN APP_DETAIL_04NH.SODON_UT % TYPE,
    P_NGAYNOPDON_UT IN APP_DETAIL_04NH.NGAYNOPDON_UT % TYPE,
    P_NUOCNOPDON_UT IN APP_DETAIL_04NH.NUOCNOPDON_UT % TYPE,
    P_NGUONGOCDIALY IN APP_DETAIL_04NH.NGUONGOCDIALY % TYPE,
    P_CHATLUONG IN APP_DETAIL_04NH.CHATLUONG % TYPE,
    P_DACTINHKHAC IN APP_DETAIL_04NH.DACTINHKHAC % TYPE,
    P_CDK_NAME_1 IN APP_DETAIL_04NH.CDK_NAME_1 % TYPE,
    P_CDK_ADDRESS_1 IN APP_DETAIL_04NH.CDK_ADDRESS_1 % TYPE,
    P_CDK_PHONE_1 IN APP_DETAIL_04NH.CDK_PHONE_1 % TYPE,
    P_CDK_FAX_1 IN APP_DETAIL_04NH.CDK_FAX_1 % TYPE,
    P_CDK_EMAIL_1 IN APP_DETAIL_04NH.CDK_EMAIL_1 % TYPE,
    P_CDK_NAME_2 IN APP_DETAIL_04NH.CDK_NAME_2 % TYPE,
    P_CDK_ADDRESS_2 IN APP_DETAIL_04NH.CDK_ADDRESS_2 % TYPE,
    P_CDK_PHONE_2 IN APP_DETAIL_04NH.CDK_PHONE_2 % TYPE,
    P_CDK_FAX_2 IN APP_DETAIL_04NH.CDK_FAX_2 % TYPE,
    P_CDK_EMAIL_2 IN APP_DETAIL_04NH.CDK_EMAIL_2 % TYPE,
    P_CDK_NAME_3 IN APP_DETAIL_04NH.CDK_NAME_3 % TYPE,
    P_CDK_ADDRESS_3 IN APP_DETAIL_04NH.CDK_ADDRESS_3 % TYPE,
    P_CDK_PHONE_3 IN APP_DETAIL_04NH.CDK_PHONE_3 % TYPE,
    P_CDK_FAX_3 IN APP_DETAIL_04NH.CDK_FAX_3 % TYPE,
    P_CDK_EMAIL_3 IN APP_DETAIL_04NH.CDK_EMAIL_3 % TYPE,
    P_CDK_NAME_4 IN APP_DETAIL_04NH.CDK_NAME_4 % TYPE,
    P_CDK_ADDRESS_4 IN APP_DETAIL_04NH.CDK_ADDRESS_4 % TYPE,
    P_CDK_PHONE_4 IN APP_DETAIL_04NH.CDK_PHONE_4 % TYPE,
    P_CDK_FAX_4 IN APP_DETAIL_04NH.CDK_FAX_4 % TYPE,
    P_CDK_EMAIL_4 IN APP_DETAIL_04NH.CDK_EMAIL_4 % TYPE,
    P_USED_SPECIAL IN APP_DETAIL_04NH.USED_SPECIAL % TYPE ,
    P_LOAINHANHIEU IN VARCHAR2 ,

    P_RETURN OUT NUMBER
)
IS
BEGIN
    P_RETURN:= PKG_COMMON.SUCESS ;
    UPDATE APP_DETAIL_04NH SET
    APPNO = P_APPNO,   DUADATE = TRUNC(P_DUADATE), LOGOURL = P_LOGOURL,
    DACTICHHANGHOA = P_DACTICHHANGHOA,   COLOR = P_COLOR,
    DESCRIPTION = P_DESCRIPTION,   HUONGQUYENUUTIEN = P_HUONGQUYENUUTIEN,  SODON_UT = P_SODON_UT,
    NGAYNOPDON_UT = TRUNC(P_NGAYNOPDON_UT), NUOCNOPDON_UT = P_NUOCNOPDON_UT,
    NGUONGOCDIALY = P_NGUONGOCDIALY,   CHATLUONG = P_CHATLUONG,
    DACTINHKHAC = P_DACTINHKHAC,  CDK_NAME_1 = P_CDK_NAME_1,
    CDK_ADDRESS_1 = P_CDK_ADDRESS_1,   CDK_PHONE_1 = P_CDK_PHONE_1,
    CDK_FAX_1 = P_CDK_FAX_1,  CDK_EMAIL_1 = P_CDK_EMAIL_1,
    CDK_NAME_2 = P_CDK_NAME_2,   CDK_ADDRESS_2 = P_CDK_ADDRESS_2,
    CDK_PHONE_2 = P_CDK_PHONE_2,  CDK_FAX_2 = P_CDK_FAX_2,
    CDK_EMAIL_2 = P_CDK_EMAIL_2,  CDK_NAME_3 = P_CDK_NAME_3,
    CDK_ADDRESS_3 = P_CDK_ADDRESS_3,  CDK_PHONE_3 = P_CDK_PHONE_3,
    CDK_FAX_3 = P_CDK_FAX_3,  CDK_EMAIL_3 = P_CDK_EMAIL_3,
    CDK_NAME_4 = P_CDK_NAME_4,  CDK_ADDRESS_4 = P_CDK_ADDRESS_4,
    CDK_PHONE_4 = P_CDK_PHONE_4,   CDK_FAX_4 = P_CDK_FAX_4,
    CDK_EMAIL_4 = P_CDK_EMAIL_4,  USED_SPECIAL = P_USED_SPECIAL ,
    LOAINHANHIEU =P_LOAINHANHIEU
      WHERE APP_HEADER_ID = P_APP_HEADER_ID;
--COMMIT; KHONG COMMIT DANG DUNG TRACSACTION
EXCEPTION WHEN OTHERS THEN
RAISE;
  P_RETURN:= PKG_COMMON.ERROR ;
END;


PROCEDURE PROC_APP_DETAIL_04NH_DELETE (

    P_APP_HEADER_ID IN APP_DETAIL_04NH.APP_HEADER_ID % TYPE,
    P_APPCODE IN APP_DETAIL_04NH.APPCODE % TYPE,
    P_LANGUAGE_CODE IN APP_DETAIL_04NH.LANGUAGE_CODE % TYPE,
    P_RETURN OUT NUMBER
)
IS
BEGIN
 P_RETURN:= PKG_COMMON.SUCESS ;
 DELETE  APP_DETAIL_04NH WHERE   APP_HEADER_ID = P_APP_HEADER_ID AND  APPCODE = P_APPCODE AND LANGUAGE_CODE = P_LANGUAGE_CODE ;

EXCEPTION WHEN OTHERS THEN
RAISE;
  P_RETURN:= PKG_COMMON.ERROR ;
END  ;



   -- ENTER FURTHER CODE BELOW AS SPECIFIED IN THE PACKAGE SPEC.
END;
/


-- End of DDL Script for Package LEGALTECH.PKG_APP_DETAIL_04NH

