-- Start of DDL Script for Table LEGALTECH.APP_DOCUMENT_OTHERS
-- Generated 06/06/2018 10:51:32 PM from LEGALTECH@LOCAL

CREATE TABLE app_document_others
    (id                             NUMBER,
    app_header_id                  NUMBER,
    documentname                   VARCHAR2(250 CHAR),
    filename                       VARCHAR2(250 CHAR),
    deleted                        NUMBER(1,0) DEFAULT 0)
  SEGMENT CREATION IMMEDIATE
  PCTFREE     10
  INITRANS    1
  MAXTRANS    255
  TABLESPACE  users
  STORAGE   (
    INITIAL     65536
    NEXT        1048576
    MINEXTENTS  1
    MAXEXTENTS  2147483645
  )
  NOCACHE
  MONITORING
  NOPARALLEL
  LOGGING
/
 

-- Comments for APP_DOCUMENT_OTHERS

COMMENT ON COLUMN app_document_others.deleted IS '0:binh thuong 1:xoa'
/

-- End of DDL Script for Table LEGALTECH.APP_DOCUMENT_OTHERS

ALTER TABLE APP_DOCUMENT_OTHERS 
 ADD (
  LANGUAGE_CODE VARCHAR2 (5)
 )
/


ALTER TABLE APP_CLASS_DETAIL 
 ADD (
  LANGUAGE_CODE VARCHAR2 (5)
 )
/

-- Start of DDL Script for Sequence LEGALTECH.SEQ_APP_DOC_OTHER
-- Generated 06/06/2018 11:37:45 PM from LEGALTECH@LOCAL

CREATE SEQUENCE seq_app_doc_other
  INCREMENT BY 1
  START WITH 1
  MINVALUE 1
  MAXVALUE 9999999999999999999999999999
  NOCYCLE
  NOORDER
  CACHE 20
/


-- End of DDL Script for Sequence LEGALTECH.SEQ_APP_DOC_OTHER



-- Start of DDL Script for Package LEGALTECH.PKG_APP_DOC_OTHERS
-- Generated 06/06/2018 11:40:54 PM from LEGALTECH@LOCAL

CREATE OR REPLACE 
PACKAGE pkg_app_doc_others
  IS
 PROCEDURE PROC_APP_DOC_OTHER_INSERT
(
    P_APP_HEADER_ID IN NUMBER ,
    P_DOCUMENTNAME IN VARCHAR2 ,
    P_FILENAME IN VARCHAR2 ,
    P_LANGUAGE_CODE IN VARCHAR2 ,
    P_RETURN OUT NUMBER
);

PROCEDURE PROC_APP_DOC_OTHER_DEL_BY_ID
(
    P_ID IN NUMBER ,
    P_LANGUAGE_CODE IN VARCHAR2 ,
    P_RETURN OUT NUMBER
);

PROCEDURE PROC_APP_DOC_OTHER_DEL_BY_APP
(
    P_APP_HEADER_ID IN NUMBER ,
    P_LANGUAGE_CODE IN VARCHAR2 ,
    P_RETURN OUT NUMBER
);


END; -- Package spec
/


CREATE OR REPLACE 
PACKAGE BODY pkg_app_doc_others
IS

PROCEDURE PROC_APP_DOC_OTHER_INSERT
(
    P_APP_HEADER_ID IN NUMBER ,
    P_DOCUMENTNAME IN VARCHAR2 ,
    P_FILENAME IN VARCHAR2 ,
    P_LANGUAGE_CODE IN VARCHAR2 ,
    P_RETURN OUT NUMBER
)
IS
V_ID NUMBER := 0 ;

BEGIN
    P_RETURN:= PKG_COMMON.SUCESS ;
    SELECT SEQ_APP_DOC_OTHER.NEXTVAL INTO V_ID FROM DUAL;
    INSERT INTO APP_DOCUMENT_OTHERS ( ID, APP_HEADER_ID, DOCUMENTNAME, FILENAME ,  DELETED ,LANGUAGE_CODE  )
    VALUES ( V_ID, P_APP_HEADER_ID, P_DOCUMENTNAME,P_FILENAME ,0,P_LANGUAGE_CODE);
--KHONG COMMIT INSERT BATH
EXCEPTION WHEN OTHERS THEN
RAISE;
  P_RETURN:= PKG_COMMON.ERROR ;
END;



PROCEDURE PROC_APP_DOC_OTHER_DEL_BY_ID
(
    P_ID IN NUMBER ,
    P_LANGUAGE_CODE IN VARCHAR2 ,
    P_RETURN OUT NUMBER
)
IS

BEGIN
     P_RETURN:= PKG_COMMON.SUCESS ;
        IF(P_LANGUAGE_CODE = PKG_COMMON.VI_VN)THEN
        DELETE APP_DOCUMENT_OTHERS WHERE  ID = P_ID  ;
        ELSE
        DELETE APP_DOCUMENT_OTHERS WHERE  ID = P_ID AND  LANGUAGE_CODE =P_LANGUAGE_CODE ;
        END IF ;


--KHONG COMMIT INSERT BATH
EXCEPTION WHEN OTHERS THEN
RAISE;
  P_RETURN:= PKG_COMMON.ERROR ;
END;



PROCEDURE PROC_APP_DOC_OTHER_DEL_BY_APP
(
    P_APP_HEADER_ID IN NUMBER ,
    P_LANGUAGE_CODE IN VARCHAR2 ,
    P_RETURN OUT NUMBER
)
IS

BEGIN
     P_RETURN:= PKG_COMMON.SUCESS ;
     IF(P_LANGUAGE_CODE = PKG_COMMON.VI_VN)THEN
       DELETE APP_DOCUMENT_OTHERS WHERE  APP_HEADER_ID = P_APP_HEADER_ID ;
      ELSE
        DELETE APP_DOCUMENT_OTHERS WHERE  APP_HEADER_ID = P_APP_HEADER_ID AND  LANGUAGE_CODE =P_LANGUAGE_CODE ;
      END IF ;



--KHONG COMMIT INSERT BATH
EXCEPTION WHEN OTHERS THEN
RAISE;
  P_RETURN:= PKG_COMMON.ERROR ;
END;
   -- ENTER FURTHER CODE BELOW AS SPECIFIED IN THE PACKAGE SPEC.
END;
/


-- End of DDL Script for Package LEGALTECH.PKG_APP_DOC_OTHERS

-- Start of DDL Script for Package LEGALTECH.PKG_APPCLASS_DETAIL
-- Generated 06/06/2018 11:42:48 PM from LEGALTECH@LOCAL

CREATE OR REPLACE 
PACKAGE pkg_appclass_detail
  IS

PROCEDURE PROC_APP_CLASS_DETAIL_INSERT
(

    P_TEXTINPUT IN APP_CLASS_DETAIL.TEXTINPUT % TYPE,
    P_CODE IN APP_CLASS_DETAIL.CODE % TYPE ,
    P_APP_HEADER_ID IN NUMBER ,
    P_LANGUAGE_CODE IN VARCHAR2 ,
    P_RETURN OUT NUMBER
);
PROCEDURE PROC_APP_CLASS_DETAIL_DELETE
(

    P_APP_HEADER_ID IN NUMBER ,
    P_LANGUAGE_CODE IN VARCHAR2 ,
    P_RETURN OUT NUMBER
);

END; -- PACKAGE SPEC
/


CREATE OR REPLACE 
PACKAGE BODY pkg_appclass_detail
IS

PROCEDURE PROC_APP_CLASS_DETAIL_INSERT
(

    P_TEXTINPUT IN APP_CLASS_DETAIL.TEXTINPUT % TYPE,
    P_CODE IN APP_CLASS_DETAIL.CODE % TYPE ,
    P_APP_HEADER_ID IN NUMBER ,
    P_LANGUAGE_CODE IN VARCHAR2 ,
    P_RETURN OUT NUMBER
)
IS
V_ID NUMBER := 0 ;

BEGIN
    P_RETURN:= PKG_COMMON.SUCESS ;
    SELECT SEQ_APP_CLASS_DETAIL.NEXTVAL INTO V_ID FROM DUAL;
    INSERT INTO APP_CLASS_DETAIL ( ID, TEXTINPUT, CODE ,  APP_HEADER_ID  ,language_code)
    VALUES ( V_ID, P_TEXTINPUT, P_CODE ,P_APP_HEADER_ID ,P_LANGUAGE_CODE);

--KHONG COMMIT INSERT BATH
EXCEPTION WHEN OTHERS THEN
RAISE;
  P_RETURN:= PKG_COMMON.ERROR ;
END;



PROCEDURE PROC_APP_CLASS_DETAIL_DELETE
(

    P_APP_HEADER_ID IN NUMBER ,
    P_LANGUAGE_CODE IN VARCHAR2 ,
    P_RETURN OUT NUMBER
)
IS


BEGIN
    P_RETURN:= PKG_COMMON.SUCESS ;
     IF(P_LANGUAGE_CODE = PKG_COMMON.VI_VN)THEN
     DELETE APP_CLASS_DETAIL WHERE  APP_HEADER_ID = P_APP_HEADER_ID ;
     ELSE
     DELETE APP_CLASS_DETAIL WHERE  APP_HEADER_ID = P_APP_HEADER_ID AND language_code =P_LANGUAGE_CODE ;
     END IF  ;

--KHONG COMMIT INSERT BATH
EXCEPTION WHEN OTHERS THEN
RAISE;
  P_RETURN:= PKG_COMMON.ERROR ;
END;

   -- ENTER FURTHER CODE BELOW AS SPECIFIED IN THE PACKAGE SPEC.
END;
/


-- End of DDL Script for Package LEGALTECH.PKG_APPCLASS_DETAIL



