ALTER TABLE APPLICATION_HEADER 
 ADD (
  GENCODE VARCHAR2 (20 CHAR)
 )
/
COMMENT ON COLUMN APPLICATION_HEADER.GENCODE IS 'fixed leng 20 '
/


-- Start of DDL Script for Sequence LEGALTECH.SEQ_GENCODE
-- Generated 17/05/2018 11:45:29 PM from LEGALTECH@LOCAL

CREATE SEQUENCE seq_gencode
  INCREMENT BY 1
  START WITH 1
  MINVALUE 1
  MAXVALUE 9999
  CYCLE
  NOORDER
  CACHE 5
/


-- End of DDL Script for Sequence LEGALTECH.SEQ_GENCODE

-- Start of DDL Script for Function LEGALTECH.FN_GENCODE
-- Generated 17/05/2018 11:56:03 PM from LEGALTECH@LOCAL

CREATE OR REPLACE 
FUNCTION fn_gencode ( p_appcode IN varchar2 )
  RETURN   VARCHAR2
 IS
 V_GENCODE  VARCHAR2(20) ;
BEGIN
     SELECT  LPAD(p_appcode, 8, '0')  || LPAD(TO_CHAR(SYSDATE,'YYYYMMDD'),8,'0') || LPAD(seq_gencode.NEXTVAL,4,'0') INTO V_GENCODE  FROM dual ;
     RETURN V_GENCODE  ;
EXCEPTION
   WHEN OTHERS  THEN
     RETURN  LPAD(p_appcode, 8, '0')  || LPAD(TO_CHAR(SYSDATE,'yyyyMMddHHmm'),12,'0')  ;
END;
/



-- End of DDL Script for Function LEGALTECH.FN_GENCODE
-- Start of DDL Script for Sequence LEGALTECH.SEQ_GENCODE
-- Generated 17/05/2018 11:56:14 PM from LEGALTECH@LOCAL

CREATE SEQUENCE seq_gencode
  INCREMENT BY 1
  START WITH 1
  MINVALUE 1
  MAXVALUE 9999
  CYCLE
  NOORDER
  CACHE 5
/


-- End of DDL Script for Sequence LEGALTECH.SEQ_GENCODE


