ALTER TABLE APP_DETAIL_04NH 
 ADD (
  LOAINHANHIEU VARCHAR2 (4 CHAR)
 )
/
COMMENT ON COLUMN APP_DETAIL_04NH.LOAINHANHIEU IS 'LOAI NHAN HIEU '
/

ALTER TABLE APP_DETAIL_04NH 
 MODIFY (
  HUONGQUYENUUTIEN CHAR (4)

 )
/