
PROCEDURE PROC_GET_FEE_FIX_BYHEADERID
(
   
    P_APP_HEADER_ID IN APP_FEE_FIX.APP_HEADER_ID % TYPE,
    P_CUSOR OUT PKG_COMMON.T_CURSOR  
)
IS
BEGIN
 
OPEN P_CUSOR FOR SELECT  * FROM  APP_FEE_FIX WHERE APP_HEADER_ID = P_APP_HEADER_ID ;
 
EXCEPTION WHEN OTHERS THEN
    ROLLBACK;
    RAISE;
      
END;