ALTER TABLE APP_DETAIL_04NH 
 ADD (
  CODELOGO VARCHAR2 (20 CHAR)
 )
 MODIFY (
  DESCRIPTION VARCHAR2 (2500 CHAR)

 )
/
COMMENT ON COLUMN APP_DETAIL_04NH.CODELOGO IS 'qui tac dat ten code cho logo sau nay de phuc vu tim kiem '
/