
PROCEDURE PROC_APP_HEADER_UPDATE
(
    P_ID IN NUMBER ,
    P_APPCODE IN APPLICATION_HEADER.APPCODE % TYPE,
    P_MASTER_NAME IN APPLICATION_HEADER.MASTER_NAME % TYPE,
    P_MASTER_ADDRESS IN APPLICATION_HEADER.MASTER_ADDRESS % TYPE,
    P_MASTER_PHONE IN APPLICATION_HEADER.MASTER_PHONE % TYPE,
    P_MASTER_FAX IN VARCHAR ,
    P_MASTER_EMAIL IN VARCHAR ,
    P_REP_MASTER_TYPE IN APPLICATION_HEADER.REP_MASTER_TYPE % TYPE,
    P_REP_MASTER_NAME IN APPLICATION_HEADER.REP_MASTER_NAME % TYPE,
    P_REP_MASTER_ADDRESS IN APPLICATION_HEADER.REP_MASTER_ADDRESS % TYPE,
    P_REP_MASTER_PHONE IN APPLICATION_HEADER.REP_MASTER_PHONE % TYPE,
    P_REP_MASTER_FAX IN APPLICATION_HEADER.REP_MASTER_FAX % TYPE,
    P_REP_MASTER_EMAIL IN APPLICATION_HEADER.REP_MASTER_EMAIL % TYPE,
    P_SEND_DATE IN APPLICATION_HEADER.SEND_DATE % TYPE,
    P_STATUS IN APPLICATION_HEADER.STATUS % TYPE,
    P_MODIFY_BY IN APPLICATION_HEADER.modify_by % TYPE,
    P_MODIFY_DATE IN APPLICATION_HEADER.modify_date % TYPE,
    P_LANGUAGUE_CODE IN APPLICATION_HEADER.LANGUAGUE_CODE % TYPE  ,
    P_ADDRESS IN VARCHAR2  ,
    P_DATENO IN VARCHAR2 ,
    P_MONTHS IN VARCHAR2 ,
    P_YEARS IN VARCHAR2 ,
    P_RETURN OUT NUMBER
)
IS
BEGIN
     P_RETURN:= 0 ;

    UPDATE APPLICATION_HEADER SET
        --APPCODE = P_APPCODE, KHONG DUOC SUA
        MASTER_NAME = P_MASTER_NAME,
        MASTER_ADDRESS = P_MASTER_ADDRESS,
        MASTER_PHONE = P_MASTER_PHONE,
        REP_MASTER_TYPE = P_REP_MASTER_TYPE,
        REP_MASTER_NAME = P_REP_MASTER_NAME,
        REP_MASTER_ADDRESS = P_REP_MASTER_ADDRESS,
        REP_MASTER_PHONE = P_REP_MASTER_PHONE,
        REP_MASTER_FAX = P_REP_MASTER_FAX,
        REP_MASTER_EMAIL = P_REP_MASTER_EMAIL,
        SEND_DATE = P_SEND_DATE,
        STATUS = P_STATUS,
        MODIFY_BY = P_MODIFY_BY,
        MODIFY_DATE = P_MODIFY_DATE ,
        MASTER_EMAIL=P_MASTER_EMAIL ,
        MASTER_FAX= P_MASTER_FAX ,
        ADDRESS = P_ADDRESS , DATENO =P_DATENO ,MONTHS =P_MONTHS ,YEARS =P_YEARS

    WHERE ID = P_ID AND LANGUAGUE_CODE = P_LANGUAGUE_CODE;
 
EXCEPTION WHEN OTHERS THEN
    P_RETURN:=PKG_COMMON.ERROR ;
    ROLLBACK ;
    RAISE;
END;
