ALTER TABLE APPLICATION_HEADER 
 ADD (
  App_No VARCHAR2 (100 CHAR),
  App_Degree VARCHAR2 (100 CHAR)
 )
/
COMMENT ON COLUMN APPLICATION_HEADER.App_No IS 'So don cua cuc cap'
/
COMMENT ON COLUMN APPLICATION_HEADER.App_Degree IS 'So bang cua cuc cap'
/
