DROP TABLE country;
/
CREATE TABLE country
    (country_id                     NUMBER,
    name                           NVARCHAR2(200),
    short_name                     NVARCHAR2(10))
/    
INSERT INTO country (country_id,name, short_name) VALUES(1,'AFGHANISTAN','AF');
INSERT INTO country (country_id,name, short_name) VALUES(2,'ÅLAND ISLANDS','AX');
INSERT INTO country (country_id,name, short_name) VALUES(3,'ALBANIA','AL');
INSERT INTO country (country_id,name, short_name) VALUES(4,'ALGERIA','DZ');
INSERT INTO country (country_id,name, short_name) VALUES(5,'AMERICAN SAMOA','AS');
INSERT INTO country (country_id,name, short_name) VALUES(6,'ANDORRA','AD');
INSERT INTO country (country_id,name, short_name) VALUES(7,'ANGOLA','AO');
INSERT INTO country (country_id,name, short_name) VALUES(8,'ANGUILLA','AI');
INSERT INTO country (country_id,name, short_name) VALUES(9,'ANTARCTICA','AQ');
INSERT INTO country (country_id,name, short_name) VALUES(10,'ANTIGUA AND BARBUDA','AG');
INSERT INTO country (country_id,name, short_name) VALUES(11,'ARGENTINA','AR');
INSERT INTO country (country_id,name, short_name) VALUES(12,'ARMENIA','AM');
INSERT INTO country (country_id,name, short_name) VALUES(13,'ARUBA','AW');
INSERT INTO country (country_id,name, short_name) VALUES(14,'AUSTRALIA','AU');
INSERT INTO country (country_id,name, short_name) VALUES(15,'AUSTRIA','AT');
INSERT INTO country (country_id,name, short_name) VALUES(16,'AZERBAIJAN','AZ');
INSERT INTO country (country_id,name, short_name) VALUES(17,'BAHAMAS','BS');
INSERT INTO country (country_id,name, short_name) VALUES(18,'BAHRAIN','BH');
INSERT INTO country (country_id,name, short_name) VALUES(19,'BANGLADESH','BD');
INSERT INTO country (country_id,name, short_name) VALUES(20,'BARBADOS','BB');
INSERT INTO country (country_id,name, short_name) VALUES(21,'BELARUS','BY');
INSERT INTO country (country_id,name, short_name) VALUES(22,'BELGIUM','BE');
INSERT INTO country (country_id,name, short_name) VALUES(23,'BELIZE','BZ');
INSERT INTO country (country_id,name, short_name) VALUES(24,'BENIN','BJ');
INSERT INTO country (country_id,name, short_name) VALUES(25,'BERMUDA','BM');
INSERT INTO country (country_id,name, short_name) VALUES(26,'BHUTAN','BT');
INSERT INTO country (country_id,name, short_name) VALUES(27,'BOLIVIA','BO');
INSERT INTO country (country_id,name, short_name) VALUES(28,'BOSNIA AND HERZEGOVINA','BA');
INSERT INTO country (country_id,name, short_name) VALUES(29,'BOTSWANA','BW');
INSERT INTO country (country_id,name, short_name) VALUES(30,'BOUVET ISLAND','BV');
INSERT INTO country (country_id,name, short_name) VALUES(31,'BRAZIL','BR');
INSERT INTO country (country_id,name, short_name) VALUES(32,'BRITISH INDIAN OCEAN TERRITORY','IO');
INSERT INTO country (country_id,name, short_name) VALUES(33,'BRUNEI DARUSSALAM','BN');
INSERT INTO country (country_id,name, short_name) VALUES(34,'BULGARIA','BG');
INSERT INTO country (country_id,name, short_name) VALUES(35,'BURKINA FASO','BF');
INSERT INTO country (country_id,name, short_name) VALUES(36,'BURUNDI','BI');
INSERT INTO country (country_id,name, short_name) VALUES(37,'CAMBODIA','KH');
INSERT INTO country (country_id,name, short_name) VALUES(38,'CAMEROON','CM');
INSERT INTO country (country_id,name, short_name) VALUES(39,'CANADA','CA');
INSERT INTO country (country_id,name, short_name) VALUES(40,'CAPE VERDE','CV');
INSERT INTO country (country_id,name, short_name) VALUES(41,'CAYMAN ISLANDS','KY');
INSERT INTO country (country_id,name, short_name) VALUES(42,'CENTRAL AFRICAN REPUBLIC','CF');
INSERT INTO country (country_id,name, short_name) VALUES(43,'CHAD','TD');
INSERT INTO country (country_id,name, short_name) VALUES(44,'CHILE','CL');
INSERT INTO country (country_id,name, short_name) VALUES(45,'CHINA','CN');
INSERT INTO country (country_id,name, short_name) VALUES(46,'CHRISTMAS ISLAND','CX');
INSERT INTO country (country_id,name, short_name) VALUES(47,'COCOS (KEELING) ISLANDS','CC');
INSERT INTO country (country_id,name, short_name) VALUES(48,'COLOMBIA','CO');
INSERT INTO country (country_id,name, short_name) VALUES(49,'COMOROS','KM');
INSERT INTO country (country_id,name, short_name) VALUES(50,'CONGO','CG');
INSERT INTO country (country_id,name, short_name) VALUES(51,'CONGO, THE DEMOCRATIC REPUBLIC OF THE','CD');
INSERT INTO country (country_id,name, short_name) VALUES(52,'COOK ISLANDS','CK');
INSERT INTO country (country_id,name, short_name) VALUES(53,'COSTA RICA','CR');
INSERT INTO country (country_id,name, short_name) VALUES(54,'CÔTE DIVOIRE','CI');
INSERT INTO country (country_id,name, short_name) VALUES(55,'CROATIA','HR');
INSERT INTO country (country_id,name, short_name) VALUES(56,'CUBA','CU');
INSERT INTO country (country_id,name, short_name) VALUES(57,'CYPRUS','CY');
INSERT INTO country (country_id,name, short_name) VALUES(58,'CZECH REPUBLIC','CZ');
INSERT INTO country (country_id,name, short_name) VALUES(59,'DENMARK','DK');
INSERT INTO country (country_id,name, short_name) VALUES(60,'DJIBOUTI','DJ');
INSERT INTO country (country_id,name, short_name) VALUES(61,'DOMINICA','DM');
INSERT INTO country (country_id,name, short_name) VALUES(62,'DOMINICAN REPUBLIC','DO');
INSERT INTO country (country_id,name, short_name) VALUES(63,'ECUADOR','EC');
INSERT INTO country (country_id,name, short_name) VALUES(64,'EGYPT','EG');
INSERT INTO country (country_id,name, short_name) VALUES(65,'EL SALVADOR','SV');
INSERT INTO country (country_id,name, short_name) VALUES(66,'EQUATORIAL GUINEA','GQ');
INSERT INTO country (country_id,name, short_name) VALUES(67,'ERITREA','ER');
INSERT INTO country (country_id,name, short_name) VALUES(68,'ESTONIA','EE');
INSERT INTO country (country_id,name, short_name) VALUES(69,'ETHIOPIA','ET');
INSERT INTO country (country_id,name, short_name) VALUES(70,'FALKLAND ISLANDS (MALVINAS)','FK');
INSERT INTO country (country_id,name, short_name) VALUES(71,'FAROE ISLANDS','FO');
INSERT INTO country (country_id,name, short_name) VALUES(72,'FIJI','FJ');
INSERT INTO country (country_id,name, short_name) VALUES(73,'FINLAND','FI');
INSERT INTO country (country_id,name, short_name) VALUES(74,'FRANCE','FR');
INSERT INTO country (country_id,name, short_name) VALUES(75,'FRENCH GUIANA','GF');
INSERT INTO country (country_id,name, short_name) VALUES(76,'FRENCH POLYNESIA','PF');
INSERT INTO country (country_id,name, short_name) VALUES(77,'FRENCH SOUTHERN TERRITORIES','TF');
INSERT INTO country (country_id,name, short_name) VALUES(78,'GABON','GA');
INSERT INTO country (country_id,name, short_name) VALUES(79,'GAMBIA','GM');
INSERT INTO country (country_id,name, short_name) VALUES(80,'GEORGIA','GE');
INSERT INTO country (country_id,name, short_name) VALUES(81,'GERMANY','DE');
INSERT INTO country (country_id,name, short_name) VALUES(82,'GHANA','GH');
INSERT INTO country (country_id,name, short_name) VALUES(83,'GIBRALTAR','GI');
INSERT INTO country (country_id,name, short_name) VALUES(84,'GREECE','GR');
INSERT INTO country (country_id,name, short_name) VALUES(85,'GREENLAND','GL');
INSERT INTO country (country_id,name, short_name) VALUES(86,'GRENADA','GD');
INSERT INTO country (country_id,name, short_name) VALUES(87,'GUADELOUPE','GP');
INSERT INTO country (country_id,name, short_name) VALUES(88,'GUAM','GU');
INSERT INTO country (country_id,name, short_name) VALUES(89,'GUATEMALA','GT');
INSERT INTO country (country_id,name, short_name) VALUES(90,'GUINEA','GN');
INSERT INTO country (country_id,name, short_name) VALUES(91,'GUINEA-BISSAU','GW');
INSERT INTO country (country_id,name, short_name) VALUES(92,'GUYANA','GY');
INSERT INTO country (country_id,name, short_name) VALUES(93,'HAITI','HT');
INSERT INTO country (country_id,name, short_name) VALUES(94,'HEARD ISLAND AND MCDONALD ISLANDS','HM');
INSERT INTO country (country_id,name, short_name) VALUES(95,'HOLY SEE (VATICAN CITY STATE)','VA');
INSERT INTO country (country_id,name, short_name) VALUES(96,'HONDURAS','HN');
INSERT INTO country (country_id,name, short_name) VALUES(97,'HONG KONG','HK');
INSERT INTO country (country_id,name, short_name) VALUES(98,'HUNGARY','HU');
INSERT INTO country (country_id,name, short_name) VALUES(99,'ICELAND','IS');
INSERT INTO country (country_id,name, short_name) VALUES(100,'INDIA','IN');
INSERT INTO country (country_id,name, short_name) VALUES(101,'INDONESIA','ID');
INSERT INTO country (country_id,name, short_name) VALUES(102,'IRAN, ISLAMIC REPUBLIC OF','IR');
INSERT INTO country (country_id,name, short_name) VALUES(103,'IRAQ','IQ');
INSERT INTO country (country_id,name, short_name) VALUES(104,'IRELAND','IE');
INSERT INTO country (country_id,name, short_name) VALUES(105,'ISRAEL','IL');
INSERT INTO country (country_id,name, short_name) VALUES(106,'ITALY','IT');
INSERT INTO country (country_id,name, short_name) VALUES(107,'JAMAICA','JM');
INSERT INTO country (country_id,name, short_name) VALUES(108,'JAPAN','JP');
INSERT INTO country (country_id,name, short_name) VALUES(109,'JORDAN','JO');
INSERT INTO country (country_id,name, short_name) VALUES(110,'KAZAKHSTAN','KZ');
INSERT INTO country (country_id,name, short_name) VALUES(111,'KENYA','KE');
INSERT INTO country (country_id,name, short_name) VALUES(112,'KIRIBATI','KI');
INSERT INTO country (country_id,name, short_name) VALUES(113,'KOREA, DEMOCRATIC PEOPLES REPUBLIC OF','KP');
INSERT INTO country (country_id,name, short_name) VALUES(114,'KOREA, REPUBLIC OF','KR');
INSERT INTO country (country_id,name, short_name) VALUES(115,'KUWAIT','KW');
INSERT INTO country (country_id,name, short_name) VALUES(116,'KYRGYZSTAN','KG');
INSERT INTO country (country_id,name, short_name) VALUES(117,'LAO PEOPLES DEMOCRATIC REPUBLIC','LA');
INSERT INTO country (country_id,name, short_name) VALUES(118,'LATVIA','LV');
INSERT INTO country (country_id,name, short_name) VALUES(119,'LEBANON','LB');
INSERT INTO country (country_id,name, short_name) VALUES(120,'LESOTHO','LS');
INSERT INTO country (country_id,name, short_name) VALUES(121,'LIBERIA','LR');
INSERT INTO country (country_id,name, short_name) VALUES(122,'LIBYAN ARAB JAMAHIRIYA','LY');
INSERT INTO country (country_id,name, short_name) VALUES(123,'LIECHTENSTEIN','LI');
INSERT INTO country (country_id,name, short_name) VALUES(124,'LITHUANIA','LT');
INSERT INTO country (country_id,name, short_name) VALUES(125,'LUXEMBOURG','LU');
INSERT INTO country (country_id,name, short_name) VALUES(126,'MACAO','MO');
INSERT INTO country (country_id,name, short_name) VALUES(127,'MACEDONIA, THE FORMER YUGOSLAV REPUBLIC OF','MK');
INSERT INTO country (country_id,name, short_name) VALUES(128,'MADAGASCAR','MG');
INSERT INTO country (country_id,name, short_name) VALUES(129,'MALAWI','MW');
INSERT INTO country (country_id,name, short_name) VALUES(130,'MALAYSIA','MY');
INSERT INTO country (country_id,name, short_name) VALUES(131,'MALDIVES','MV');
INSERT INTO country (country_id,name, short_name) VALUES(132,'MALI','ML');
INSERT INTO country (country_id,name, short_name) VALUES(133,'MALTA','MT');
INSERT INTO country (country_id,name, short_name) VALUES(134,'MARSHALL ISLANDS','MH');
INSERT INTO country (country_id,name, short_name) VALUES(135,'MARTINIQUE','MQ');
INSERT INTO country (country_id,name, short_name) VALUES(136,'MAURITANIA','MR');
INSERT INTO country (country_id,name, short_name) VALUES(137,'MAURITIUS','MU');
INSERT INTO country (country_id,name, short_name) VALUES(138,'MAYOTTE','YT');
INSERT INTO country (country_id,name, short_name) VALUES(139,'MEXICO','MX');
INSERT INTO country (country_id,name, short_name) VALUES(140,'MICRONESIA, FEDERATED STATES OF','FM');
INSERT INTO country (country_id,name, short_name) VALUES(141,'MOLDOVA, REPUBLIC OF','MD');
INSERT INTO country (country_id,name, short_name) VALUES(142,'MONACO','MC');
INSERT INTO country (country_id,name, short_name) VALUES(143,'MONGOLIA','MN');
INSERT INTO country (country_id,name, short_name) VALUES(144,'MONTSERRAT','MS');
INSERT INTO country (country_id,name, short_name) VALUES(145,'MOROCCO','MA');
INSERT INTO country (country_id,name, short_name) VALUES(146,'MOZAMBIQUE','MZ');
INSERT INTO country (country_id,name, short_name) VALUES(147,'MYANMAR','MM');
INSERT INTO country (country_id,name, short_name) VALUES(148,'NAMIBIA','NA');
INSERT INTO country (country_id,name, short_name) VALUES(149,'NAURU','NR');
INSERT INTO country (country_id,name, short_name) VALUES(150,'NEPAL','NP');
INSERT INTO country (country_id,name, short_name) VALUES(151,'NETHERLANDS','NL');
INSERT INTO country (country_id,name, short_name) VALUES(152,'NETHERLANDS ANTILLES','AN');
INSERT INTO country (country_id,name, short_name) VALUES(153,'NEW CALEDONIA','NC');
INSERT INTO country (country_id,name, short_name) VALUES(154,'NEW ZEALAND','NZ');
INSERT INTO country (country_id,name, short_name) VALUES(155,'NICARAGUA','NI');
INSERT INTO country (country_id,name, short_name) VALUES(156,'NIGER','NE');
INSERT INTO country (country_id,name, short_name) VALUES(157,'NIGERIA','NG');
INSERT INTO country (country_id,name, short_name) VALUES(158,'NIUE','NU');
INSERT INTO country (country_id,name, short_name) VALUES(159,'NORFOLK ISLAND','NF');
INSERT INTO country (country_id,name, short_name) VALUES(160,'NORTHERN MARIANA ISLANDS','MP');
INSERT INTO country (country_id,name, short_name) VALUES(161,'NORWAY','NO');
INSERT INTO country (country_id,name, short_name) VALUES(162,'OMAN','OM');
INSERT INTO country (country_id,name, short_name) VALUES(163,'PAKISTAN','PK');
INSERT INTO country (country_id,name, short_name) VALUES(164,'PALAU','PW');
INSERT INTO country (country_id,name, short_name) VALUES(165,'PALESTINIAN TERRITORY, OCCUPIED','PS');
INSERT INTO country (country_id,name, short_name) VALUES(166,'PANAMA','PA');
INSERT INTO country (country_id,name, short_name) VALUES(167,'PAPUA NEW GUINEA','PG');
INSERT INTO country (country_id,name, short_name) VALUES(168,'PARAGUAY','PY');
INSERT INTO country (country_id,name, short_name) VALUES(169,'PERU','PE');
INSERT INTO country (country_id,name, short_name) VALUES(170,'PHILIPPINES','PH');
INSERT INTO country (country_id,name, short_name) VALUES(171,'PITCAIRN','PN');
INSERT INTO country (country_id,name, short_name) VALUES(172,'POLAND','PL');
INSERT INTO country (country_id,name, short_name) VALUES(173,'PORTUGAL','PT');
INSERT INTO country (country_id,name, short_name) VALUES(174,'PUERTO RICO','PR');
INSERT INTO country (country_id,name, short_name) VALUES(175,'QATAR','QA');
INSERT INTO country (country_id,name, short_name) VALUES(176,'RÉUNION','RE');
INSERT INTO country (country_id,name, short_name) VALUES(177,'ROMANIA','RO');
INSERT INTO country (country_id,name, short_name) VALUES(178,'RUSSIAN FEDERATION','RU');
INSERT INTO country (country_id,name, short_name) VALUES(179,'RWANDA','RW');
INSERT INTO country (country_id,name, short_name) VALUES(180,'SAINT HELENA','SH');
INSERT INTO country (country_id,name, short_name) VALUES(181,'SAINT KITTS AND NEVIS','KN');
INSERT INTO country (country_id,name, short_name) VALUES(182,'SAINT LUCIA','LC');
INSERT INTO country (country_id,name, short_name) VALUES(183,'SAINT PIERRE AND MIQUELON','PM');
INSERT INTO country (country_id,name, short_name) VALUES(184,'SAINT VINCENT AND THE GRENADINES','VC');
INSERT INTO country (country_id,name, short_name) VALUES(185,'SAMOA','WS');
INSERT INTO country (country_id,name, short_name) VALUES(186,'SAN MARINO','SM');
INSERT INTO country (country_id,name, short_name) VALUES(187,'SAO TOME AND PRINCIPE','ST');
INSERT INTO country (country_id,name, short_name) VALUES(188,'SAUDI ARABIA','SA');
INSERT INTO country (country_id,name, short_name) VALUES(189,'SENEGAL','SN');
INSERT INTO country (country_id,name, short_name) VALUES(190,'SERBIA AND MONTENEGRO','CS');
INSERT INTO country (country_id,name, short_name) VALUES(191,'SEYCHELLES','SC');
INSERT INTO country (country_id,name, short_name) VALUES(192,'SIERRA LEONE','SL');
INSERT INTO country (country_id,name, short_name) VALUES(193,'SINGAPORE','SG');
INSERT INTO country (country_id,name, short_name) VALUES(194,'SLOVAKIA','SK');
INSERT INTO country (country_id,name, short_name) VALUES(195,'SLOVENIA','SI');
INSERT INTO country (country_id,name, short_name) VALUES(196,'SOLOMON ISLANDS','SB');
INSERT INTO country (country_id,name, short_name) VALUES(197,'SOMALIA','SO');
INSERT INTO country (country_id,name, short_name) VALUES(198,'SOUTH AFRICA','ZA');
INSERT INTO country (country_id,name, short_name) VALUES(199,'SOUTH GEORGIA AND THE SOUTH SANDWICH ISLANDS','GS');
INSERT INTO country (country_id,name, short_name) VALUES(200,'SPAIN','ES');
INSERT INTO country (country_id,name, short_name) VALUES(201,'SRI LANKA','LK');
INSERT INTO country (country_id,name, short_name) VALUES(202,'SUDAN','SD');
INSERT INTO country (country_id,name, short_name) VALUES(203,'SURINAME','SR');
INSERT INTO country (country_id,name, short_name) VALUES(204,'SVALBARD AND JAN MAYEN','SJ');
INSERT INTO country (country_id,name, short_name) VALUES(205,'SWAZILAND','SZ');
INSERT INTO country (country_id,name, short_name) VALUES(206,'SWEDEN','SE');
INSERT INTO country (country_id,name, short_name) VALUES(207,'SWITZERLAND','CH');
INSERT INTO country (country_id,name, short_name) VALUES(208,'SYRIAN ARAB REPUBLIC','SY');
INSERT INTO country (country_id,name, short_name) VALUES(209,'TAIWAN, PROVINCE OF CHINA','TW');
INSERT INTO country (country_id,name, short_name) VALUES(210,'TAJIKISTAN','TJ');
INSERT INTO country (country_id,name, short_name) VALUES(211,'TANZANIA, UNITED REPUBLIC OF','TZ');
INSERT INTO country (country_id,name, short_name) VALUES(212,'THAILAND','TH');
INSERT INTO country (country_id,name, short_name) VALUES(213,'TIMOR-LESTE','TL');
INSERT INTO country (country_id,name, short_name) VALUES(214,'TOGO','TG');
INSERT INTO country (country_id,name, short_name) VALUES(215,'TOKELAU','TK');
INSERT INTO country (country_id,name, short_name) VALUES(216,'TONGA','TO');
INSERT INTO country (country_id,name, short_name) VALUES(217,'TRINIDAD AND TOBAGO','TT');
INSERT INTO country (country_id,name, short_name) VALUES(218,'TUNISIA','TN');
INSERT INTO country (country_id,name, short_name) VALUES(219,'TURKEY','TR');
INSERT INTO country (country_id,name, short_name) VALUES(220,'TURKMENISTAN','TM');
INSERT INTO country (country_id,name, short_name) VALUES(221,'TURKS AND CAICOS ISLANDS','TC');
INSERT INTO country (country_id,name, short_name) VALUES(222,'TUVALU','TV');
INSERT INTO country (country_id,name, short_name) VALUES(223,'UGANDA','UG');
INSERT INTO country (country_id,name, short_name) VALUES(224,'UKRAINE','UA');
INSERT INTO country (country_id,name, short_name) VALUES(225,'UNITED ARAB EMIRATES','AE');
INSERT INTO country (country_id,name, short_name) VALUES(226,'UNITED KINGDOM','GB');
INSERT INTO country (country_id,name, short_name) VALUES(227,'UNITED STATES','US');
INSERT INTO country (country_id,name, short_name) VALUES(228,'UNITED STATES MINOR OUTLYING ISLANDS','UM');
INSERT INTO country (country_id,name, short_name) VALUES(229,'URUGUAY','UY');
INSERT INTO country (country_id,name, short_name) VALUES(230,'UZBEKISTAN','UZ');
INSERT INTO country (country_id,name, short_name) VALUES(231,'VANUATU','VU');
INSERT INTO country (country_id,name, short_name) VALUES(232,'Vatican City State see HOLY SEE                                                                                                                      VA','');
INSERT INTO country (country_id,name, short_name) VALUES(233,'VENEZUELA','VE');
INSERT INTO country (country_id,name, short_name) VALUES(234,'VIET NAM','VN');
INSERT INTO country (country_id,name, short_name) VALUES(235,'VIRGIN ISLANDS, BRITISH','VG');
INSERT INTO country (country_id,name, short_name) VALUES(236,'VIRGIN ISLANDS, U.S.','VI');
INSERT INTO country (country_id,name, short_name) VALUES(237,'WALLIS AND FUTUNA','WF');
INSERT INTO country (country_id,name, short_name) VALUES(238,'WESTERN SAHARA','EH');
INSERT INTO country (country_id,name, short_name) VALUES(239,'YEMEN','YE');
INSERT INTO country (country_id,name, short_name) VALUES(240,'ZAMBIA','ZM');
INSERT INTO country (country_id,name, short_name) VALUES(241,'ZIMBABWE','ZW');

