-- Start of DDL Script for Package Body LEGALTECH.PKG_APP_HEADER
-- Generated 9-Jul-2018 0:03:53 from LEGALTECH@LOCALHOST

CREATE OR REPLACE 
PACKAGE pkg_app_header
  IS
APP_HEADER_STATUS_LUUTAM CONSTANT NUMBER(1) := 0;
APP_HEADER_STATUS_CHOPHANLOAI CONSTANT NUMBER(1) := 1;
APP_HEADER_STATUS_DAGUI2LS CONSTANT NUMBER(1) := 2;
APP_HEADER_STATUS_LS_DA_CF CONSTANT NUMBER(1) := 3;
APP_HEADER_STATUS_CHO_KH_CF CONSTANT NUMBER(1) := 4;
APP_HEADER_STATUS_KH_DA_CF CONSTANT NUMBER(1) := 5;
APP_HEADER_STATUS_KH_DA_RJ CONSTANT NUMBER(2) := 51;
APP_HEADER_STATUS_FILLING CONSTANT NUMBER(1) := 6;

PROCEDURE proc_update_status
(
    p_id IN NUMBER,
    p_status IN NUMBER,
    p_notes IN VARCHAR2,
    p_modify_by IN VARCHAR2,
    p_modify_date IN DATE,
    p_return OUT NUMBER
);

PROCEDURE PROC_APPLICATION_HEADER_SEARCH
(
    P_SEARCH_KEY IN VARCHAR2,
    P_FROM IN VARCHAR2,
    P_TO IN VARCHAR2,
    P_SORT_TYPE IN VARCHAR2,
    P_TOTAL_RECORD OUT NUMBER,
    P_CURSOR OUT pkg_common.t_cursor
);


PROCEDURE PROC_APP_HEADER_INSERT
(
    P_APPCODE IN APPLICATION_HEADER.APPCODE % TYPE,
    P_MASTER_NAME IN APPLICATION_HEADER.MASTER_NAME % TYPE,
    P_MASTER_ADDRESS IN APPLICATION_HEADER.MASTER_ADDRESS % TYPE,
    P_MASTER_PHONE IN APPLICATION_HEADER.MASTER_PHONE % TYPE,
    P_MASTER_FAX IN VARCHAR ,
    P_MASTER_EMAIL IN VARCHAR ,
    P_REP_MASTER_TYPE IN APPLICATION_HEADER.REP_MASTER_TYPE % TYPE,
    P_REP_MASTER_NAME IN APPLICATION_HEADER.REP_MASTER_NAME % TYPE,
    P_REP_MASTER_ADDRESS IN APPLICATION_HEADER.REP_MASTER_ADDRESS % TYPE,
    P_REP_MASTER_PHONE IN APPLICATION_HEADER.REP_MASTER_PHONE % TYPE,
    P_REP_MASTER_FAX IN APPLICATION_HEADER.REP_MASTER_FAX % TYPE,
    P_REP_MASTER_EMAIL IN APPLICATION_HEADER.REP_MASTER_EMAIL % TYPE,
    P_SEND_DATE IN APPLICATION_HEADER.SEND_DATE % TYPE,
    P_STATUS IN APPLICATION_HEADER.STATUS % TYPE,
    P_CREATED_BY IN APPLICATION_HEADER.CREATED_BY % TYPE,
    P_CREATED_DATE IN APPLICATION_HEADER.CREATED_DATE % TYPE,
    P_LANGUAGUE_CODE IN APPLICATION_HEADER.LANGUAGUE_CODE % TYPE  ,
    P_ADDRESS IN VARCHAR2  ,
    P_DATENO IN VARCHAR2 ,
    P_MONTHS IN VARCHAR2 ,
    P_YEARS IN VARCHAR2 ,
    p_client_reference IN VARCHAR2,
    p_case_name IN VARCHAR2,
    P_RETURN OUT NUMBER
);


PROCEDURE PROC_APP_HEADER_UPDATE
(
    P_ID IN NUMBER ,
    P_APPCODE IN APPLICATION_HEADER.APPCODE % TYPE,
    P_MASTER_NAME IN APPLICATION_HEADER.MASTER_NAME % TYPE,
    P_MASTER_ADDRESS IN APPLICATION_HEADER.MASTER_ADDRESS % TYPE,
    P_MASTER_PHONE IN APPLICATION_HEADER.MASTER_PHONE % TYPE,
    P_MASTER_FAX IN VARCHAR ,
    P_MASTER_EMAIL IN VARCHAR ,
    P_REP_MASTER_TYPE IN APPLICATION_HEADER.REP_MASTER_TYPE % TYPE,
    P_REP_MASTER_NAME IN APPLICATION_HEADER.REP_MASTER_NAME % TYPE,
    P_REP_MASTER_ADDRESS IN APPLICATION_HEADER.REP_MASTER_ADDRESS % TYPE,
    P_REP_MASTER_PHONE IN APPLICATION_HEADER.REP_MASTER_PHONE % TYPE,
    P_REP_MASTER_FAX IN APPLICATION_HEADER.REP_MASTER_FAX % TYPE,

    P_REP_MASTER_EMAIL IN APPLICATION_HEADER.REP_MASTER_EMAIL % TYPE,
    P_SEND_DATE IN APPLICATION_HEADER.SEND_DATE % TYPE,
    P_STATUS IN APPLICATION_HEADER.STATUS % TYPE,
    P_MODIFY_BY IN APPLICATION_HEADER.MODIFY_BY % TYPE,
    P_MODIFY_DATE IN APPLICATION_HEADER.MODIFY_DATE % TYPE,
    P_LANGUAGUE_CODE IN APPLICATION_HEADER.LANGUAGUE_CODE % TYPE  ,
    P_ADDRESS IN VARCHAR2  ,
    P_DATENO IN VARCHAR2 ,
    P_MONTHS IN VARCHAR2 ,
    P_YEARS IN VARCHAR2 ,
    p_client_reference IN VARCHAR2,
    p_case_name IN VARCHAR2,
    P_RETURN OUT NUMBER
);

PROCEDURE PROC_APP_HEADER_DELETED
(
    P_ID IN NUMBER ,
    P_LANGUAGUE_CODE IN VARCHAR2 ,
    P_RETURN OUT NUMBER
);

PROCEDURE proc_getByAppNo
(
    p_appNo IN VARCHAR2,
    p_user_name IN VARCHAR2,
    p_languague_code IN VARCHAR2 ,
    p_cursor OUT pkg_common.t_cursor
);

END;
/


CREATE OR REPLACE 
PACKAGE BODY pkg_app_header
IS

PROCEDURE PROC_APPLICATION_HEADER_SEARCH
(
    P_SEARCH_KEY IN VARCHAR2,
    P_FROM IN VARCHAR2,
    P_TO IN VARCHAR2,
    P_SORT_TYPE IN VARCHAR2,
    P_TOTAL_RECORD OUT NUMBER,
    P_CURSOR OUT PKG_COMMON.T_CURSOR
)
IS
    V_SQL VARCHAR2(32000) DEFAULT '';
    V_CONDITION VARCHAR2(4000) DEFAULT '';
    V_TOTAL_COUNT VARCHAR2(32000) DEFAULT '';

    V_INDEX NUMBER DEFAULT 0;
    CURSOR V_CUR_CONDITION IS
        SELECT COLUMN_VALUE AS CONDITION FROM TABLE(FN_PARSER(P_SEARCH_KEY,'|'));

    V_STATUS VARCHAR2(3) DEFAULT 'ALL';
    V_APP_CODE VARCHAR2(10) DEFAULT 'ALL';
    V_MASTER_NAME VARCHAR2(100) DEFAULT 'ALL';

    V_FROM NUMBER ;
    V_TO NUMBER;
BEGIN


    -- LAY RA CAC DK TIM KIEM
    FOR ITEM IN V_CUR_CONDITION LOOP

        IF V_INDEX = 0 THEN
            V_APP_CODE := ITEM.CONDITION;
        ELSIF V_INDEX = 1 THEN
            V_STATUS := ITEM.CONDITION;
        ELSIF V_INDEX = 2 THEN
            V_MASTER_NAME := ITEM.CONDITION;
        END IF;

        V_INDEX := V_INDEX + 1;
    END LOOP;

    IF V_APP_CODE <> 'ALL' THEN
        V_CONDITION := V_CONDITION || ' AND A.APPCODE = ''' || V_APP_CODE || '''';
    END IF;

    IF V_STATUS <> 'ALL' THEN
        V_CONDITION := V_CONDITION || ' AND A.STATUS = ' || V_STATUS;
    END IF;

    IF V_MASTER_NAME <> 'ALL' THEN
        V_CONDITION :=  V_CONDITION || ' AND UPPER(A.MASTER_NAME) LIKE ''%' || UPPER(V_MASTER_NAME) || '%'' ';
    END IF;


   /* V_SQL := 'SELECT  A.*, AL1.CONTENT AS STATUS_NAME, AL2.CONTENT AS STATUS_FORMM_NAME, AL3.CONTENT AS STATUS_CONTENT_NAME,SA.APPNAME
      FROM APPLICATION_HEADER A
      JOIN SYS_APPLICATION SA ON SA.APPCODE = A.APPCODE AND A.LANGUAGUE_CODE = SA.LANGUAGECODE
      LEFT JOIN ALLCODE AL1 ON AL1.CDVAL = TO_CHAR(A.STATUS) AND AL1.CDNAME = ''APP'' AND AL1.CDTYPE = ''STATUS''
      LEFT JOIN ALLCODE AL2 ON AL2.CDVAL = A.STATUS_FORM AND AL2.CDNAME = ''APP'' AND AL2.CDTYPE = ''STATUS_FORM''
      LEFT JOIN ALLCODE AL3 ON AL3.CDVAL = A.STATUS_CONTENT AND AL3.CDNAME = ''APP'' AND AL3.CDTYPE = ''STATUS_CONTENT'' WHERE 1 = 1 AND A.DELETED=0 ';
    */

    V_SQL := 'SELECT  A.* FROM view_app_header A WHERE 1 = 1 ';
    V_SQL :=  V_SQL || V_CONDITION;

    IF P_SORT_TYPE <> 'ALL' THEN
        V_SQL :=  V_SQL || P_SORT_TYPE;
    ELSE
        V_SQL :=  V_SQL || ' ORDER BY A.APPCODE,A.CREATED_DATE';
    END IF;

    DBMS_OUTPUT.PUT_LINE(V_SQL);


    V_TOTAL_COUNT := 'SELECT COUNT(*) FROM (' || V_SQL || ')';
    EXECUTE IMMEDIATE V_TOTAL_COUNT INTO V_TOTAL_COUNT;

    V_FROM := P_FROM ;
    V_TO := P_TO;

    IF P_FROM = '0' AND P_TO = '0' THEN
        V_FROM := '1' ;
        V_TO := V_TOTAL_COUNT;
    END IF;

    V_SQL := 'SELECT * FROM ( SELECT ROWNUM STT, V.* FROM( ' || V_SQL || ') V ) A WHERE STT BETWEEN ' || V_FROM || ' AND ' || V_TO;
    OPEN P_CURSOR FOR V_SQL;

    PKG_LOG.LOGMSGALL(V_SQL);


    P_TOTAL_RECORD := V_TOTAL_COUNT;

EXCEPTION
WHEN OTHERS THEN
    RAISE;
END;

-- dangtq
PROCEDURE proc_update_status
(
    p_id IN NUMBER,
    p_status IN NUMBER,
    p_notes IN VARCHAR2,
    p_modify_by IN VARCHAR2,
    p_modify_date IN DATE,
    p_return OUT NUMBER
)
IS
BEGIN

    UPDATE APPLICATION_HEADER
    SET status = p_status,
        notes = p_notes,
        modify_by = p_modify_by,
        modify_date = p_modify_date
    WHERE id = p_id;

    p_return := 0;

COMMIT;
EXCEPTION
WHEN OTHERS THEN
    RAISE;
END;

PROCEDURE PROC_APP_HEADER_INSERT
(
    P_APPCODE IN APPLICATION_HEADER.APPCODE % TYPE,
    P_MASTER_NAME IN APPLICATION_HEADER.MASTER_NAME % TYPE,
    P_MASTER_ADDRESS IN APPLICATION_HEADER.MASTER_ADDRESS % TYPE,
    P_MASTER_PHONE IN APPLICATION_HEADER.MASTER_PHONE % TYPE,
    P_MASTER_FAX IN VARCHAR ,
    P_MASTER_EMAIL IN VARCHAR ,
    P_REP_MASTER_TYPE IN APPLICATION_HEADER.REP_MASTER_TYPE % TYPE,
    P_REP_MASTER_NAME IN APPLICATION_HEADER.REP_MASTER_NAME % TYPE,
    P_REP_MASTER_ADDRESS IN APPLICATION_HEADER.REP_MASTER_ADDRESS % TYPE,
    P_REP_MASTER_PHONE IN APPLICATION_HEADER.REP_MASTER_PHONE % TYPE,
    P_REP_MASTER_FAX IN APPLICATION_HEADER.REP_MASTER_FAX % TYPE,
    P_REP_MASTER_EMAIL IN APPLICATION_HEADER.REP_MASTER_EMAIL % TYPE,
    P_SEND_DATE IN APPLICATION_HEADER.SEND_DATE % TYPE,
    P_STATUS IN APPLICATION_HEADER.STATUS % TYPE,
    P_CREATED_BY IN APPLICATION_HEADER.CREATED_BY % TYPE,
    P_CREATED_DATE IN APPLICATION_HEADER.CREATED_DATE % TYPE,
    P_LANGUAGUE_CODE IN APPLICATION_HEADER.LANGUAGUE_CODE % TYPE  ,
    P_ADDRESS IN VARCHAR2  ,
    P_DATENO IN VARCHAR2 ,
    P_MONTHS IN VARCHAR2 ,
    P_YEARS IN VARCHAR2 ,
    p_client_reference IN VARCHAR2,
    p_case_name IN VARCHAR2,
    P_RETURN OUT NUMBER
)
IS
    V_ID NUMBER;

    V_ID_GENCODE NUMBER;
    V_GENCODE VARCHAR2(50);
    PLOG_RETURN  VARCHAR2(2000);
BEGIN

    SELECT SEQ_APPLICATION_HEADER.NEXTVAL INTO V_ID FROM DUAL;

    SELECT SEQ_GENCODE.NEXTVAL INTO V_ID_GENCODE FROM DUAL;

    V_GENCODE := P_APPCODE || to_char(SYSDATE,'yyyyMMdd') || V_ID_GENCODE;

    --TRA RA ID DE INSERT CAC BANG LIEN QUAN
    P_RETURN:=V_ID;
    INSERT INTO APPLICATION_HEADER
    (
        ID, APPCODE, MASTER_NAME, MASTER_ADDRESS, MASTER_PHONE,
        REP_MASTER_TYPE, REP_MASTER_NAME, REP_MASTER_ADDRESS, REP_MASTER_PHONE, REP_MASTER_FAX,
        REP_MASTER_EMAIL, SEND_DATE, STATUS, DELETED, CREATED_BY, CREATED_DATE ,MASTER_FAX  ,MASTER_EMAIL ,
        LANGUAGUE_CODE ,ADDRESS ,DATENO,MONTHS,YEARS,GENCODE,client_reference,case_name
    )
    VALUES
    (
        V_ID, P_APPCODE, P_MASTER_NAME, P_MASTER_ADDRESS, P_MASTER_PHONE,
        P_REP_MASTER_TYPE, P_REP_MASTER_NAME, P_REP_MASTER_ADDRESS, P_REP_MASTER_PHONE, P_REP_MASTER_FAX, P_REP_MASTER_EMAIL,
        P_SEND_DATE, P_STATUS,  0, P_CREATED_BY, P_CREATED_DATE,P_MASTER_FAX  ,P_MASTER_EMAIL ,
        P_LANGUAGUE_CODE,P_ADDRESS ,P_DATENO,P_MONTHS,P_YEARS,V_GENCODE,p_client_reference,p_case_name

    );
    --COMMIT;
EXCEPTION WHEN OTHERS THEN
    P_RETURN:=PKG_COMMON.ERROR ;
    PLOG_RETURN := SUBSTR(SQLCODE,1,500) || SUBSTR(SQLERRM,1,500);
    pkg_log.log_error(PLOG_RETURN,'PROC_APP_HEADER_INSERT');
    RAISE;
END;

PROCEDURE PROC_APP_HEADER_UPDATE
(
    P_ID IN NUMBER ,
    P_APPCODE IN APPLICATION_HEADER.APPCODE % TYPE,
    P_MASTER_NAME IN APPLICATION_HEADER.MASTER_NAME % TYPE,
    P_MASTER_ADDRESS IN APPLICATION_HEADER.MASTER_ADDRESS % TYPE,
    P_MASTER_PHONE IN APPLICATION_HEADER.MASTER_PHONE % TYPE,
    P_MASTER_FAX IN VARCHAR ,
    P_MASTER_EMAIL IN VARCHAR ,
    P_REP_MASTER_TYPE IN APPLICATION_HEADER.REP_MASTER_TYPE % TYPE,
    P_REP_MASTER_NAME IN APPLICATION_HEADER.REP_MASTER_NAME % TYPE,
    P_REP_MASTER_ADDRESS IN APPLICATION_HEADER.REP_MASTER_ADDRESS % TYPE,
    P_REP_MASTER_PHONE IN APPLICATION_HEADER.REP_MASTER_PHONE % TYPE,
    P_REP_MASTER_FAX IN APPLICATION_HEADER.REP_MASTER_FAX % TYPE,
    P_REP_MASTER_EMAIL IN APPLICATION_HEADER.REP_MASTER_EMAIL % TYPE,
    P_SEND_DATE IN APPLICATION_HEADER.SEND_DATE % TYPE,
    P_STATUS IN APPLICATION_HEADER.STATUS % TYPE,
    P_MODIFY_BY IN APPLICATION_HEADER.modify_by % TYPE,
    P_MODIFY_DATE IN APPLICATION_HEADER.modify_date % TYPE,
    P_LANGUAGUE_CODE IN APPLICATION_HEADER.LANGUAGUE_CODE % TYPE  ,
    P_ADDRESS IN VARCHAR2  ,
    P_DATENO IN VARCHAR2 ,
    P_MONTHS IN VARCHAR2 ,
    P_YEARS IN VARCHAR2 ,
    p_client_reference IN VARCHAR2,
    p_case_name IN VARCHAR2,
    P_RETURN OUT NUMBER
)
IS
BEGIN
     P_RETURN:= 0 ;

    UPDATE APPLICATION_HEADER SET
        --APPCODE = P_APPCODE, KHONG DUOC SUA
        MASTER_NAME = P_MASTER_NAME,
        MASTER_ADDRESS = P_MASTER_ADDRESS,
        MASTER_PHONE = P_MASTER_PHONE,
        REP_MASTER_TYPE = P_REP_MASTER_TYPE,
        REP_MASTER_NAME = P_REP_MASTER_NAME,
        REP_MASTER_ADDRESS = P_REP_MASTER_ADDRESS,
        REP_MASTER_PHONE = P_REP_MASTER_PHONE,
        REP_MASTER_FAX = P_REP_MASTER_FAX,
        REP_MASTER_EMAIL = P_REP_MASTER_EMAIL,
        --SEND_DATE = P_SEND_DATE,
        STATUS = P_STATUS,
        MODIFY_BY = P_MODIFY_BY,
        MODIFY_DATE = P_MODIFY_DATE ,
        MASTER_EMAIL=P_MASTER_EMAIL ,
        MASTER_FAX= P_MASTER_FAX ,
        ADDRESS = P_ADDRESS , DATENO =P_DATENO ,MONTHS =P_MONTHS ,YEARS =P_YEARS,
        client_reference = p_client_reference,
        case_name = p_case_name

    WHERE ID = P_ID AND LANGUAGUE_CODE = P_LANGUAGUE_CODE;

EXCEPTION WHEN OTHERS THEN
    P_RETURN:=PKG_COMMON.ERROR ;
    ROLLBACK ;
    RAISE;
END;

PROCEDURE PROC_APP_HEADER_DELETED
(
    P_ID IN NUMBER ,
    P_LANGUAGUE_CODE IN VARCHAR2 ,
    P_RETURN OUT NUMBER
)
IS
BEGIN
    P_RETURN:= PKG_COMMON.SUCESS ;

    --NEU XOA TIENG VIET THI UPDATE CA TIENG ANH
    IF(P_LANGUAGUE_CODE = PKG_COMMON.VI_VN)THEN
        UPDATE APPLICATION_HEADER SET  DELETED =PKG_COMMON.DELETED WHERE  ID = P_ID ;
    ELSE
        UPDATE APPLICATION_HEADER SET  DELETED =PKG_COMMON.DELETED WHERE  ID = P_ID  AND LANGUAGUE_CODE = P_LANGUAGUE_CODE;
    END IF;

     RETURN ;
     -- CON NEU XOA TIENG ANH THI CHI UPDATE TIENG ANH THOI
EXCEPTION WHEN OTHERS THEN
    P_RETURN:=PKG_COMMON.ERROR ;
    ROLLBACK ;
    RAISE;
END ;

PROCEDURE proc_getByAppNo
(
    p_appNo IN VARCHAR2,
    p_user_name IN VARCHAR2,
    p_languague_code IN VARCHAR2 ,
    p_cursor OUT pkg_common.t_cursor
)
IS
BEGIN
    OPEN p_cursor FOR SELECT * FROM view_app_header WHERE app_no = p_appNo;
EXCEPTION
WHEN OTHERS THEN
    RAISE;
END ;

END;
/


-- End of DDL Script for Package Body LEGALTECH.PKG_APP_HEADER

