ALTER TABLE S_USERS 
 ADD (
  CONTACT_PERSON VARCHAR2 (10 CHAR)
 )
/
COMMENT ON COLUMN S_USERS.CONTACT_PERSON IS 'Mr/Ms...'
/

ALTER TABLE APPLICATION_HEADER 
 ADD (
  CLIENT_REFERENCE VARCHAR2 (200 CHAR),
  CASE_NAME VARCHAR2 (200 CHAR)
 )
/
COMMENT ON COLUMN APPLICATION_HEADER.CLIENT_REFERENCE IS 'MA HO SO CUA KHACH HANG TU NHAP THEO DON'
/
COMMENT ON COLUMN APPLICATION_HEADER.CASE_NAME IS 'CASE NAME KHACH HANG TU NHAP'
/

ALTER TABLE SYS_APPLICATION 
 ADD (
  APPLICATION_TYPE NUMBER (1),
  OBJECT_TYPE NUMBER (1)
 )
/
COMMENT ON COLUMN SYS_APPLICATION.APPLICATION_TYPE IS 'LOAI DON 1: Dang ky,2: khieu nai, 3: phan doi, 4: chuyen nhuong'
/
COMMENT ON COLUMN SYS_APPLICATION.OBJECT_TYPE IS 'DOI TUONG: 1: TRADE MARK, 2: PATENT,3: COPY_RIGHT'
/