PROCEDURE PROC_APP_HEADER_INSERT
(
    P_APPCODE IN APPLICATION_HEADER.APPCODE % TYPE,
    P_MASTER_NAME IN APPLICATION_HEADER.MASTER_NAME % TYPE,
    P_MASTER_ADDRESS IN APPLICATION_HEADER.MASTER_ADDRESS % TYPE,
    P_MASTER_PHONE IN APPLICATION_HEADER.MASTER_PHONE % TYPE,
    P_MASTER_FAX IN VARCHAR ,
    P_MASTER_EMAIL IN VARCHAR ,
    P_REP_MASTER_TYPE IN APPLICATION_HEADER.REP_MASTER_TYPE % TYPE,
    P_REP_MASTER_NAME IN APPLICATION_HEADER.REP_MASTER_NAME % TYPE,
    P_REP_MASTER_ADDRESS IN APPLICATION_HEADER.REP_MASTER_ADDRESS % TYPE,
    P_REP_MASTER_PHONE IN APPLICATION_HEADER.REP_MASTER_PHONE % TYPE,
    P_REP_MASTER_FAX IN APPLICATION_HEADER.REP_MASTER_FAX % TYPE,
    P_REP_MASTER_EMAIL IN APPLICATION_HEADER.REP_MASTER_EMAIL % TYPE,
    P_SEND_DATE IN APPLICATION_HEADER.SEND_DATE % TYPE,
    P_STATUS IN APPLICATION_HEADER.STATUS % TYPE,
    P_CREATED_BY IN APPLICATION_HEADER.CREATED_BY % TYPE,
    P_CREATED_DATE IN APPLICATION_HEADER.CREATED_DATE % TYPE,
    P_LANGUAGUE_CODE IN APPLICATION_HEADER.LANGUAGUE_CODE % TYPE  ,
    P_ADDRESS IN VARCHAR2  ,
    P_DATENO IN VARCHAR2 ,
    P_MONTHS IN VARCHAR2 ,
    P_YEARS IN VARCHAR2 ,
    P_RETURN OUT NUMBER
)
IS
    V_ID NUMBER;

    V_ID_GENCODE NUMBER;
    V_GENCODE VARCHAR2(30);
BEGIN

    SELECT SEQ_APPLICATION_HEADER.NEXTVAL INTO V_ID FROM DUAL;

    SELECT SEQ_GENCODE.NEXTVAL INTO V_ID_GENCODE FROM DUAL;

    V_GENCODE := P_APPCODE || to_char(SYSDATE,'yyyyMMdd') || V_ID_GENCODE;

    --TRA RA ID DE INSERT CAC BANG LIEN QUAN
    P_RETURN:=V_ID;
    INSERT INTO APPLICATION_HEADER
    (
        ID, APPCODE, MASTER_NAME, MASTER_ADDRESS, MASTER_PHONE,
        REP_MASTER_TYPE, REP_MASTER_NAME, REP_MASTER_ADDRESS, REP_MASTER_PHONE, REP_MASTER_FAX,
        REP_MASTER_EMAIL, SEND_DATE, STATUS, DELETED, CREATED_BY, CREATED_DATE ,MASTER_FAX  ,MASTER_EMAIL ,
        LANGUAGUE_CODE ,ADDRESS ,DATENO,MONTHS,YEARS,GENCODE
    )
    VALUES
    (
        V_ID, P_APPCODE, P_MASTER_NAME, P_MASTER_ADDRESS, P_MASTER_PHONE,
        P_REP_MASTER_TYPE, P_REP_MASTER_NAME, P_REP_MASTER_ADDRESS, P_REP_MASTER_PHONE, P_REP_MASTER_FAX, P_REP_MASTER_EMAIL,
        P_SEND_DATE, P_STATUS,  0, P_CREATED_BY, P_CREATED_DATE,P_MASTER_FAX  ,P_MASTER_EMAIL ,
        P_LANGUAGUE_CODE,P_ADDRESS ,P_DATENO,P_MONTHS,P_YEARS,V_GENCODE

    );

--COMMIT;
EXCEPTION WHEN OTHERS THEN
    P_RETURN:=PKG_COMMON.ERROR ;
    RAISE;
END;