PROCEDURE PROC_APP_DOCUMENT_DEL_BY_APP
(
    P_LANGUAGE_CODE IN APP_DOCUMENT.LANGUAGE_CODE % TYPE,
    P_APP_HEADER_ID IN APP_DOCUMENT.APP_HEADER_ID % TYPE,
    P_RETURN OUT NUMBER
)
IS
BEGIN
     P_RETURN:= PKG_COMMON.SUCESS ;
     DELETE APP_DOCUMENT WHERE APP_HEADER_ID = P_APP_HEADER_ID AND LANGUAGE_CODE =P_LANGUAGE_CODE ;
EXCEPTION
WHEN OTHERS THEN
    RAISE;
    P_RETURN:= PKG_COMMON.ERROR ;
END;