-- Start of DDL Script for Package Body LEGALTECH.PKG_COMMON
-- Generated 3-Jun-2018 22:09:37 from LEGALTECH@LOCALHOST

CREATE OR REPLACE 
PACKAGE pkg_common
  IS

TYPE t_cursor IS ref CURSOR ;

-- trang thai nguoi dung
-- luu trong allcode voi cdname='USER_STATUS'
USER_STATUS_STOPPED CONSTANT NUMBER(1) := 0;
USER_STATUS_ACTIVE CONSTANT NUMBER(1) := 1;

USER_TYPE_ADMIN CONSTANT NUMBER(1) := 1;
USER_TYPE_LAWER CONSTANT NUMBER(1) := 2;
USER_TYPE_CUSTOMER CONSTANT NUMBER(1) := 3;

-- loai chuc nang
-- luu trong allcode voi cdname='FUNCTION_TYPE'
FN_NO_REQUIRED_LOGIN CONSTANT NUMBER(1) := 0;
FN_MENU CONSTANT NUMBER(1) := 1;
FN_INNER CONSTANT NUMBER(1) := 2;
FN_IMMEDIATE_SELF CONSTANT NUMBER(1) := 3;

-- Loai gia su dung luu trong allcode voi cdname='UNIT_PRICE_TYPE'
UNIT_PRICE_TYPE_M CONSTANT CHAR(1) := 'M';
UNIT_PRICE_TYPE_G CONSTANT CHAR(1) := 'G';

-- Gioi tinh luu trong allcode voi cdname='SEX_TYPE'
MALE CONSTANT CHAR(1) := 'M';
FEMALE CONSTANT CHAR(1) := 'F';

--MA LOI TRA VE
ERROR NUMBER :=-99 ;
SUCESS NUMBER :=0 ;

--NGON NGU HIEN THI
VI_VN VARCHAR2(5) :='VI_VN' ;
EN_US VARCHAR2(5) :='EN_US' ;

DELETED NUMBER :=1 ;
END;
/


CREATE OR REPLACE 
PACKAGE BODY pkg_common
IS


END;
/


-- End of DDL Script for Package Body LEGALTECH.PKG_COMMON

