ALTER TABLE APP_DETAIL_PLB01_SDD 
 ADD (
  NUMBER_PIC NUMBER,
  NUMBER_PAGE NUMBER
 )
/
COMMENT ON COLUMN APP_DETAIL_PLB01_SDD.NUMBER_PIC IS 'SO HINH'
/
COMMENT ON COLUMN APP_DETAIL_PLB01_SDD.NUMBER_PAGE IS 'SO TRANG'
/