ALTER TABLE APPLICATION_HEADER 
 ADD (
  STATUS_DATE DATE
 )
/
COMMENT ON COLUMN APPLICATION_HEADER.STATUS_DATE IS 'NGAY CAP NHAT TRANG THAI GAN NHAT'
/

UPDATE APPLICATION_HEADER SET STATUS_DATE = modify_date;
/
COMMIT;
/
ALTER TABLE APPLICATION_HEADER 
 ADD (
  URL_COPY_FILING VARCHAR2 (200 CHAR)
 )
/
COMMENT ON COLUMN APPLICATION_HEADER.URL_COPY_FILING IS 'DUONG DAN FILE COPY NOP DON'
/