
PROCEDURE PROC_APP_TM06DKQT_GET_BY_ID
(
    P_APP_HEADER_ID IN VARCHAR2,
    P_LANGUAGE IN VARCHAR2,
    P_STATUS IN NUMBER ,
    P_CURSOR OUT PKG_COMMON.T_CURSOR  ,
    P_C_DOC OUT  PKG_COMMON.T_CURSOR ,
    P_C_CLASS_DETAIL OUT  PKG_COMMON.T_CURSOR
)
IS
BEGIN

    OPEN  P_CURSOR FOR SELECT A.* , B.*, C.APPNO AS REF_APPNO_TEXT,
    CT1.NAME AS COUNTRY_ID01_TEXT,
    CT2.NAME AS COUNTRY_ID02_TEXT,
    CT3.NAME AS COUNTRY_ID03_TEXT,
    CT4.NAME AS COUNTRY_ID04_TEXT,
    CT5.NAME AS COUNTRY_ID05_TEXT,
    CT6.NAME AS COUNTRY_ID06_TEXT,
    CT7.NAME AS COUNTRY_ID07_TEXT,
    CT8.NAME AS COUNTRY_ID08_TEXT
     FROM APPLICATION_HEADER A LEFT JOIN APP_DETAIL_TM06DKQT B ON A.ID = B.APP_HEADER_ID
     LEFT JOIN APP_DETAIL_04NH C ON B.REF_APPNO = C.APP_HEADER_ID
     LEFT JOIN COUNTRY CT1 ON B.COUNTRY_ID01 = CT1.COUNTRY_ID
     LEFT JOIN COUNTRY CT2 ON B.COUNTRY_ID02 = CT2.COUNTRY_ID
     LEFT JOIN COUNTRY CT3 ON B.COUNTRY_ID03 = CT3.COUNTRY_ID
     LEFT JOIN COUNTRY CT4 ON B.COUNTRY_ID04 = CT4.COUNTRY_ID
     LEFT JOIN COUNTRY CT5 ON B.COUNTRY_ID05 = CT5.COUNTRY_ID
     LEFT JOIN COUNTRY CT6 ON B.COUNTRY_ID06 = CT6.COUNTRY_ID
     LEFT JOIN COUNTRY CT7 ON B.COUNTRY_ID07 = CT7.COUNTRY_ID
     LEFT JOIN COUNTRY CT8 ON B.COUNTRY_ID08 = CT8.COUNTRY_ID

           WHERE   A.LANGUAGUE_CODE =P_LANGUAGE   AND  B.APP_HEADER_ID = P_APP_HEADER_ID  AND STATUS = P_STATUS AND
            DELETED =0 AND B.LANGUAGE = P_LANGUAGE AND C.LANGUAGE_CODE = P_LANGUAGE ;
    --LAY DANH SACH CAC TAI LIEU DINH KEM
    OPEN  P_C_DOC FOR SELECT  * FROM APP_DOCUMENT A  WHERE  app_header_id = P_APP_HEADER_ID AND  language_code = P_LANGUAGE ;
    --LAY DANH SACH CAC TAI LIEU KHAC DINH KEM
    OPEN  P_C_CLASS_DETAIL FOR SELECT  * FROM APP_CLASS_DETAIL A  WHERE  app_header_id = P_APP_HEADER_ID AND  language_code = P_LANGUAGE ;

EXCEPTION WHEN OTHERS THEN
    RAISE;
END  ;