INSERT INTO WIKI_CATALOGUES 
VALUES(99,'LUẬT TÀI CHÍNH',0,NULL,NULL,NULL,NULL,0,NULL,0);
INSERT INTO WIKI_CATALOGUES 
VALUES(100,'LUẬT HÌNH SỰ',0,NULL,NULL,NULL,NULL,0,NULL,0);
INSERT INTO WIKI_CATALOGUES 
VALUES(101,'LUẬT NHẬP KHẨU HÀNG HÓA',1,NULL,NULL,NULL,NULL,0,NULL,99);
INSERT INTO WIKI_CATALOGUES 
VALUES(102,'LUẬT XUẤT KHẨU HÀNG HÓA',1,NULL,NULL,NULL,NULL,0,NULL,99);
INSERT INTO WIKI_CATALOGUES 
VALUES(103,'LUẬT XỬ KÝ TRANH CHẤP TÀI SẢN',1,NULL,NULL,NULL,NULL,0,NULL,100);