CREATE TABLE WIKI_CATALOGUES
    (ID                             NUMBER(20,0),
    NAME                           VARCHAR2(200 CHAR),
    CATA_LEVEL                     NUMBER(2,0) DEFAULT 0,
    CREATED_BY                     VARCHAR2(50 CHAR),
    CREATED_DATE                   DATE,
    MODIFIED_BY                    VARCHAR2(50 CHAR),
    MODIFIED_DATE                  DATE,
    DELETED                        NUMBER(1,0) DEFAULT 0)
  PCTFREE     10
  INITRANS    1
  MAXTRANS    255
  TABLESPACE  USERS
  NOCACHE
  MONITORING
  NOPARALLEL
  LOGGING
/



CREATE TABLE WIKI_DOCS
    (ID                             NUMBER(20,0),
    TITLE                          VARCHAR2(4000 CHAR),
    CONTENT                        CLOB,
    VIEW_NUMBER                    NUMBER(20,0) DEFAULT 0,
    CREATED_BY                     VARCHAR2(50 CHAR),
    CREATED_DATE                   DATE,
    MODIFIED_BY                    VARCHAR2(50 CHAR),
    MODIFIED_DATE                  DATE,
    DELETED                        NUMBER(1,0) DEFAULT 0,
    LANGUAGE_CODE                  VARCHAR2(5 CHAR),
    HASHTAG                        VARCHAR2(1000 CHAR))
  PCTFREE     10
  INITRANS    1
  MAXTRANS    255
  TABLESPACE  USERS
  NOCACHE
  MONITORING
  LOB ("CONTENT") STORE AS SYS_LOB0000092411C00003$$
  (
  TABLESPACE  USERS
   NOCACHE LOGGING
   CHUNK 8192
  )
  NOPARALLEL
  LOGGING
/

 


CREATE TABLE WIKI_DOCS_CATALOGUES
    (ID                             NUMBER(20,0),
    DOC_ID                         NUMBER(20,0),
    CATALOGUE_ID                   NUMBER(20,0))
  PCTFREE     10
  INITRANS    1
  MAXTRANS    255
  TABLESPACE  USERS
  NOCACHE
  MONITORING
  NOPARALLEL
  LOGGING
/




COMMENT ON COLUMN WIKI_DOCS_CATALOGUES.CATALOGUE_ID IS 'ID DANH MUC BAI VIET'
/
COMMENT ON COLUMN WIKI_DOCS_CATALOGUES.DOC_ID IS 'ID BAI VIET'
/
CREATE TABLE WIKI_HASHTAG_DOCS
    (ID                             NUMBER(20,0),
    WIKI_DOC_ID                    NUMBER(20,0),
    HASHTAG_ID                     NUMBER(20,0),
    HASHTAG_NAME                   VARCHAR2(200 CHAR),
    DELETED                        NUMBER(1,0) DEFAULT 0,
    DOC_TITLE                      VARCHAR2(200 CHAR))
  PCTFREE     10
  INITRANS    1
  MAXTRANS    255
  TABLESPACE  USERS
  NOCACHE
  MONITORING
  NOPARALLEL
  LOGGING
/




COMMENT ON COLUMN WIKI_HASHTAG_DOCS.DOC_TITLE IS 'TIEU DE CUA BAI VIET'
/
COMMENT ON COLUMN WIKI_HASHTAG_DOCS.HASHTAG_ID IS 'ID CUA HASHTAG'
/
COMMENT ON COLUMN WIKI_HASHTAG_DOCS.HASHTAG_NAME IS 'TEN CUA HASHTAG'
/
COMMENT ON COLUMN WIKI_HASHTAG_DOCS.WIKI_DOC_ID IS 'ID CUA BAI VIET'
/
CREATE TABLE WIKI_HASHTAG_NAMES
    (ID                             NUMBER(20,0),
    NAME                           VARCHAR2(200 CHAR),
    NUMBER_TAG                     NUMBER(20,0),
    CREATED_BY                     VARCHAR2(50 CHAR),
    CREATED_DATE                   DATE,
    MODIFIED_BY                    VARCHAR2(50 CHAR),
    MODIFIED_DATE                  DATE,
    DELETED                        NUMBER(1,0) DEFAULT 0)
  PCTFREE     10
  INITRANS    1
  MAXTRANS    255
  TABLESPACE  USERS
  NOCACHE
  MONITORING
  NOPARALLEL
  LOGGING
/




COMMENT ON COLUMN WIKI_HASHTAG_NAMES.NAME IS 'TEN HIEN THI'
/
COMMENT ON COLUMN WIKI_HASHTAG_NAMES.NUMBER_TAG IS 'SO LAN DUOC TAG'
/
