-- Start of DDL Script for Package LEGALCODE.PKG_A03
-- Generated 16-Jun-2019 13:56:26 from LEGALCODE@LEGALONLINE
CREATE SEQUENCE seq_app_detail_a03
  INCREMENT BY 1
  START WITH 6
  MINVALUE 1
  MAXVALUE 999999999999999
  NOCYCLE
  NOORDER
  CACHE 5
/

CREATE TABLE app_detail_a03_industry_design
    (id                             NUMBER(20,0),
    case_code                      VARCHAR2(50 BYTE),
    app_header_id                  NUMBER(20,0),
    language_code                  VARCHAR2(10 BYTE),
    industry_design_name           VARCHAR2(200 BYTE),
    refappno                       VARCHAR2(50 BYTE),
    app_sentdate                   DATE,
    kqtd_type                      NUMBER(1,0),
    kqtd_value                     NUMBER(1,0),
    phanloai_type                  NUMBER(1,0))
  SEGMENT CREATION IMMEDIATE
  PCTFREE     10
  INITRANS    1
  MAXTRANS    255
  TABLESPACE  users
  STORAGE   (
    INITIAL     65536
    NEXT        1048576
    MINEXTENTS  1
    MAXEXTENTS  2147483645
  )
  NOCACHE
  MONITORING
  NOPARALLEL
  LOGGING
/





-- Comments for APP_DETAIL_A03_INDUSTRY_DESIGN

COMMENT ON COLUMN app_detail_a03_industry_design.app_sentdate IS 'ngay nop don'
/
COMMENT ON COLUMN app_detail_a03_industry_design.industry_design_name IS 'ten kieu dang cong nghiep'
/
COMMENT ON COLUMN app_detail_a03_industry_design.kqtd_type IS 'ket qua tham dinh 1: da co kq 2: chua co ket qua'
/
COMMENT ON COLUMN app_detail_a03_industry_design.kqtd_value IS 'gia tri ket qua tham dinh'
/
COMMENT ON COLUMN app_detail_a03_industry_design.phanloai_type IS '1: tu phan loai 2: cuc shtt phan loai'
/
COMMENT ON COLUMN app_detail_a03_industry_design.refappno IS 'so don goc'
/

CREATE OR REPLACE 
PACKAGE pkg_a03
  IS


PROCEDURE PROC_GETBY_ID
(
    P_APP_HEADER_ID IN NUMBER,
    P_LANGUAGE_CODE IN APP_DETAIL_A03_INDUSTRY_DESIGN.LANGUAGE_CODE % TYPE,
    P_CURSOR OUT PKG_COMMON.T_CURSOR,
    P_CURSORHEADER OUT PKG_COMMON.T_CURSOR,
    P_CURSOR_DOC OUT PKG_COMMON.T_CURSOR,
    P_CURSOR_FEE OUT PKG_COMMON.T_CURSOR,
    P_CURSOR_OTHER_MASTER OUT PKG_COMMON.T_CURSOR,
    P_CURSOR_AUTHOR OUT PKG_COMMON.T_CURSOR,
    P_CURSOR_CLASS OUT PKG_COMMON.T_CURSOR,
    P_CURSOR_OTHER_DOC OUT PKG_COMMON.T_CURSOR,
    P_CURSOR_UU_TIEN OUT PKG_COMMON.T_CURSOR
);


PROCEDURE PROC_APP_DETAIL_A03_INSERT
(
    P_RETURN OUT NUMBER,
    P_ID IN APP_DETAIL_A03_INDUSTRY_DESIGN.ID % TYPE,
    P_CASE_CODE IN APP_DETAIL_A03_INDUSTRY_DESIGN.CASE_CODE % TYPE,
    P_APP_HEADER_ID IN APP_DETAIL_A03_INDUSTRY_DESIGN.APP_HEADER_ID % TYPE,
    P_LANGUAGE_CODE IN APP_DETAIL_A03_INDUSTRY_DESIGN.LANGUAGE_CODE % TYPE,
    P_REFAPPNO IN APP_DETAIL_A03_INDUSTRY_DESIGN.REFAPPNO % TYPE,
    P_APP_SENTDATE IN APP_DETAIL_A03_INDUSTRY_DESIGN.APP_SENTDATE % TYPE,
    P_INDUSTRY_DESIGN_NAME IN APP_DETAIL_A03_INDUSTRY_DESIGN.INDUSTRY_DESIGN_NAME % TYPE,
    P_KQTD_TYPE IN APP_DETAIL_A03_INDUSTRY_DESIGN.KQTD_TYPE % TYPE,
    P_KQTD_VALUE IN APP_DETAIL_A03_INDUSTRY_DESIGN.KQTD_VALUE % TYPE,
    P_PHANLOAI_TYPE IN APP_DETAIL_A03_INDUSTRY_DESIGN.PHANLOAI_TYPE % TYPE
);

PROCEDURE PROC_APP_DETAIL_A03_UPDATE
(
    P_RETURN OUT NUMBER,
    P_ID IN APP_DETAIL_A03_INDUSTRY_DESIGN.ID % TYPE,
    P_CASE_CODE IN APP_DETAIL_A03_INDUSTRY_DESIGN.CASE_CODE % TYPE,
    P_APP_HEADER_ID IN APP_DETAIL_A03_INDUSTRY_DESIGN.APP_HEADER_ID % TYPE,
    P_LANGUAGE_CODE IN APP_DETAIL_A03_INDUSTRY_DESIGN.LANGUAGE_CODE % TYPE,
    P_REFAPPNO IN APP_DETAIL_A03_INDUSTRY_DESIGN.REFAPPNO % TYPE,
    P_APP_SENTDATE IN APP_DETAIL_A03_INDUSTRY_DESIGN.APP_SENTDATE % TYPE,
    P_INDUSTRY_DESIGN_NAME IN APP_DETAIL_A03_INDUSTRY_DESIGN.INDUSTRY_DESIGN_NAME % TYPE,
    P_KQTD_TYPE IN APP_DETAIL_A03_INDUSTRY_DESIGN.KQTD_TYPE % TYPE,
    P_KQTD_VALUE IN APP_DETAIL_A03_INDUSTRY_DESIGN.KQTD_VALUE % TYPE,
    P_PHANLOAI_TYPE IN APP_DETAIL_A03_INDUSTRY_DESIGN.PHANLOAI_TYPE % TYPE
);

PROCEDURE PROC_APP_DETAIL_A03_DELETE
(
    P_APP_HEADER_ID IN APP_DETAIL_PLB01_SDD.APP_HEADER_ID % TYPE,
    P_APPCODE IN APP_DETAIL_PLB01_SDD.APPCODE % TYPE,
    P_LANGUAGE_CODE IN APP_DETAIL_PLB01_SDD.LANGUAGE_CODE % TYPE,
    P_RETURN OUT NUMBER
);

END;
/



-- End of DDL Script for Package LEGALCODE.PKG_A03

