-- Start of DDL Script for Table LEGALTECH.APP_DETAIL_A02
-- Generated 18-Aug-2019 21:07:30 from LEGALTECH@LEGALONLINE

CREATE TABLE app_detail_a02
    (id                             NUMBER(20,0),
    case_code                      VARCHAR2(50 BYTE),
    app_header_id                  NUMBER(20,0),
    language_code                  VARCHAR2(10 BYTE),
    tenthietke                     VARCHAR2(200 CHAR),
    ngaytaothietke                 DATE,
    khaithactm                     VARCHAR2(100 CHAR),
    khaithactm_tainuoc             VARCHAR2(100 CHAR),
    khaithactm_ngay                DATE,
    chucnang                       VARCHAR2(10 CHAR),
    chucnang_other                 VARCHAR2(100 CHAR),
    cautruc                        VARCHAR2(10 CHAR),
    cautruc_other                  VARCHAR2(100 CHAR),
    congnghe                       VARCHAR2(10 CHAR),
    congnghe_other                 VARCHAR2(100 CHAR),
    motatomtat                     VARCHAR2(200 CHAR),
    soanh                          NUMBER(20,0))
  SEGMENT CREATION IMMEDIATE
  PCTFREE     10
  INITRANS    1
  MAXTRANS    255
  TABLESPACE  users
  STORAGE   (
    INITIAL     65536
    NEXT        1048576
    MINEXTENTS  1
    MAXEXTENTS  2147483645
  )
  NOCACHE
  MONITORING
  NOPARALLEL
  LOGGING
/



-- Start of DDL Script for Package LEGALTECH.PKG_A02
-- Generated 18-Aug-2019 21:07:39 from LEGALTECH@LEGALONLINE

CREATE OR REPLACE 
PACKAGE pkg_a02
  IS

PROCEDURE PROC_GETBY_ID
(
    P_APP_HEADER_ID IN NUMBER,
    P_LANGUAGE_CODE IN APP_DETAIL_A03.LANGUAGE_CODE % TYPE,
    P_CURSOR OUT PKG_COMMON.T_CURSOR,
    P_CURSORHEADER OUT PKG_COMMON.T_CURSOR,
    P_CURSOR_DOC OUT PKG_COMMON.T_CURSOR,
    P_CURSOR_FEE OUT PKG_COMMON.T_CURSOR,
    P_CURSOR_OTHER_MASTER OUT PKG_COMMON.T_CURSOR,
    P_CURSOR_AUTHOR OUT PKG_COMMON.T_CURSOR,
    P_CURSOR_OTHER_DOC OUT PKG_COMMON.T_CURSOR,
    P_CURSOR_DOC_DESIGN OUT PKG_COMMON.T_CURSOR
);

PROCEDURE PROC_APP_DETAIL_A02_INSERT
(
    P_RETURN OUT NUMBER,
    P_CASE_CODE IN APP_DETAIL_A03.CASE_CODE % TYPE,
    P_APP_HEADER_ID IN APP_DETAIL_A03.APP_HEADER_ID % TYPE,
    P_LANGUAGE_CODE IN APP_DETAIL_A03.LANGUAGE_CODE % TYPE,
    P_TENTHIETKE IN VARCHAR2,
    P_NGAYTAOTHIETKE IN DATE,
    P_KHAITHACTM IN VARCHAR2,
    P_KHAITHACTM_TAINUOC IN VARCHAR,
    P_KHAITHACTM_NGAY IN DATE,
    P_CHUCNANG IN VARCHAR2,
    P_CHUCNANG_OTHER IN VARCHAR2,
    P_CAUTRUC IN VARCHAR2,
    P_CAUTRUC_OTHER IN VARCHAR2,
    P_CONGNGHE IN VARCHAR2,
    P_CONGNGHE_OTHER IN VARCHAR2,
    P_MOTATOMTAT IN VARCHAR2,
    P_SOANH IN NUMBER

);

PROCEDURE PROC_APP_DETAIL_A02_UPDATE
(
    P_RETURN OUT NUMBER,
    P_ID IN APP_DETAIL_A03.ID % TYPE,
    P_CASE_CODE IN APP_DETAIL_A03.CASE_CODE % TYPE,
    P_APP_HEADER_ID IN APP_DETAIL_A03.APP_HEADER_ID % TYPE,
    P_LANGUAGE_CODE IN APP_DETAIL_A03.LANGUAGE_CODE % TYPE,
    P_TENTHIETKE IN VARCHAR2,
    P_NGAYTAOTHIETKE IN DATE,
    P_KHAITHACTM IN VARCHAR2,
    P_KHAITHACTM_TAINUOC IN VARCHAR,
    P_KHAITHACTM_NGAY IN DATE,
    P_CHUCNANG IN VARCHAR2,
    P_CHUCNANG_OTHER IN VARCHAR2,
    P_CAUTRUC IN VARCHAR2,
    P_CAUTRUC_OTHER IN VARCHAR2,
    P_CONGNGHE IN VARCHAR2,
    P_CONGNGHE_OTHER IN VARCHAR2,
    P_MOTATOMTAT IN VARCHAR2,
    P_SOANH IN NUMBER

);

PROCEDURE PROC_APP_DETAIL_A02_DELETE
(
    P_APP_HEADER_ID IN APP_DETAIL_PLB01_SDD.APP_HEADER_ID % TYPE,
    P_APPCODE IN APP_DETAIL_PLB01_SDD.APPCODE % TYPE,
    P_LANGUAGE_CODE IN APP_DETAIL_PLB01_SDD.LANGUAGE_CODE % TYPE,
    P_RETURN OUT NUMBER
);
END;
/


CREATE OR REPLACE 
PACKAGE BODY pkg_a02
IS



PROCEDURE PROC_GETBY_ID
(
    P_APP_HEADER_ID IN NUMBER,
    P_LANGUAGE_CODE IN APP_DETAIL_A03.LANGUAGE_CODE % TYPE,
    P_CURSOR OUT PKG_COMMON.T_CURSOR,
    P_CURSORHEADER OUT PKG_COMMON.T_CURSOR,
    P_CURSOR_DOC OUT PKG_COMMON.T_CURSOR,
    P_CURSOR_FEE OUT PKG_COMMON.T_CURSOR,
    P_CURSOR_OTHER_MASTER OUT PKG_COMMON.T_CURSOR,
    P_CURSOR_AUTHOR OUT PKG_COMMON.T_CURSOR,
    P_CURSOR_OTHER_DOC OUT PKG_COMMON.T_CURSOR,
    P_CURSOR_DOC_DESIGN OUT PKG_COMMON.T_CURSOR
)
IS
    V_CASE_CODE VARCHAR2(50);
BEGIN

    SELECT DISTINCT CASE_CODE INTO V_CASE_CODE FROM APPLICATION_HEADER WHERE ID = P_APP_HEADER_ID;

    OPEN P_CURSOR FOR
    SELECT D.*,AH.* FROM APP_DETAIL_A02 D
    JOIN APPLICATION_HEADER AH ON AH.CASE_CODE = D.CASE_CODE AND AH.LANGUAGUE_CODE = D.LANGUAGE_CODE AND AH.DELETED = 0
    AND AH.CASE_CODE = V_CASE_CODE ;

    OPEN P_CURSORHEADER FOR
    SELECT * FROM VIEW_APP_HEADER WHERE ID = P_APP_HEADER_ID;

    --LAY DANH SACH CAC TAI LIEU DINH KEM
    OPEN P_CURSOR_DOC FOR
    SELECT * FROM APP_DOCUMENT A  WHERE APP_HEADER_ID = P_APP_HEADER_ID  ORDER BY ID;

    OPEN P_CURSOR_FEE FOR
    SELECT * FROM APP_FEE_FIX  WHERE CASE_CODE = V_CASE_CODE ;

    OPEN P_CURSOR_OTHER_MASTER FOR
    SELECT * FROM OTHER_MASTER  WHERE app_header_id = p_app_header_id;

    OPEN P_CURSOR_AUTHOR FOR
    SELECT * FROM AUTHORS  WHERE app_header_id = p_app_header_id ;


    OPEN P_CURSOR_OTHER_DOC FOR SELECT  * FROM APP_DOCUMENT_OTHERS A  WHERE  APP_HEADER_ID = P_APP_HEADER_ID AND DELETED = 0
    AND FILETYPE = 1 ;


    OPEN P_CURSOR_OTHER_DOC FOR SELECT  * FROM APP_DOCUMENT_OTHERS A  WHERE  APP_HEADER_ID = P_APP_HEADER_ID AND DELETED = 0
    AND FILETYPE = 1 ;

    OPEN P_CURSOR_DOC_DESIGN FOR SELECT  * FROM APP_DOCUMENT_OTHERS A  WHERE  APP_HEADER_ID = P_APP_HEADER_ID AND DELETED = 0
    AND FILETYPE = 2 ;


EXCEPTION
WHEN OTHERS THEN
    RAISE;
END;

PROCEDURE PROC_APP_DETAIL_A02_INSERT
(
    P_RETURN OUT NUMBER,
    P_CASE_CODE IN APP_DETAIL_A03.CASE_CODE % TYPE,
    P_APP_HEADER_ID IN APP_DETAIL_A03.APP_HEADER_ID % TYPE,
    P_LANGUAGE_CODE IN APP_DETAIL_A03.LANGUAGE_CODE % TYPE,
    P_TENTHIETKE IN VARCHAR2,
    P_NGAYTAOTHIETKE IN DATE,
    P_KHAITHACTM IN VARCHAR2,
    P_KHAITHACTM_TAINUOC IN VARCHAR,
    P_KHAITHACTM_NGAY IN DATE,
    P_CHUCNANG IN VARCHAR2,
    P_CHUCNANG_OTHER IN VARCHAR2,
    P_CAUTRUC IN VARCHAR2,
    P_CAUTRUC_OTHER IN VARCHAR2,
    P_CONGNGHE IN VARCHAR2,
    P_CONGNGHE_OTHER IN VARCHAR2,
    P_MOTATOMTAT IN VARCHAR2,
    P_SOANH IN NUMBER

)
IS
V_ID NUMBER;
BEGIN

 SELECT SEQ_APP_DETAIL_A02.NEXTVAL INTO V_ID FROM DUAL;
 INSERT INTO APP_DETAIL_A02
 (
     ID, CASE_CODE, APP_HEADER_ID, LANGUAGE_CODE,
     TENTHIETKE,
     NGAYTAOTHIETKE ,
     KHAITHACTM ,
     KHAITHACTM_TAINUOC ,
     KHAITHACTM_NGAY ,
     CHUCNANG ,
     CHUCNANG_OTHER,
     CAUTRUC,
     CAUTRUC_OTHER,
     CONGNGHE,
     CONGNGHE_OTHER,
     MOTATOMTAT,
     SOANH
 )
  VALUES
  (
    V_ID, P_CASE_CODE,
    P_APP_HEADER_ID,
    P_LANGUAGE_CODE,
    P_TENTHIETKE,
    P_NGAYTAOTHIETKE,
    P_KHAITHACTM,
    P_KHAITHACTM_TAINUOC,
    P_KHAITHACTM_NGAY,
    P_CHUCNANG ,
    P_CHUCNANG_OTHER,
    P_CAUTRUC,
    P_CAUTRUC_OTHER,
    P_CONGNGHE ,
    P_CONGNGHE_OTHER ,
    P_MOTATOMTAT,
    P_SOANH
  );

  P_RETURN := V_ID;
EXCEPTION
WHEN OTHERS THEN
    P_RETURN := -1;
    RAISE;
END;


PROCEDURE PROC_APP_DETAIL_A02_UPDATE
(
    P_RETURN OUT NUMBER,
    P_ID IN APP_DETAIL_A03.ID % TYPE,
    P_CASE_CODE IN APP_DETAIL_A03.CASE_CODE % TYPE,
    P_APP_HEADER_ID IN APP_DETAIL_A03.APP_HEADER_ID % TYPE,
    P_LANGUAGE_CODE IN APP_DETAIL_A03.LANGUAGE_CODE % TYPE,
    P_TENTHIETKE IN VARCHAR2,
    P_NGAYTAOTHIETKE IN DATE,
    P_KHAITHACTM IN VARCHAR2,
    P_KHAITHACTM_TAINUOC IN VARCHAR,
    P_KHAITHACTM_NGAY IN DATE,
    P_CHUCNANG IN VARCHAR2,
    P_CHUCNANG_OTHER IN VARCHAR2,
    P_CAUTRUC IN VARCHAR2,
    P_CAUTRUC_OTHER IN VARCHAR2,
    P_CONGNGHE IN VARCHAR2,
    P_CONGNGHE_OTHER IN VARCHAR2,
    P_MOTATOMTAT IN VARCHAR2,
    P_SOANH IN NUMBER

)
IS

BEGIN

 UPDATE  APP_DETAIL_A02 SET

     NGAYTAOTHIETKE = P_NGAYTAOTHIETKE,
     KHAITHACTM = P_KHAITHACTM,
     KHAITHACTM_TAINUOC = P_KHAITHACTM_TAINUOC,
     KHAITHACTM_NGAY = P_KHAITHACTM_NGAY,
     CHUCNANG = P_CHUCNANG,
     CHUCNANG_OTHER = P_CHUCNANG_OTHER,
     CAUTRUC = P_CAUTRUC,
     CAUTRUC_OTHER = P_CAUTRUC_OTHER,
     CONGNGHE= P_CONGNGHE,
     CONGNGHE_OTHER= P_CONGNGHE_OTHER,
     MOTATOMTAT= P_MOTATOMTAT,
     SOANH = P_SOANH,
     TENTHIETKE = P_TENTHIETKE
     WHERE       ID = P_ID;

  P_RETURN := P_ID;
EXCEPTION
WHEN OTHERS THEN
    P_RETURN := -1;
    RAISE;
END;




PROCEDURE PROC_APP_DETAIL_A02_DELETE
(
    P_APP_HEADER_ID IN APP_DETAIL_PLB01_SDD.APP_HEADER_ID % TYPE,
    P_APPCODE IN APP_DETAIL_PLB01_SDD.APPCODE % TYPE,
    P_LANGUAGE_CODE IN APP_DETAIL_PLB01_SDD.LANGUAGE_CODE % TYPE,
    P_RETURN OUT NUMBER
)
IS
    V_CASE_CODE VARCHAR2(50);
BEGIN

    SELECT DISTINCT CASE_CODE INTO V_CASE_CODE FROM APPLICATION_HEADER WHERE ID = P_APP_HEADER_ID;

    DELETE APP_DETAIL_A02
    WHERE CASE_CODE = V_CASE_CODE ; --AND LANGUAGE_CODE = P_LANGUAGE_CODE;


    DELETE FROM  APP_FEE_FIX  A WHERE  A.APP_HEADER_ID = P_APP_HEADER_ID;

    DELETE FROM  OTHER_MASTER   A WHERE  A.APP_HEADER_ID = P_APP_HEADER_ID;

    DELETE FROM  AUTHORS  A WHERE  A.APP_HEADER_ID = P_APP_HEADER_ID;

    DELETE FROM APP_DOCUMENT_OTHERS A WHERE  A.APP_HEADER_ID = P_APP_HEADER_ID;

    P_RETURN:= 1;

COMMIT;
EXCEPTION
WHEN OTHERS THEN
    P_RETURN := PKG_COMMON.ERROR;
    RAISE;
END  ;




END;
/


-- End of DDL Script for Package LEGALTECH.PKG_A02



-- End of DDL Script for Table LEGALTECH.APP_DETAIL_A02

