//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApps.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WebApps.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gửi đơn.
        /// </summary>
        public static string btnGuiDon {
            get {
                return ResourceManager.GetString("btnGuiDon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lưu tạm.
        /// </summary>
        public static string btnLuuTam {
            get {
                return ResourceManager.GetString("btnLuuTam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to chứng khoán.
        /// </summary>
        public static string Code {
            get {
                return ResourceManager.GetString("Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ẩn.
        /// </summary>
        public static string lblAn {
            get {
                return ResourceManager.GetString("lblAn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bản.
        /// </summary>
        public static string lblBan {
            get {
                return ResourceManager.GetString("lblBan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bản dịch tiếng Việt, gồm.
        /// </summary>
        public static string lblBanDichTiengVietGom {
            get {
                return ResourceManager.GetString("lblBanDichTiengVietGom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bản sao đơn đầu tiên, gồm.
        /// </summary>
        public static string lblbanSaoDauTienGom {
            get {
                return ResourceManager.GetString("lblbanSaoDauTienGom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chất lượng.
        /// </summary>
        public static string lblChatLuong {
            get {
                return ResourceManager.GetString("lblChatLuong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chủ đơn.
        /// </summary>
        public static string lblChuDon {
            get {
                return ResourceManager.GetString("lblChuDon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chủ đơn khác.
        /// </summary>
        public static string lblChuDonKhac {
            get {
                return ResourceManager.GetString("lblChuDonKhac", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Có sử dụng đơn ưu tiên.
        /// </summary>
        public static string lblCoSuDungDonUT {
            get {
                return ResourceManager.GetString("lblCoSuDungDonUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Có yêu cầu cấp Phó bản Giấy chứng nhận đăng ký nhãn hiệu.
        /// </summary>
        public static string lblCoYeuCauCapPho {
            get {
                return ResourceManager.GetString("lblCoYeuCauCapPho", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đặc tính hàng hóa.
        /// </summary>
        public static string lblDacTinhHanghoa {
            get {
                return ResourceManager.GetString("lblDacTinhHanghoa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đặc tính khác.
        /// </summary>
        public static string lblDacTinhKhac {
            get {
                return ResourceManager.GetString("lblDacTinhKhac", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ĐẠI DIỆN CỦA CHỦ ĐƠN.
        /// </summary>
        public static string lblDaiDienChuDon {
            get {
                return ResourceManager.GetString("lblDaiDienChuDon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Địa chỉ.
        /// </summary>
        public static string lblDiaChi {
            get {
                return ResourceManager.GetString("lblDiaChi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Điện thoại.
        /// </summary>
        public static string lblDienThoai {
            get {
                return ResourceManager.GetString("lblDienThoai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đơn này được tách ra từ đơn số .
        /// </summary>
        public static string lblDonTachRaTuDonSo {
            get {
                return ResourceManager.GetString("lblDonTachRaTuDonSo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giấy chuyển nhượng quyền ưu tiên.
        /// </summary>
        public static string lblGiayChuyenNhuongQuyenUT {
            get {
                return ResourceManager.GetString("lblGiayChuyenNhuongQuyenUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Là người đại diện theo pháp luật của chủ đơn.
        /// </summary>
        public static string lblLaNguoiDaiDienTheoPL {
            get {
                return ResourceManager.GetString("lblLaNguoiDaiDienTheoPL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Là người khác được uỷ quyền của chủ đơn.
        /// </summary>
        public static string lblLaNguoiKhacDuocUyQuyen {
            get {
                return ResourceManager.GetString("lblLaNguoiKhacDuocUyQuyen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Là tổ chức dịch vụ đại diện sở hữu công nghiệp được uỷ quyền của chủ đơn.
        /// </summary>
        public static string lblLaToChucDichVuDaiDienSoHuu {
            get {
                return ResourceManager.GetString("lblLaToChucDichVuDaiDienSoHuu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lệ phí công bố đơn.
        /// </summary>
        public static string lblLePhiCBDon {
            get {
                return ResourceManager.GetString("lblLePhiCBDon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lệ phí nộp đơn.
        /// </summary>
        public static string lblLePhiNopDon {
            get {
                return ResourceManager.GetString("lblLePhiNopDon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lệ phí  yêu cầu hưởng quyền ưu tiên.
        /// </summary>
        public static string lblLePhiYeuCauHuongQuyenUuTien {
            get {
                return ResourceManager.GetString("lblLePhiYeuCauHuongQuyenUuTien", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loại phí, lệ phí.
        /// </summary>
        public static string lblLoaiPhiLePhi {
            get {
                return ResourceManager.GetString("lblLoaiPhiLePhi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mẫu nhãn hiệu.
        /// </summary>
        public static string lblMauNhanHieu {
            get {
                return ResourceManager.GetString("lblMauNhanHieu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mầu sắc.
        /// </summary>
        public static string lblMauSac {
            get {
                return ResourceManager.GetString("lblMauSac", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mỗi nhóm có trên 6 sản phẩm/dịch vụ (từ sản phẩm/dịch vụ thứ 7 trở đi).
        /// </summary>
        public static string lblMoiNhom6SanPham {
            get {
                return ResourceManager.GetString("lblMoiNhom6SanPham", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mô tả.
        /// </summary>
        public static string lblMoTa {
            get {
                return ResourceManager.GetString("lblMoTa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MÔ TẢ TÓM TẮT ĐẶC TÍNH CỦA HÀNG HOÁ/DỊCH VỤ ĐƯỢC CHỨNG NHẬN.
        /// </summary>
        public static string lblMoTaDacTinhCuaHangHoa {
            get {
                return ResourceManager.GetString("lblMoTaDacTinhCuaHangHoa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày nộp đơn.
        /// </summary>
        public static string lblNgayNopDon {
            get {
                return ResourceManager.GetString("lblNgayNopDon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nguồn gốc địa lý.
        /// </summary>
        public static string lblNguonGocDiaLy {
            get {
                return ResourceManager.GetString("lblNguonGocDiaLy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhãn hiệu.
        /// </summary>
        public static string lblNhanHieu {
            get {
                return ResourceManager.GetString("lblNhanHieu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhãn hiệu chứng nhận.
        /// </summary>
        public static string lblNhanHieuChungNhan {
            get {
                return ResourceManager.GetString("lblNhanHieuChungNhan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhãn hiệu liên kết.
        /// </summary>
        public static string lblNhanHieuLienKet {
            get {
                return ResourceManager.GetString("lblNhanHieuLienKet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhãn hiệu tập thể.
        /// </summary>
        public static string lblNhanHieuTapThe {
            get {
                return ResourceManager.GetString("lblNhanHieuTapThe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nước nộp đơn.
        /// </summary>
        public static string lblNuocNopDon {
            get {
                return ResourceManager.GetString("lblNuocNopDon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PHÍ, LỆ PHÍ.
        /// </summary>
        public static string lblPhiLePhi {
            get {
                return ResourceManager.GetString("lblPhiLePhi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phí phân loại quốc tế về Nhãn hiệu.
        /// </summary>
        public static string lblPhiLoaiQTNH {
            get {
                return ResourceManager.GetString("lblPhiLoaiQTNH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phí thẩm định đơn.
        /// </summary>
        public static string lblPhiThamDinhDon {
            get {
                return ResourceManager.GetString("lblPhiThamDinhDon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phí tra cứu phục vụ thẩm định nội dung cho mỗi nhóm hàng hoá, dịch vụ.
        /// </summary>
        public static string lblPhiTraCuuPhuVuThamDinh {
            get {
                return ResourceManager.GetString("lblPhiTraCuuPhuVuThamDinh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số bản.
        /// </summary>
        public static string lblSoBan {
            get {
                return ResourceManager.GetString("lblSoBan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số đối tượng tính phí.
        /// </summary>
        public static string lblSoDoiTuongTinhPhi {
            get {
                return ResourceManager.GetString("lblSoDoiTuongTinhPhi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số đơn.
        /// </summary>
        public static string lblSoDon {
            get {
                return ResourceManager.GetString("lblSoDon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số tiền.
        /// </summary>
        public static string lblSoTien {
            get {
                return ResourceManager.GetString("lblSoTien", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tải file.
        /// </summary>
        public static string lblTaiFile {
            get {
                return ResourceManager.GetString("lblTaiFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tài liệu chứng minh quyền ưu tiên.
        /// </summary>
        public static string lblTaiLieuChungMinhQuyenUuTien {
            get {
                return ResourceManager.GetString("lblTaiLieuChungMinhQuyenUuTien", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên đầy đủ.
        /// </summary>
        public static string lblTenDayDu {
            get {
                return ResourceManager.GetString("lblTenDayDu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên nhãn hiệu.
        /// </summary>
        public static string lblTenNhanHieu {
            get {
                return ResourceManager.GetString("lblTenNhanHieu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm chủ đơn.
        /// </summary>
        public static string lblThemChuDon {
            get {
                return ResourceManager.GetString("lblThemChuDon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm đơn.
        /// </summary>
        public static string lblThemDon {
            get {
                return ResourceManager.GetString("lblThemDon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theo đơn (các đơn) nộp theo Công ước Paris.
        /// </summary>
        public static string lblTheoDonNopCongUocPR {
            get {
                return ResourceManager.GetString("lblTheoDonNopCongUocPR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theo đơn (các đơn) đầu tiên nộp tại Việt Nam.
        /// </summary>
        public static string lblTheoDonNopTaiVN {
            get {
                return ResourceManager.GetString("lblTheoDonNopTaiVN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theo thoả thuận khác.
        /// </summary>
        public static string lblTheoThoaThuanKhac {
            get {
                return ResourceManager.GetString("lblTheoThoaThuanKhac", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to YÊU CẦU HƯỞNG QUYỀN ƯU TIÊN.
        /// </summary>
        public static string lblYeuCauHuongQuyenUT {
            get {
                return ResourceManager.GetString("lblYeuCauHuongQuyenUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QUẢN LÝ VỤ VIỆC.
        /// </summary>
        public static string QuanLyVuViec {
            get {
                return ResourceManager.GetString("QuanLyVuViec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quản lý vụ việc.
        /// </summary>
        public static string TM04NH_QuanLyVuViec {
            get {
                return ResourceManager.GetString("TM04NH_QuanLyVuViec", resourceCulture);
            }
        }
    }
}
