//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApps.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WebApps.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gửi đơn.
        /// </summary>
        public static string btnGuiDon {
            get {
                return ResourceManager.GetString("btnGuiDon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lưu tạm.
        /// </summary>
        public static string btnLuuTam {
            get {
                return ResourceManager.GetString("btnLuuTam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to chứng khoán.
        /// </summary>
        public static string Code {
            get {
                return ResourceManager.GetString("Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ẩn.
        /// </summary>
        public static string lblAn {
            get {
                return ResourceManager.GetString("lblAn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ảnh đại diện.
        /// </summary>
        public static string lblAnhDaiDien {
            get {
                return ResourceManager.GetString("lblAnhDaiDien", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bản.
        /// </summary>
        public static string lblBan {
            get {
                return ResourceManager.GetString("lblBan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bản (có danh mục và phân nhóm hàng hoá, dịch vụ mang nhãn hiệu).
        /// </summary>
        public static string lblBanCoDanhMucPhanLoaiHangHoa {
            get {
                return ResourceManager.GetString("lblBanCoDanhMucPhanLoaiHangHoa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bản dịch tiếng Việt, gồm.
        /// </summary>
        public static string lblBanDichTiengVietGom {
            get {
                return ResourceManager.GetString("lblBanDichTiengVietGom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bản đồ khu vực địa lý.
        /// </summary>
        public static string lblBanDoKhuVucDiaLy {
            get {
                return ResourceManager.GetString("lblBanDoKhuVucDiaLy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bản gốc.
        /// </summary>
        public static string lblBanGoc {
            get {
                return ResourceManager.GetString("lblBanGoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bản gốc nộp sau.
        /// </summary>
        public static string lblBanGocNopSau {
            get {
                return ResourceManager.GetString("lblBanGocNopSau", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bản gốc đã nộp theo đơn số.
        /// </summary>
        public static string lblBanGocNopTheoDonSo {
            get {
                return ResourceManager.GetString("lblBanGocNopTheoDonSo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bản sao.
        /// </summary>
        public static string lblBanSao {
            get {
                return ResourceManager.GetString("lblBanSao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bản sao đơn đầu tiên, gồm.
        /// </summary>
        public static string lblbanSaoDauTienGom {
            get {
                return ResourceManager.GetString("lblbanSaoDauTienGom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CÁC TÀI LIỆU KHÁC.
        /// </summary>
        public static string lblCacTaiLieuKhac {
            get {
                return ResourceManager.GetString("lblCacTaiLieuKhac", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Các tài liệu liên quan đính kèm trong đơn.
        /// </summary>
        public static string lblCacTaiLieuLienQuanDinhKem {
            get {
                return ResourceManager.GetString("lblCacTaiLieuLienQuanDinhKem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CAM KẾT CỦA CHỦ ĐƠN.
        /// </summary>
        public static string lblCamKetCuaChuDon {
            get {
                return ResourceManager.GetString("lblCamKetCuaChuDon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chất lượng.
        /// </summary>
        public static string lblChatLuong {
            get {
                return ResourceManager.GetString("lblChatLuong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chọn file.
        /// </summary>
        public static string lblChonFile {
            get {
                return ResourceManager.GetString("lblChonFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chủ đơn.
        /// </summary>
        public static string lblChuDon {
            get {
                return ResourceManager.GetString("lblChuDon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chủ đơn khác.
        /// </summary>
        public static string lblChuDonKhac {
            get {
                return ResourceManager.GetString("lblChuDonKhac", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chứng từ phí, lệ phí.
        /// </summary>
        public static string lblChungTuLePhi {
            get {
                return ResourceManager.GetString("lblChungTuLePhi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Có.
        /// </summary>
        public static string lblCo {
            get {
                return ResourceManager.GetString("lblCo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Có sử dụng đơn ưu tiên.
        /// </summary>
        public static string lblCoSuDungDonUT {
            get {
                return ResourceManager.GetString("lblCoSuDungDonUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Có tài liệu bổ trợ khai tại trang bổ sung.
        /// </summary>
        public static string lblCoTaiLieuBoTro {
            get {
                return ResourceManager.GetString("lblCoTaiLieuBoTro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Có yêu cầu cấp Phó bản Giấy chứng nhận đăng ký nhãn hiệu.
        /// </summary>
        public static string lblCoYeuCauCapPho {
            get {
                return ResourceManager.GetString("lblCoYeuCauCapPho", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đặc tính hàng hóa.
        /// </summary>
        public static string lblDacTinhHanghoa {
            get {
                return ResourceManager.GetString("lblDacTinhHanghoa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đặc tính khác.
        /// </summary>
        public static string lblDacTinhKhac {
            get {
                return ResourceManager.GetString("lblDacTinhKhac", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ĐẠI DIỆN CỦA CHỦ ĐƠN.
        /// </summary>
        public static string lblDaiDienChuDon {
            get {
                return ResourceManager.GetString("lblDaiDienChuDon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đại diện SHCN.
        /// </summary>
        public static string lblDaiDienSHCN {
            get {
                return ResourceManager.GetString("lblDaiDienSHCN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ĐĂNG KÝ NHÃN HIỆU.
        /// </summary>
        public static string lblDangKyNhanHieu {
            get {
                return ResourceManager.GetString("lblDangKyNhanHieu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danh sách mẫu đơn.
        /// </summary>
        public static string lblDanhSachMauDon {
            get {
                return ResourceManager.GetString("lblDanhSachMauDon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nếu Người nộp đơn không nhớ số đơn gốc thì có thể để trống, Luật sư sẽ điền thay sau.
        /// </summary>
        public static string lblDatatitle04NHD08 {
            get {
                return ResourceManager.GetString("lblDatatitle04NHD08", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Địa chỉ.
        /// </summary>
        public static string lblDiaChi {
            get {
                return ResourceManager.GetString("lblDiaChi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Điện thoại.
        /// </summary>
        public static string lblDienThoai {
            get {
                return ResourceManager.GetString("lblDienThoai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đơn này được tách ra từ đơn số .
        /// </summary>
        public static string lblDonTachRaTuDonSo {
            get {
                return ResourceManager.GetString("lblDonTachRaTuDonSo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giấy chuyển nhượng quyền ưu tiên.
        /// </summary>
        public static string lblGiayChuyenNhuongQuyenUT {
            get {
                return ResourceManager.GetString("lblGiayChuyenNhuongQuyenUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giấy uỷ quyền bằng tiếng.
        /// </summary>
        public static string lblGiayUyQuyen {
            get {
                return ResourceManager.GetString("lblGiayUyQuyen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gõ hàng hóa muốn đăng ký, chọn Class tương ứng.
        /// </summary>
        public static string lblGohangHoaDKChonClass {
            get {
                return ResourceManager.GetString("lblGohangHoaDKChonClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hàng hóa.
        /// </summary>
        public static string lblHangHoa {
            get {
                return ResourceManager.GetString("lblHangHoa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hàng hóa đã thêm.
        /// </summary>
        public static string lblHangHoaDaThem {
            get {
                return ResourceManager.GetString("lblHangHoaDaThem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MÔ TẢ TÓM TẮT ĐẶC TÍNH CỦA HÀNG HÓA/DỊCH VỤ ĐƯỢC CHỨNG NHẬN.
        /// </summary>
        public static string lblHeaderDanhMucVaPhanLoaiHangHoa {
            get {
                return ResourceManager.GetString("lblHeaderDanhMucVaPhanLoaiHangHoa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Khách hàng điền đủ thông tin lên và tải lên.
        /// </summary>
        public static string lblKhacHangFillThongTin {
            get {
                return ResourceManager.GetString("lblKhacHangFillThongTin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Khai tại.
        /// </summary>
        public static string lblKhaiTai {
            get {
                return ResourceManager.GetString("lblKhaiTai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không.
        /// </summary>
        public static string lblKhong {
            get {
                return ResourceManager.GetString("lblKhong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không tìm thấy dữ liệu.
        /// </summary>
        public static string lblKhongTimThayDL {
            get {
                return ResourceManager.GetString("lblKhongTimThayDL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Là người đại diện theo pháp luật của chủ đơn.
        /// </summary>
        public static string lblLaNguoiDaiDienTheoPL {
            get {
                return ResourceManager.GetString("lblLaNguoiDaiDienTheoPL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Là người khác được uỷ quyền của chủ đơn.
        /// </summary>
        public static string lblLaNguoiKhacDuocUyQuyen {
            get {
                return ResourceManager.GetString("lblLaNguoiKhacDuocUyQuyen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Là tổ chức dịch vụ đại diện sở hữu công nghiệp được uỷ quyền của chủ đơn.
        /// </summary>
        public static string lblLaToChucDichVuDaiDienSoHuu {
            get {
                return ResourceManager.GetString("lblLaToChucDichVuDaiDienSoHuu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lên đầu trang.
        /// </summary>
        public static string lblLenTrangDau {
            get {
                return ResourceManager.GetString("lblLenTrangDau", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lệ phí công bố đơn.
        /// </summary>
        public static string lblLePhiCBDon {
            get {
                return ResourceManager.GetString("lblLePhiCBDon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lệ phí nộp đơn.
        /// </summary>
        public static string lblLePhiNopDon {
            get {
                return ResourceManager.GetString("lblLePhiNopDon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lệ phí  yêu cầu hưởng quyền ưu tiên.
        /// </summary>
        public static string lblLePhiYeuCauHuongQuyenUuTien {
            get {
                return ResourceManager.GetString("lblLePhiYeuCauHuongQuyenUuTien", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loại phí, lệ phí.
        /// </summary>
        public static string lblLoaiPhiLePhi {
            get {
                return ResourceManager.GetString("lblLoaiPhiLePhi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã đại điện.
        /// </summary>
        public static string lblMaDaiDien {
            get {
                return ResourceManager.GetString("lblMaDaiDien", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã nhóm.
        /// </summary>
        public static string lblMaNhom {
            get {
                return ResourceManager.GetString("lblMaNhom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mẫu.
        /// </summary>
        public static string lblMau {
            get {
                return ResourceManager.GetString("lblMau", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mẫu nhãn hiệu.
        /// </summary>
        public static string lblMauNhanHieu {
            get {
                return ResourceManager.GetString("lblMauNhanHieu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mẫu nhãn hiệu, gồm.
        /// </summary>
        public static string lblMauNhanHieuGom {
            get {
                return ResourceManager.GetString("lblMauNhanHieuGom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mầu sắc.
        /// </summary>
        public static string lblMauSac {
            get {
                return ResourceManager.GetString("lblMauSac", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tải mẫu về.
        /// </summary>
        public static string lblMauTaiVe {
            get {
                return ResourceManager.GetString("lblMauTaiVe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mỗi nhóm có trên 6 sản phẩm/dịch vụ (từ sản phẩm/dịch vụ thứ 7 trở đi).
        /// </summary>
        public static string lblMoiNhom6SanPham {
            get {
                return ResourceManager.GetString("lblMoiNhom6SanPham", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mô tả.
        /// </summary>
        public static string lblMoTa {
            get {
                return ResourceManager.GetString("lblMoTa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MÔ TẢ TÓM TẮT ĐẶC TÍNH CỦA HÀNG HOÁ/DỊCH VỤ ĐƯỢC CHỨNG NHẬN.
        /// </summary>
        public static string lblMoTaDacTinhCuaHangHoa {
            get {
                return ResourceManager.GetString("lblMoTaDacTinhCuaHangHoa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Năm.
        /// </summary>
        public static string lblNam {
            get {
                return ResourceManager.GetString("lblNam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày khai.
        /// </summary>
        public static string lblNgayKhai {
            get {
                return ResourceManager.GetString("lblNgayKhai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày nộp đơn.
        /// </summary>
        public static string lblNgayNopDon {
            get {
                return ResourceManager.GetString("lblNgayNopDon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nguồn gốc địa lý.
        /// </summary>
        public static string lblNguonGocDiaLy {
            get {
                return ResourceManager.GetString("lblNguonGocDiaLy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhãn hiệu.
        /// </summary>
        public static string lblNhanHieu {
            get {
                return ResourceManager.GetString("lblNhanHieu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhãn hiệu chứng nhận.
        /// </summary>
        public static string lblNhanHieuChungNhan {
            get {
                return ResourceManager.GetString("lblNhanHieuChungNhan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhãn hiệu liên kết.
        /// </summary>
        public static string lblNhanHieuLienKet {
            get {
                return ResourceManager.GetString("lblNhanHieuLienKet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhãn hiệu tập thể.
        /// </summary>
        public static string lblNhanHieuTapThe {
            get {
                return ResourceManager.GetString("lblNhanHieuTapThe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhập tên tài liệu đính kèm.
        /// </summary>
        public static string lblNhapTenTaiLieuDinhKem {
            get {
                return ResourceManager.GetString("lblNhapTenTaiLieuDinhKem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhóm.
        /// </summary>
        public static string lblNhom {
            get {
                return ResourceManager.GetString("lblNhom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không.
        /// </summary>
        public static string lblNo {
            get {
                return ResourceManager.GetString("lblNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nước nộp đơn.
        /// </summary>
        public static string lblNuocNopDon {
            get {
                return ResourceManager.GetString("lblNuocNopDon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PHÍ, LỆ PHÍ.
        /// </summary>
        public static string lblPhiLePhi {
            get {
                return ResourceManager.GetString("lblPhiLePhi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phí phân loại quốc tế về Nhãn hiệu.
        /// </summary>
        public static string lblPhiLoaiQTNH {
            get {
                return ResourceManager.GetString("lblPhiLoaiQTNH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phí thẩm định đơn.
        /// </summary>
        public static string lblPhiThamDinhDon {
            get {
                return ResourceManager.GetString("lblPhiThamDinhDon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phí tra cứu phục vụ thẩm định nội dung cho mỗi nhóm hàng hoá, dịch vụ.
        /// </summary>
        public static string lblPhiTraCuuPhuVuThamDinh {
            get {
                return ResourceManager.GetString("lblPhiTraCuuPhuVuThamDinh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quy chế sử dụng NH tập thể/chứng nhận, gồm.
        /// </summary>
        public static string lblQuyCheSuDungNH {
            get {
                return ResourceManager.GetString("lblQuyCheSuDungNH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sản phẩm.
        /// </summary>
        public static string lblSanPham {
            get {
                return ResourceManager.GetString("lblSanPham", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ảnh có kích cỡ từ.
        /// </summary>
        public static string lblSizeOfPicture {
            get {
                return ResourceManager.GetString("lblSizeOfPicture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số bản.
        /// </summary>
        public static string lblSoBan {
            get {
                return ResourceManager.GetString("lblSoBan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số đối tượng tính phí.
        /// </summary>
        public static string lblSoDoiTuongTinhPhi {
            get {
                return ResourceManager.GetString("lblSoDoiTuongTinhPhi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số đơn.
        /// </summary>
        public static string lblSoDon {
            get {
                return ResourceManager.GetString("lblSoDon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số tiền.
        /// </summary>
        public static string lblSoTien {
            get {
                return ResourceManager.GetString("lblSoTien", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to STT.
        /// </summary>
        public static string lblSTT {
            get {
                return ResourceManager.GetString("lblSTT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tải file.
        /// </summary>
        public static string lblTaiFile {
            get {
                return ResourceManager.GetString("lblTaiFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tài liệu chứng minh quyền ưu tiên.
        /// </summary>
        public static string lblTaiLieuChungMinhQuyenUT {
            get {
                return ResourceManager.GetString("lblTaiLieuChungMinhQuyenUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tài liệu chứng minh quyền ưu tiên.
        /// </summary>
        public static string lblTaiLieuChungMinhQuyenUuTien {
            get {
                return ResourceManager.GetString("lblTaiLieuChungMinhQuyenUuTien", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tài liệu xác nhận thụ hưởng quyền đăng ký từ người khác.
        /// </summary>
        public static string lblTaiLieuDKXacNhanThuHuong {
            get {
                return ResourceManager.GetString("lblTaiLieuDKXacNhanThuHuong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tài liệu khác.
        /// </summary>
        public static string lblTaiLieuKhac {
            get {
                return ResourceManager.GetString("lblTaiLieuKhac", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CÁC TÀI LIỆU CÓ TRONG ĐƠN.
        /// </summary>
        public static string lblTaiLieuTrongDon {
            get {
                return ResourceManager.GetString("lblTaiLieuTrongDon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tài liệu xác nhận được phép sử dụng các dấu hiệu đặc biệt (biểu tượng, cờ, huy hiệu, con dấu…), gồm.
        /// </summary>
        public static string lblTaiLieuXacNhanDuoc {
            get {
                return ResourceManager.GetString("lblTaiLieuXacNhanDuoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tài liệu xác nhận quyền đăng ký nhãn hiệu.
        /// </summary>
        public static string lblTaiLieuXacNhanQuyenDKNH {
            get {
                return ResourceManager.GetString("lblTaiLieuXacNhanQuyenDKNH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tất cả.
        /// </summary>
        public static string lblTatCa {
            get {
                return ResourceManager.GetString("lblTatCa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên đầy đủ.
        /// </summary>
        public static string lblTenDayDu {
            get {
                return ResourceManager.GetString("lblTenDayDu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên file.
        /// </summary>
        public static string lblTenFile {
            get {
                return ResourceManager.GetString("lblTenFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên nhãn hiệu.
        /// </summary>
        public static string lblTenNhanHieu {
            get {
                return ResourceManager.GetString("lblTenNhanHieu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên tài liệu.
        /// </summary>
        public static string lblTenTaiLieu {
            get {
                return ResourceManager.GetString("lblTenTaiLieu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tháng.
        /// </summary>
        public static string lblThang {
            get {
                return ResourceManager.GetString("lblThang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm.
        /// </summary>
        public static string lblThem {
            get {
                return ResourceManager.GetString("lblThem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm chủ đơn.
        /// </summary>
        public static string lblThemChuDon {
            get {
                return ResourceManager.GetString("lblThemChuDon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm đơn.
        /// </summary>
        public static string lblThemDon {
            get {
                return ResourceManager.GetString("lblThemDon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theo đơn (các đơn) nộp theo Công ước Paris.
        /// </summary>
        public static string lblTheoDonNopCongUocPR {
            get {
                return ResourceManager.GetString("lblTheoDonNopCongUocPR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theo đơn (các đơn) đầu tiên nộp tại Việt Nam.
        /// </summary>
        public static string lblTheoDonNopTaiVN {
            get {
                return ResourceManager.GetString("lblTheoDonNopTaiVN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theo thoả thuận khác.
        /// </summary>
        public static string lblTheoThoaThuanKhac {
            get {
                return ResourceManager.GetString("lblTheoThoaThuanKhac", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email không đúng định dạng.
        /// </summary>
        public static string lblThongBaoLoiEmail {
            get {
                return ResourceManager.GetString("lblThongBaoLoiEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tìm kiếm nhóm.
        /// </summary>
        public static string lblTimKiemNhom {
            get {
                return ResourceManager.GetString("lblTimKiemNhom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tôi cam đoan mọi thông tin trong tờ khai trên đây là trung thực, đúng sự thật và hoàn toàn chịu trách nhiệm trước pháp luật..
        /// </summary>
        public static string lblToiCamdoan {
            get {
                return ResourceManager.GetString("lblToiCamdoan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tờ khai, gồm.
        /// </summary>
        public static string lblToKhaiGom {
            get {
                return ResourceManager.GetString("lblToKhaiGom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tổng số nhóm.
        /// </summary>
        public static string lblTongSoNhom {
            get {
                return ResourceManager.GetString("lblTongSoNhom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tổng SP.
        /// </summary>
        public static string lblTongSP {
            get {
                return ResourceManager.GetString("lblTongSP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to trang.
        /// </summary>
        public static string lblTrang {
            get {
                return ResourceManager.GetString("lblTrang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Văn bản của UBND tỉnh, TP trực thuộc TW cho phép sử dụng địa danh hoặc dấu hiệu khác chỉ nguồn gốc địa lý của đặc sản địa phượng.
        /// </summary>
        public static string lblVanBanUBNDTinh {
            get {
                return ResourceManager.GetString("lblVanBanUBNDTinh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xem trước.
        /// </summary>
        public static string lblXemTruoc {
            get {
                return ResourceManager.GetString("lblXemTruoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Có.
        /// </summary>
        public static string lblYes {
            get {
                return ResourceManager.GetString("lblYes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to YÊU CẦU HƯỞNG QUYỀN ƯU TIÊN.
        /// </summary>
        public static string lblYeuCauHuongQuyenUT {
            get {
                return ResourceManager.GetString("lblYeuCauHuongQuyenUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QUẢN LÝ VỤ VIỆC.
        /// </summary>
        public static string QuanLyVuViec {
            get {
                return ResourceManager.GetString("QuanLyVuViec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quản lý vụ việc.
        /// </summary>
        public static string TM04NH_QuanLyVuViec {
            get {
                return ResourceManager.GetString("TM04NH_QuanLyVuViec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tìm kiếm.
        /// </summary>
        public static string WikiSearchButton {
            get {
                return ResourceManager.GetString("WikiSearchButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tìm kiếm theo tiêu đề hoặc hashtag.
        /// </summary>
        public static string WikiSearchPlaceholder {
            get {
                return ResourceManager.GetString("WikiSearchPlaceholder", resourceCulture);
            }
        }
    }
}
