//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApps.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WebApps.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gỡ bài.
        /// </summary>
        public static string btnGoBai {
            get {
                return ResourceManager.GetString("btnGoBai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gỡ bỏ.
        /// </summary>
        public static string btnGoBo {
            get {
                return ResourceManager.GetString("btnGoBo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gửi bài.
        /// </summary>
        public static string btnGuiBai {
            get {
                return ResourceManager.GetString("btnGuiBai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gửi đơn.
        /// </summary>
        public static string btnGuiDon {
            get {
                return ResourceManager.GetString("btnGuiDon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lưu tạm.
        /// </summary>
        public static string btnLuuTam {
            get {
                return ResourceManager.GetString("btnLuuTam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sửa.
        /// </summary>
        public static string btnSua {
            get {
                return ResourceManager.GetString("btnSua", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Từ chối.
        /// </summary>
        public static string btnTuChoi {
            get {
                return ResourceManager.GetString("btnTuChoi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xem chi tiêt.
        /// </summary>
        public static string btnXemChiTiet {
            get {
                return ResourceManager.GetString("btnXemChiTiet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xóa.
        /// </summary>
        public static string btnXoa {
            get {
                return ResourceManager.GetString("btnXoa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xuất bản.
        /// </summary>
        public static string btnXuatban {
            get {
                return ResourceManager.GetString("btnXuatban", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Case Name không được để trống!.
        /// </summary>
        public static string CaseNameTrong {
            get {
                return ResourceManager.GetString("CaseNameTrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chưa nhập tên hàng hóa!.
        /// </summary>
        public static string ChuaNhapTenHangHoa {
            get {
                return ResourceManager.GetString("ChuaNhapTenHangHoa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client Reference không được để trống!.
        /// </summary>
        public static string ClientReferenceTrong {
            get {
                return ResourceManager.GetString("ClientReferenceTrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to chứng khoán.
        /// </summary>
        public static string Code {
            get {
                return ResourceManager.GetString("Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PHẦN DÀNH CHO LUẬT SƯ.
        /// </summary>
        public static string DanhChoLuatSu {
            get {
                return ResourceManager.GetString("DanhChoLuatSu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ẩn.
        /// </summary>
        public static string lblAn {
            get {
                return ResourceManager.GetString("lblAn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ảnh đại diện.
        /// </summary>
        public static string lblAnhDaiDien {
            get {
                return ResourceManager.GetString("lblAnhDaiDien", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bài viết.
        /// </summary>
        public static string lblBaiViet {
            get {
                return ResourceManager.GetString("lblBaiViet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bản.
        /// </summary>
        public static string lblBan {
            get {
                return ResourceManager.GetString("lblBan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bản (có danh mục và phân nhóm hàng hoá, dịch vụ mang nhãn hiệu).
        /// </summary>
        public static string lblBanCoDanhMucPhanLoaiHangHoa {
            get {
                return ResourceManager.GetString("lblBanCoDanhMucPhanLoaiHangHoa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bản dịch tiếng Việt, gồm.
        /// </summary>
        public static string lblBanDichTiengVietGom {
            get {
                return ResourceManager.GetString("lblBanDichTiengVietGom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bản đồ khu vực địa lý.
        /// </summary>
        public static string lblBanDoKhuVucDiaLy {
            get {
                return ResourceManager.GetString("lblBanDoKhuVucDiaLy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bản gốc.
        /// </summary>
        public static string lblBanGoc {
            get {
                return ResourceManager.GetString("lblBanGoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bản gốc nộp sau.
        /// </summary>
        public static string lblBanGocNopSau {
            get {
                return ResourceManager.GetString("lblBanGocNopSau", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bản gốc đã nộp theo đơn số.
        /// </summary>
        public static string lblBanGocNopTheoDonSo {
            get {
                return ResourceManager.GetString("lblBanGocNopTheoDonSo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bản sao.
        /// </summary>
        public static string lblBanSao {
            get {
                return ResourceManager.GetString("lblBanSao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bản sao đơn đầu tiên, gồm.
        /// </summary>
        public static string lblbanSaoDauTienGom {
            get {
                return ResourceManager.GetString("lblbanSaoDauTienGom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CÁC TÀI LIỆU KHÁC.
        /// </summary>
        public static string lblCacTaiLieuKhac {
            get {
                return ResourceManager.GetString("lblCacTaiLieuKhac", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Các tài liệu liên quan đính kèm trong đơn.
        /// </summary>
        public static string lblCacTaiLieuLienQuanDinhKem {
            get {
                return ResourceManager.GetString("lblCacTaiLieuLienQuanDinhKem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CAM KẾT CỦA CHỦ ĐƠN.
        /// </summary>
        public static string lblCamKetCuaChuDon {
            get {
                return ResourceManager.GetString("lblCamKetCuaChuDon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập nhật lúc.
        /// </summary>
        public static string lblCapNhatLuc {
            get {
                return ResourceManager.GetString("lblCapNhatLuc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chất lượng.
        /// </summary>
        public static string lblChatLuong {
            get {
                return ResourceManager.GetString("lblChatLuong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chi tiết bài viết.
        /// </summary>
        public static string lblChiTietBaiViet {
            get {
                return ResourceManager.GetString("lblChiTietBaiViet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chọn file.
        /// </summary>
        public static string lblChonFile {
            get {
                return ResourceManager.GetString("lblChonFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chức năng.
        /// </summary>
        public static string lblChucNang {
            get {
                return ResourceManager.GetString("lblChucNang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chủ đơn.
        /// </summary>
        public static string lblChuDon {
            get {
                return ResourceManager.GetString("lblChuDon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chủ đơn khác.
        /// </summary>
        public static string lblChuDonKhac {
            get {
                return ResourceManager.GetString("lblChuDonKhac", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chứng từ phí, lệ phí.
        /// </summary>
        public static string lblChungTuLePhi {
            get {
                return ResourceManager.GetString("lblChungTuLePhi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chuyên mục chính.
        /// </summary>
        public static string lblChuyenMucChinh {
            get {
                return ResourceManager.GetString("lblChuyenMucChinh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chuyên mục liên quan.
        /// </summary>
        public static string lblChuyenMucLienQuan {
            get {
                return ResourceManager.GetString("lblChuyenMucLienQuan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Có.
        /// </summary>
        public static string lblCo {
            get {
                return ResourceManager.GetString("lblCo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Có sử dụng đơn ưu tiên.
        /// </summary>
        public static string lblCoSuDungDonUT {
            get {
                return ResourceManager.GetString("lblCoSuDungDonUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Có tài liệu bổ trợ khai tại trang bổ sung.
        /// </summary>
        public static string lblCoTaiLieuBoTro {
            get {
                return ResourceManager.GetString("lblCoTaiLieuBoTro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Có yêu cầu cấp Phó bản Giấy chứng nhận đăng ký nhãn hiệu.
        /// </summary>
        public static string lblCoYeuCauCapPho {
            get {
                return ResourceManager.GetString("lblCoYeuCauCapPho", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đặc tính hàng hóa.
        /// </summary>
        public static string lblDacTinhHanghoa {
            get {
                return ResourceManager.GetString("lblDacTinhHanghoa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đặc tính khác.
        /// </summary>
        public static string lblDacTinhKhac {
            get {
                return ResourceManager.GetString("lblDacTinhKhac", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ĐẠI DIỆN CỦA CHỦ ĐƠN.
        /// </summary>
        public static string lblDaiDienChuDon {
            get {
                return ResourceManager.GetString("lblDaiDienChuDon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đại diện SHCN.
        /// </summary>
        public static string lblDaiDienSHCN {
            get {
                return ResourceManager.GetString("lblDaiDienSHCN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ĐĂNG KÝ NHÃN HIỆU.
        /// </summary>
        public static string lblDangKyNhanHieu {
            get {
                return ResourceManager.GetString("lblDangKyNhanHieu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danh mục.
        /// </summary>
        public static string lblDanhMuc {
            get {
                return ResourceManager.GetString("lblDanhMuc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danh sách mẫu đơn.
        /// </summary>
        public static string lblDanhSachMauDon {
            get {
                return ResourceManager.GetString("lblDanhSachMauDon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danh sách tin.
        /// </summary>
        public static string lblDanhSachTin {
            get {
                return ResourceManager.GetString("lblDanhSachTin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nếu Người nộp đơn không nhớ số đơn gốc thì có thể để trống, Luật sư sẽ điền thay sau.
        /// </summary>
        public static string lblDatatitle04NHD08 {
            get {
                return ResourceManager.GetString("lblDatatitle04NHD08", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Địa chỉ.
        /// </summary>
        public static string lblDiaChi {
            get {
                return ResourceManager.GetString("lblDiaChi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Điện thoại.
        /// </summary>
        public static string lblDienThoai {
            get {
                return ResourceManager.GetString("lblDienThoai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đơn này được tách ra từ đơn số .
        /// </summary>
        public static string lblDonTachRaTuDonSo {
            get {
                return ResourceManager.GetString("lblDonTachRaTuDonSo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giấy chuyển nhượng quyền ưu tiên.
        /// </summary>
        public static string lblGiayChuyenNhuongQuyenUT {
            get {
                return ResourceManager.GetString("lblGiayChuyenNhuongQuyenUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giấy uỷ quyền bằng tiếng.
        /// </summary>
        public static string lblGiayUyQuyen {
            get {
                return ResourceManager.GetString("lblGiayUyQuyen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gõ hàng hóa muốn đăng ký, chọn Class tương ứng.
        /// </summary>
        public static string lblGohangHoaDKChonClass {
            get {
                return ResourceManager.GetString("lblGohangHoaDKChonClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hàng hóa.
        /// </summary>
        public static string lblHangHoa {
            get {
                return ResourceManager.GetString("lblHangHoa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hàng hóa đã thêm.
        /// </summary>
        public static string lblHangHoaDaThem {
            get {
                return ResourceManager.GetString("lblHangHoaDaThem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MÔ TẢ TÓM TẮT ĐẶC TÍNH CỦA HÀNG HÓA/DỊCH VỤ ĐƯỢC CHỨNG NHẬN.
        /// </summary>
        public static string lblHeaderDanhMucVaPhanLoaiHangHoa {
            get {
                return ResourceManager.GetString("lblHeaderDanhMucVaPhanLoaiHangHoa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Khách hàng điền đủ thông tin lên và tải lên.
        /// </summary>
        public static string lblKhacHangFillThongTin {
            get {
                return ResourceManager.GetString("lblKhacHangFillThongTin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Khai tại.
        /// </summary>
        public static string lblKhaiTai {
            get {
                return ResourceManager.GetString("lblKhaiTai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không.
        /// </summary>
        public static string lblKhong {
            get {
                return ResourceManager.GetString("lblKhong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không tìm thấy dữ liệu.
        /// </summary>
        public static string lblKhongTimThayDL {
            get {
                return ResourceManager.GetString("lblKhongTimThayDL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Là người đại diện theo pháp luật của chủ đơn.
        /// </summary>
        public static string lblLaNguoiDaiDienTheoPL {
            get {
                return ResourceManager.GetString("lblLaNguoiDaiDienTheoPL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Là người khác được uỷ quyền của chủ đơn.
        /// </summary>
        public static string lblLaNguoiKhacDuocUyQuyen {
            get {
                return ResourceManager.GetString("lblLaNguoiKhacDuocUyQuyen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Là tổ chức dịch vụ đại diện sở hữu công nghiệp được uỷ quyền của chủ đơn.
        /// </summary>
        public static string lblLaToChucDichVuDaiDienSoHuu {
            get {
                return ResourceManager.GetString("lblLaToChucDichVuDaiDienSoHuu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lên đầu trang.
        /// </summary>
        public static string lblLenTrangDau {
            get {
                return ResourceManager.GetString("lblLenTrangDau", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lệ phí công bố đơn.
        /// </summary>
        public static string lblLePhiCBDon {
            get {
                return ResourceManager.GetString("lblLePhiCBDon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lệ phí nộp đơn.
        /// </summary>
        public static string lblLePhiNopDon {
            get {
                return ResourceManager.GetString("lblLePhiNopDon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lệ phí  yêu cầu hưởng quyền ưu tiên.
        /// </summary>
        public static string lblLePhiYeuCauHuongQuyenUuTien {
            get {
                return ResourceManager.GetString("lblLePhiYeuCauHuongQuyenUuTien", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loại phí, lệ phí.
        /// </summary>
        public static string lblLoaiPhiLePhi {
            get {
                return ResourceManager.GetString("lblLoaiPhiLePhi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lưu bài.
        /// </summary>
        public static string lblLuuBai {
            get {
                return ResourceManager.GetString("lblLuuBai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã đại điện.
        /// </summary>
        public static string lblMaDaiDien {
            get {
                return ResourceManager.GetString("lblMaDaiDien", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã nhóm.
        /// </summary>
        public static string lblMaNhom {
            get {
                return ResourceManager.GetString("lblMaNhom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mẫu.
        /// </summary>
        public static string lblMau {
            get {
                return ResourceManager.GetString("lblMau", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mẫu nhãn hiệu.
        /// </summary>
        public static string lblMauNhanHieu {
            get {
                return ResourceManager.GetString("lblMauNhanHieu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mẫu nhãn hiệu, gồm.
        /// </summary>
        public static string lblMauNhanHieuGom {
            get {
                return ResourceManager.GetString("lblMauNhanHieuGom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mầu sắc.
        /// </summary>
        public static string lblMauSac {
            get {
                return ResourceManager.GetString("lblMauSac", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tải mẫu về.
        /// </summary>
        public static string lblMauTaiVe {
            get {
                return ResourceManager.GetString("lblMauTaiVe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mỗi nhóm có trên 6 sản phẩm/dịch vụ (từ sản phẩm/dịch vụ thứ 7 trở đi).
        /// </summary>
        public static string lblMoiNhom6SanPham {
            get {
                return ResourceManager.GetString("lblMoiNhom6SanPham", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mô tả.
        /// </summary>
        public static string lblMoTa {
            get {
                return ResourceManager.GetString("lblMoTa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MÔ TẢ TÓM TẮT ĐẶC TÍNH CỦA HÀNG HOÁ/DỊCH VỤ ĐƯỢC CHỨNG NHẬN.
        /// </summary>
        public static string lblMoTaDacTinhCuaHangHoa {
            get {
                return ResourceManager.GetString("lblMoTaDacTinhCuaHangHoa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Năm.
        /// </summary>
        public static string lblNam {
            get {
                return ResourceManager.GetString("lblNam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày khai.
        /// </summary>
        public static string lblNgayKhai {
            get {
                return ResourceManager.GetString("lblNgayKhai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày nộp đơn.
        /// </summary>
        public static string lblNgayNopDon {
            get {
                return ResourceManager.GetString("lblNgayNopDon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Người tạo.
        /// </summary>
        public static string lblNguoiTao {
            get {
                return ResourceManager.GetString("lblNguoiTao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nguồn gốc địa lý.
        /// </summary>
        public static string lblNguonGocDiaLy {
            get {
                return ResourceManager.GetString("lblNguonGocDiaLy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhãn hiệu.
        /// </summary>
        public static string lblNhanHieu {
            get {
                return ResourceManager.GetString("lblNhanHieu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhãn hiệu chứng nhận.
        /// </summary>
        public static string lblNhanHieuChungNhan {
            get {
                return ResourceManager.GetString("lblNhanHieuChungNhan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhãn hiệu liên kết.
        /// </summary>
        public static string lblNhanHieuLienKet {
            get {
                return ResourceManager.GetString("lblNhanHieuLienKet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhãn hiệu tập thể.
        /// </summary>
        public static string lblNhanHieuTapThe {
            get {
                return ResourceManager.GetString("lblNhanHieuTapThe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhập tên tài liệu đính kèm.
        /// </summary>
        public static string lblNhapTenTaiLieuDinhKem {
            get {
                return ResourceManager.GetString("lblNhapTenTaiLieuDinhKem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhóm.
        /// </summary>
        public static string lblNhom {
            get {
                return ResourceManager.GetString("lblNhom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không.
        /// </summary>
        public static string lblNo {
            get {
                return ResourceManager.GetString("lblNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nội dung.
        /// </summary>
        public static string lblNoiDung {
            get {
                return ResourceManager.GetString("lblNoiDung", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nước nộp đơn.
        /// </summary>
        public static string lblNuocNopDon {
            get {
                return ResourceManager.GetString("lblNuocNopDon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PHÍ, LỆ PHÍ.
        /// </summary>
        public static string lblPhiLePhi {
            get {
                return ResourceManager.GetString("lblPhiLePhi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phí phân loại quốc tế về Nhãn hiệu.
        /// </summary>
        public static string lblPhiLoaiQTNH {
            get {
                return ResourceManager.GetString("lblPhiLoaiQTNH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phí thẩm định đơn.
        /// </summary>
        public static string lblPhiThamDinhDon {
            get {
                return ResourceManager.GetString("lblPhiThamDinhDon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phí tra cứu phục vụ thẩm định nội dung cho mỗi nhóm hàng hoá, dịch vụ.
        /// </summary>
        public static string lblPhiTraCuuPhuVuThamDinh {
            get {
                return ResourceManager.GetString("lblPhiTraCuuPhuVuThamDinh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quản lý bài viết.
        /// </summary>
        public static string lblQuanLyBaiViet {
            get {
                return ResourceManager.GetString("lblQuanLyBaiViet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quốc gia.
        /// </summary>
        public static string lblQuocGia {
            get {
                return ResourceManager.GetString("lblQuocGia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quy chế sử dụng NH tập thể/chứng nhận, gồm.
        /// </summary>
        public static string lblQuyCheSuDungNH {
            get {
                return ResourceManager.GetString("lblQuyCheSuDungNH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sản phẩm.
        /// </summary>
        public static string lblSanPham {
            get {
                return ResourceManager.GetString("lblSanPham", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ảnh có kích cỡ từ.
        /// </summary>
        public static string lblSizeOfPicture {
            get {
                return ResourceManager.GetString("lblSizeOfPicture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số bản.
        /// </summary>
        public static string lblSoBan {
            get {
                return ResourceManager.GetString("lblSoBan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số đối tượng tính phí.
        /// </summary>
        public static string lblSoDoiTuongTinhPhi {
            get {
                return ResourceManager.GetString("lblSoDoiTuongTinhPhi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số đơn.
        /// </summary>
        public static string lblSoDon {
            get {
                return ResourceManager.GetString("lblSoDon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số tiền.
        /// </summary>
        public static string lblSoTien {
            get {
                return ResourceManager.GetString("lblSoTien", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to STT.
        /// </summary>
        public static string lblSTT {
            get {
                return ResourceManager.GetString("lblSTT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sửa bài viết.
        /// </summary>
        public static string lblSuaBaiViet {
            get {
                return ResourceManager.GetString("lblSuaBaiViet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tải file.
        /// </summary>
        public static string lblTaiFile {
            get {
                return ResourceManager.GetString("lblTaiFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tài liệu chứng minh quyền ưu tiên.
        /// </summary>
        public static string lblTaiLieuChungMinhQuyenUT {
            get {
                return ResourceManager.GetString("lblTaiLieuChungMinhQuyenUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tài liệu chứng minh quyền ưu tiên.
        /// </summary>
        public static string lblTaiLieuChungMinhQuyenUuTien {
            get {
                return ResourceManager.GetString("lblTaiLieuChungMinhQuyenUuTien", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tài liệu xác nhận thụ hưởng quyền đăng ký từ người khác.
        /// </summary>
        public static string lblTaiLieuDKXacNhanThuHuong {
            get {
                return ResourceManager.GetString("lblTaiLieuDKXacNhanThuHuong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tài liệu khác.
        /// </summary>
        public static string lblTaiLieuKhac {
            get {
                return ResourceManager.GetString("lblTaiLieuKhac", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CÁC TÀI LIỆU CÓ TRONG ĐƠN.
        /// </summary>
        public static string lblTaiLieuTrongDon {
            get {
                return ResourceManager.GetString("lblTaiLieuTrongDon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tài liệu xác nhận được phép sử dụng các dấu hiệu đặc biệt (biểu tượng, cờ, huy hiệu, con dấu…), gồm.
        /// </summary>
        public static string lblTaiLieuXacNhanDuoc {
            get {
                return ResourceManager.GetString("lblTaiLieuXacNhanDuoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tài liệu xác nhận quyền đăng ký nhãn hiệu.
        /// </summary>
        public static string lblTaiLieuXacNhanQuyenDKNH {
            get {
                return ResourceManager.GetString("lblTaiLieuXacNhanQuyenDKNH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tất cả.
        /// </summary>
        public static string lblTatCa {
            get {
                return ResourceManager.GetString("lblTatCa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên đầy đủ.
        /// </summary>
        public static string lblTenDayDu {
            get {
                return ResourceManager.GetString("lblTenDayDu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên file.
        /// </summary>
        public static string lblTenFile {
            get {
                return ResourceManager.GetString("lblTenFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên nhãn hiệu.
        /// </summary>
        public static string lblTenNhanHieu {
            get {
                return ResourceManager.GetString("lblTenNhanHieu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên tài liệu.
        /// </summary>
        public static string lblTenTaiLieu {
            get {
                return ResourceManager.GetString("lblTenTaiLieu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tháng.
        /// </summary>
        public static string lblThang {
            get {
                return ResourceManager.GetString("lblThang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm.
        /// </summary>
        public static string lblThem {
            get {
                return ResourceManager.GetString("lblThem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm chủ đơn.
        /// </summary>
        public static string lblThemChuDon {
            get {
                return ResourceManager.GetString("lblThemChuDon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm đơn.
        /// </summary>
        public static string lblThemDon {
            get {
                return ResourceManager.GetString("lblThemDon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm mới bài viết.
        /// </summary>
        public static string lblThemMoiBaiViet {
            get {
                return ResourceManager.GetString("lblThemMoiBaiViet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theo đơn (các đơn) nộp theo Công ước Paris.
        /// </summary>
        public static string lblTheoDonNopCongUocPR {
            get {
                return ResourceManager.GetString("lblTheoDonNopCongUocPR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theo đơn (các đơn) đầu tiên nộp tại Việt Nam.
        /// </summary>
        public static string lblTheoDonNopTaiVN {
            get {
                return ResourceManager.GetString("lblTheoDonNopTaiVN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theo thoả thuận khác.
        /// </summary>
        public static string lblTheoThoaThuanKhac {
            get {
                return ResourceManager.GetString("lblTheoThoaThuanKhac", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thoát.
        /// </summary>
        public static string lblThoat {
            get {
                return ResourceManager.GetString("lblThoat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email không đúng định dạng.
        /// </summary>
        public static string lblThongBaoLoiEmail {
            get {
                return ResourceManager.GetString("lblThongBaoLoiEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông tin bài viết.
        /// </summary>
        public static string lblThongTinBaiViet {
            get {
                return ResourceManager.GetString("lblThongTinBaiViet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tiêu đề.
        /// </summary>
        public static string lblTieuDe {
            get {
                return ResourceManager.GetString("lblTieuDe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tìm kiếm nhóm.
        /// </summary>
        public static string lblTimKiemNhom {
            get {
                return ResourceManager.GetString("lblTimKiemNhom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tin tức.
        /// </summary>
        public static string lblTinTuc {
            get {
                return ResourceManager.GetString("lblTinTuc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tôi cam đoan mọi thông tin trong tờ khai trên đây là trung thực, đúng sự thật và hoàn toàn chịu trách nhiệm trước pháp luật..
        /// </summary>
        public static string lblToiCamdoan {
            get {
                return ResourceManager.GetString("lblToiCamdoan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tờ khai, gồm.
        /// </summary>
        public static string lblToKhaiGom {
            get {
                return ResourceManager.GetString("lblToKhaiGom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tóm tắt.
        /// </summary>
        public static string lblTomTat {
            get {
                return ResourceManager.GetString("lblTomTat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tổng số nhóm.
        /// </summary>
        public static string lblTongSoNhom {
            get {
                return ResourceManager.GetString("lblTongSoNhom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tổng SP.
        /// </summary>
        public static string lblTongSP {
            get {
                return ResourceManager.GetString("lblTongSP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to trang.
        /// </summary>
        public static string lblTrang {
            get {
                return ResourceManager.GetString("lblTrang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Văn bản của UBND tỉnh, TP trực thuộc TW cho phép sử dụng địa danh hoặc dấu hiệu khác chỉ nguồn gốc địa lý của đặc sản địa phượng.
        /// </summary>
        public static string lblVanBanUBNDTinh {
            get {
                return ResourceManager.GetString("lblVanBanUBNDTinh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xem trước.
        /// </summary>
        public static string lblXemTruoc {
            get {
                return ResourceManager.GetString("lblXemTruoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Có.
        /// </summary>
        public static string lblYes {
            get {
                return ResourceManager.GetString("lblYes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to YÊU CẦU HƯỞNG QUYỀN ƯU TIÊN.
        /// </summary>
        public static string lblYeuCauHuongQuyenUT {
            get {
                return ResourceManager.GetString("lblYeuCauHuongQuyenUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lên đầu trang.
        /// </summary>
        public static string LenDauTrang {
            get {
                return ResourceManager.GetString("LenDauTrang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QUẢN LÝ VỤ VIỆC.
        /// </summary>
        public static string QuanLyVuViec {
            get {
                return ResourceManager.GetString("QuanLyVuViec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tìm kiếm hàng hóa/dịch vụ.
        /// </summary>
        public static string SearchAppClass {
            get {
                return ResourceManager.GetString("SearchAppClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã hàng hóa không đúng, Kiểm tra lại mã hàng hóa!.
        /// </summary>
        public static string TenHangHoaKhongDung {
            get {
                return ResourceManager.GetString("TenHangHoaKhongDung", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tìm số đơn.
        /// </summary>
        public static string TimSoDon {
            get {
                return ResourceManager.GetString("TimSoDon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quản lý vụ việc.
        /// </summary>
        public static string TM04NH_QuanLyVuViec {
            get {
                return ResourceManager.GetString("TM04NH_QuanLyVuViec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bản cam kết sẽ sử dụng NH tại nước yêu cầu đăng ký bảo hộ (nếu chỉ định vào các quốc gia Ireland, Singapore, Vương quốc Anh và Hoa Kỳ.
        /// </summary>
        public static string TM2B_BanCamKetSeSD {
            get {
                return ResourceManager.GetString("TM2B_BanCamKetSeSD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to số trang.
        /// </summary>
        public static string TM2B_BanDichSoTrang {
            get {
                return ResourceManager.GetString("TM2B_BanDichSoTrang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bản dịch tiếng Việt.
        /// </summary>
        public static string TM2B_BanDichTiengViet {
            get {
                return ResourceManager.GetString("TM2B_BanDichTiengViet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bản gốc.
        /// </summary>
        public static string TM2B_BanGoc {
            get {
                return ResourceManager.GetString("TM2B_BanGoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bản gốc đã nộp theo đơn.
        /// </summary>
        public static string TM2B_BanGocDaNopTheo {
            get {
                return ResourceManager.GetString("TM2B_BanGocDaNopTheo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bản gốc sẽ nộp sau.
        /// </summary>
        public static string TM2B_BanGocSeNopSau {
            get {
                return ResourceManager.GetString("TM2B_BanGocSeNopSau", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bằng tiếng.
        /// </summary>
        public static string TM2B_BangTieng {
            get {
                return ResourceManager.GetString("TM2B_BangTieng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bản sao.
        /// </summary>
        public static string TM2B_BanSao {
            get {
                return ResourceManager.GetString("TM2B_BanSao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bản sao Giấy chứng nhận đăng ký nhãn hiệu cơ sở.
        /// </summary>
        public static string TM2B_BanSaoGiayCNDK {
            get {
                return ResourceManager.GetString("TM2B_BanSaoGiayCNDK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bản sao Tờ khai yêu cầu cấp GCN đăng ký nhãn hiệu cơ sở.
        /// </summary>
        public static string TM2B_BanSaoToKhai {
            get {
                return ResourceManager.GetString("TM2B_BanSaoToKhai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phải chọn ít nhất 1 giá trị đại điện cho chủ đơn!.
        /// </summary>
        public static string TM2B_ChonDaiDienChuDon {
            get {
                return ResourceManager.GetString("TM2B_ChonDaiDienChuDon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phải chọn ít nhất 1 loại giấy đăng kỹ nhãn hiệu cơ sở!.
        /// </summary>
        public static string TM2B_ChonGiayDK {
            get {
                return ResourceManager.GetString("TM2B_ChonGiayDK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chưa chọn nhóm hàng hóa dịch vụ!.
        /// </summary>
        public static string TM2B_ChonHangHoaDV {
            get {
                return ResourceManager.GetString("TM2B_ChonHangHoaDV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chọn khách hàng.
        /// </summary>
        public static string TM2B_ChonKhachHang {
            get {
                return ResourceManager.GetString("TM2B_ChonKhachHang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày nộp đơn không được phép để trống!.
        /// </summary>
        public static string TM2B_ChonNgayNopDon {
            get {
                return ResourceManager.GetString("TM2B_ChonNgayNopDon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phải chọn ít nhất 1 nước chỉ định đăng ký nhãn hiệu!.
        /// </summary>
        public static string TM2B_ChonNuocDKNH {
            get {
                return ResourceManager.GetString("TM2B_ChonNuocDKNH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chưa chọn số đơn!.
        /// </summary>
        public static string TM2B_ChonSoDon {
            get {
                return ResourceManager.GetString("TM2B_ChonSoDon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phải chọn ít nhất 1 giá trị loại thành viên!.
        /// </summary>
        public static string TM2B_ChonThanhVien {
            get {
                return ResourceManager.GetString("TM2B_ChonThanhVien", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn chưa chọn khách hàng khai hộ đơn!.
        /// </summary>
        public static string TM2B_ChuaChonKhachHang {
            get {
                return ResourceManager.GetString("TM2B_ChuaChonKhachHang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CHỦ ĐƠN.
        /// </summary>
        public static string TM2B_ChuDon {
            get {
                return ResourceManager.GetString("TM2B_ChuDon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chứng từ lệ phí.
        /// </summary>
        public static string TM2B_ChungTuLePhi {
            get {
                return ResourceManager.GetString("TM2B_ChungTuLePhi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ĐẠI DIỆN CỦA CHỦ ĐƠN.
        /// </summary>
        public static string TM2B_DaiDienChuDon {
            get {
                return ResourceManager.GetString("TM2B_DaiDienChuDon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Địa chỉ không được để trống!.
        /// </summary>
        public static string TM2B_DiaChiKhongDuocDeTrong {
            get {
                return ResourceManager.GetString("TM2B_DiaChiKhongDuocDeTrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đơn đăng ký nhãn hiệu cơ sở.
        /// </summary>
        public static string TM2B_dondangkynhanhieucs {
            get {
                return ResourceManager.GetString("TM2B_dondangkynhanhieucs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email không đúng định dạng!.
        /// </summary>
        public static string TM2B_EmailKhongDuocDeTrong {
            get {
                return ResourceManager.GetString("TM2B_EmailKhongDuocDeTrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request for amendment of application.
        /// </summary>
        public static string TM2B_Formname {
            get {
                return ResourceManager.GetString("TM2B_Formname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giấy chứng nhận đăng ký nhãn hiệu cơ sở.
        /// </summary>
        public static string TM2B_giaycndknhcs {
            get {
                return ResourceManager.GetString("TM2B_giaycndknhcs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giấy ủy quyền.
        /// </summary>
        public static string TM2B_GiayUyQuyen {
            get {
                return ResourceManager.GetString("TM2B_GiayUyQuyen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không tìm thấy dữ liệu.
        /// </summary>
        public static string TM2B_KhongTimThayDuLieu {
            get {
                return ResourceManager.GetString("TM2B_KhongTimThayDuLieu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Làm bằng tiếng.
        /// </summary>
        public static string TM2B_LamBangTieng {
            get {
                return ResourceManager.GetString("TM2B_LamBangTieng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to YÊU CẦU ĐĂNG KÝ QUỐC TẾ NHÃN HIỆU CÓ NGUỒN GỐC VIỆT NAM.
        /// </summary>
        public static string TM2B_legend {
            get {
                return ResourceManager.GetString("TM2B_legend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lệ phí đăng ký không được để trống!.
        /// </summary>
        public static string TM2B_LePhiDangKy {
            get {
                return ResourceManager.GetString("TM2B_LePhiDangKy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã nhóm.
        /// </summary>
        public static string TM2B_MaNhom {
            get {
                return ResourceManager.GetString("TM2B_MaNhom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mẫu đăng ký của Văn phòng quốc tế, form số:.
        /// </summary>
        public static string TM2B_MauDKVPQT {
            get {
                return ResourceManager.GetString("TM2B_MauDKVPQT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mẫu nhãn hiệu.
        /// </summary>
        public static string TM2B_MauNhanHieu {
            get {
                return ResourceManager.GetString("TM2B_MauNhanHieu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày nộp đơn/Ngày cấp CGN.
        /// </summary>
        public static string TM2B_Ngaynopdon {
            get {
                return ResourceManager.GetString("TM2B_Ngaynopdon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NHÃN HIỆU QUỐC TẾ.
        /// </summary>
        public static string TM2B_nhanhieuquocte {
            get {
                return ResourceManager.GetString("TM2B_nhanhieuquocte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhập tài liệu.
        /// </summary>
        public static string TM2B_NhapTaiLieu {
            get {
                return ResourceManager.GetString("TM2B_NhapTaiLieu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phí dịch vụ làm thủ tục đăng ký quốc tế nhãn hiệu đã nộp kèm theo:.
        /// </summary>
        public static string TM2B_PhiDichVu {
            get {
                return ResourceManager.GetString("TM2B_PhiDichVu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số bản.
        /// </summary>
        public static string TM2B_SoBan {
            get {
                return ResourceManager.GetString("TM2B_SoBan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số đơn/Số GCN.
        /// </summary>
        public static string TM2B_sodon {
            get {
                return ResourceManager.GetString("TM2B_sodon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số đơn.
        /// </summary>
        public static string TM2B_SodonNopTheo {
            get {
                return ResourceManager.GetString("TM2B_SodonNopTheo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số mẫu.
        /// </summary>
        public static string TM2B_SoMau {
            get {
                return ResourceManager.GetString("TM2B_SoMau", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số trang.
        /// </summary>
        public static string TM2B_SoTrang {
            get {
                return ResourceManager.GetString("TM2B_SoTrang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số trang bổ sung.
        /// </summary>
        public static string TM2B_SoTrangBoSung {
            get {
                return ResourceManager.GetString("TM2B_SoTrangBoSung", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tải file.
        /// </summary>
        public static string TM2B_taifile {
            get {
                return ResourceManager.GetString("TM2B_taifile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tài liệu bổ sung.
        /// </summary>
        public static string TM2B_TaiLieuBoSung {
            get {
                return ResourceManager.GetString("TM2B_TaiLieuBoSung", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CÁC TÀI LIỆU CÓ TRONG ĐƠN.
        /// </summary>
        public static string TM2B_TaiLieuCoTrongDon {
            get {
                return ResourceManager.GetString("TM2B_TaiLieuCoTrongDon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Khách hàng:.
        /// </summary>
        public static string TM2B_TenKhachHang {
            get {
                return ResourceManager.GetString("TM2B_TenKhachHang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên không được để trống!.
        /// </summary>
        public static string TM2B_TenKhongDuocDeTrong {
            get {
                return ResourceManager.GetString("TM2B_TenKhongDuocDeTrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TÊN VÀ MÃ NƯỚC CHỈ ĐỊNH ĐĂNG KÝ QUỐC TẾ NHÃN HIỆU.
        /// </summary>
        public static string TM2B_TenNuocDK {
            get {
                return ResourceManager.GetString("TM2B_TenNuocDK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chỉ là Thành viên Nghị định thư Madrid.
        /// </summary>
        public static string TM2B_thanhviennghidinhthu {
            get {
                return ResourceManager.GetString("TM2B_thanhviennghidinhthu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vừa là Thành viên Thoả ước Madrid, vừa là Thành viên Nghị định thư Madrid.
        /// </summary>
        public static string TM2B_thanhvienthoauoc {
            get {
                return ResourceManager.GetString("TM2B_thanhvienthoauoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to THÔNG TIN CƠ BẢN.
        /// </summary>
        public static string TM2B_thongtincoban {
            get {
                return ResourceManager.GetString("TM2B_thongtincoban", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tìm kiếm quốc gia.
        /// </summary>
        public static string TM2B_TimKiemQuocGia {
            get {
                return ResourceManager.GetString("TM2B_TimKiemQuocGia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tìm kiếm số đơn.
        /// </summary>
        public static string TM2B_TimKiemSoDon {
            get {
                return ResourceManager.GetString("TM2B_TimKiemSoDon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tờ khai.
        /// </summary>
        public static string TM2B_TITLE {
            get {
                return ResourceManager.GetString("TM2B_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sửa đơn.
        /// </summary>
        public static string TM2B_TitleEdit {
            get {
                return ResourceManager.GetString("TM2B_TitleEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tờ khai, gồm.
        /// </summary>
        public static string TM2B_ToKhaiGom {
            get {
                return ResourceManager.GetString("TM2B_ToKhaiGom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Có ít nhất 2 lựa chọn mã nước trùng nhau, vui lòng kiểm tra lại!.
        /// </summary>
        public static string TM2B_TrungMaNuoc {
            get {
                return ResourceManager.GetString("TM2B_TrungMaNuoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bản dịch tiếng Việt, gồm.
        /// </summary>
        public static string TM3B_BanDichTiengVietGom {
            get {
                return ResourceManager.GetString("TM3B_BanDichTiengVietGom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bản sao chứng từ nộp phí, lệ phí (trường hợp nộp phí, lệ phí qua dịch vụ bưu chính hoặc nộp trực tiếp vào tài khoản của Cục Sở hữu trí tuệ).
        /// </summary>
        public static string TM3B_BanSaoChungTuNopPhi {
            get {
                return ResourceManager.GetString("TM3B_BanSaoChungTuNopPhi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sửa đơn.
        /// </summary>
        public static string TM3B_BtnSuaDon {
            get {
                return ResourceManager.GetString("TM3B_BtnSuaDon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CAM KẾT CỦA CHỦ ĐƠN.
        /// </summary>
        public static string TM3B_CamKetChuDon {
            get {
                return ResourceManager.GetString("TM3B_CamKetChuDon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chưa chọn loại đơn đăng ký.
        /// </summary>
        public static string TM3B_ChonLoaiDonDK {
            get {
                return ResourceManager.GetString("TM3B_ChonLoaiDonDK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phải chọn ít nhất 1 giá trị nội dung yêu cầu sửa đổi!.
        /// </summary>
        public static string TM3B_ChonNoiDungYCSuaDoi {
            get {
                return ResourceManager.GetString("TM3B_ChonNoiDungYCSuaDoi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đề nghị sửa thành.
        /// </summary>
        public static string TM3B_DeNghiSuaThanh {
            get {
                return ResourceManager.GetString("TM3B_DeNghiSuaThanh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đề nghị sửa thành không được để trống!.
        /// </summary>
        public static string TM3B_DeNghiSuaThanhTrong {
            get {
                return ResourceManager.GetString("TM3B_DeNghiSuaThanhTrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Địa chỉ của chủ đơn.
        /// </summary>
        public static string TM3B_DiaChiChuDon {
            get {
                return ResourceManager.GetString("TM3B_DiaChiChuDon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đơn đăng ký chỉ dẫn địa lý.
        /// </summary>
        public static string TM3B_DonDKChiDanDiaLy {
            get {
                return ResourceManager.GetString("TM3B_DonDKChiDanDiaLy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đơn đăng ký kiểu dáng công nghiệp.
        /// </summary>
        public static string TM3B_DonDKKieuDangCongNghiep {
            get {
                return ResourceManager.GetString("TM3B_DonDKKieuDangCongNghiep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đơn đăng ký nhãn hiệu.
        /// </summary>
        public static string TM3B_DonDKNhanHieu {
            get {
                return ResourceManager.GetString("TM3B_DonDKNhanHieu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đơn đăng ký sáng chế.
        /// </summary>
        public static string TM3B_DonDKSangChe {
            get {
                return ResourceManager.GetString("TM3B_DonDKSangChe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đơn đăng ký thiết kế bố trí mạch tích hợp bán dẫn.
        /// </summary>
        public static string TM3B_DonDKThietKeBotriMach {
            get {
                return ResourceManager.GetString("TM3B_DonDKThietKeBotriMach", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ĐƠN YÊU CẦU SỬA ĐỔI.
        /// </summary>
        public static string TM3B_FormHeader {
            get {
                return ResourceManager.GetString("TM3B_FormHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request for amendment of application.
        /// </summary>
        public static string TM3B_Formname {
            get {
                return ResourceManager.GetString("TM3B_Formname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phải chọn ít nhất 1 giá trị đơn yêu cầu sửa đổi!.
        /// </summary>
        public static string TM3B_GiaTriDonYCSuaDoi {
            get {
                return ResourceManager.GetString("TM3B_GiaTriDonYCSuaDoi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giấy uỷ quyền bằng tiếng.
        /// </summary>
        public static string TM3B_GiayUyQuyenBangTieng {
            get {
                return ResourceManager.GetString("TM3B_GiayUyQuyenBangTieng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Có lỗi xảy ra kiểm tra kết nối internet.
        /// </summary>
        public static string TM3B_InternetError {
            get {
                return ResourceManager.GetString("TM3B_InternetError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Khai tại.
        /// </summary>
        public static string TM3B_KhaiTai {
            get {
                return ResourceManager.GetString("TM3B_KhaiTai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không có file để tải lên!.
        /// </summary>
        public static string TM3B_KhongCoFile {
            get {
                return ResourceManager.GetString("TM3B_KhongCoFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SỬA ĐỔI ĐƠN ĐĂNG KÝ ĐỐI TƯỢNG SỞ HỮU CÔNG NGHIỆP.
        /// </summary>
        public static string TM3B_Legend {
            get {
                return ResourceManager.GetString("TM3B_Legend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to lỗi.
        /// </summary>
        public static string TM3B_Loi {
            get {
                return ResourceManager.GetString("TM3B_Loi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nếu Người nộp đơn không nhớ số đơn gốc thì có thể để trống, Luật sư sẽ điền thay sau.
        /// </summary>
        public static string TM3B_LuatSuDienThay {
            get {
                return ResourceManager.GetString("TM3B_LuatSuDienThay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lưu tạm không thành công.
        /// </summary>
        public static string TM3B_LuuTamLoi {
            get {
                return ResourceManager.GetString("TM3B_LuuTamLoi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lưu tạm thành công!.
        /// </summary>
        public static string TM3B_LuuTamThanhCong {
            get {
                return ResourceManager.GetString("TM3B_LuuTamThanhCong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Năm.
        /// </summary>
        public static string TM3B_Nam {
            get {
                return ResourceManager.GetString("TM3B_Nam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày khai.
        /// </summary>
        public static string TM3B_NgayKhai {
            get {
                return ResourceManager.GetString("TM3B_NgayKhai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nội dung khác.
        /// </summary>
        public static string TM3B_NoiDungKhac {
            get {
                return ResourceManager.GetString("TM3B_NoiDungKhac", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NỘI DUNG YÊU CẦU SỬA ĐỔI.
        /// </summary>
        public static string TM3B_NoiDungYCSuaDoi {
            get {
                return ResourceManager.GetString("TM3B_NoiDungYCSuaDoi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số đối tượng tính phí.
        /// </summary>
        public static string TM3B_SoDoiTuongTinhPhi {
            get {
                return ResourceManager.GetString("TM3B_SoDoiTuongTinhPhi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số đơn.
        /// </summary>
        public static string TM3B_SoDon {
            get {
                return ResourceManager.GetString("TM3B_SoDon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số đơn không được để trống!.
        /// </summary>
        public static string TM3B_SoDonKhongDuocDeTrong {
            get {
                return ResourceManager.GetString("TM3B_SoDonKhongDuocDeTrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số hình.
        /// </summary>
        public static string TM3B_SoHinh {
            get {
                return ResourceManager.GetString("TM3B_SoHinh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số hình không được để trống!.
        /// </summary>
        public static string TM3B_SoHinhKhongDuocDeTrong {
            get {
                return ResourceManager.GetString("TM3B_SoHinhKhongDuocDeTrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số tiền.
        /// </summary>
        public static string TM3B_SoTien {
            get {
                return ResourceManager.GetString("TM3B_SoTien", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số trang không được để trống!.
        /// </summary>
        public static string TM3B_SoTrangKhongDuocDeTrong {
            get {
                return ResourceManager.GetString("TM3B_SoTrangKhongDuocDeTrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tài liệu khác, cụ thể.
        /// </summary>
        public static string TM3B_TaiLieuKhac {
            get {
                return ResourceManager.GetString("TM3B_TaiLieuKhac", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên tài liệu.
        /// </summary>
        public static string TM3B_TaiLieuKhacTenTaiLieu {
            get {
                return ResourceManager.GetString("TM3B_TaiLieuKhacTenTaiLieu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tài liệu xác nhận việc sửa đổi hợp pháp, bằng tiếng.
        /// </summary>
        public static string TM3B_TaiLieuXacNhanThayDoi {
            get {
                return ResourceManager.GetString("TM3B_TaiLieuXacNhanThayDoi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tải mẫu về.
        /// </summary>
        public static string TM3B_TaiMau {
            get {
                return ResourceManager.GetString("TM3B_TaiMau", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên chủ đơn.
        /// </summary>
        public static string TM3B_TenChuDon {
            get {
                return ResourceManager.GetString("TM3B_TenChuDon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không tải file có tên file được lưu là unicode Tiếng việt có dấu!.
        /// </summary>
        public static string TM3B_TenFileChuaUnicode {
            get {
                return ResourceManager.GetString("TM3B_TenFileChuaUnicode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên file không được quá 200 ký tự.
        /// </summary>
        public static string TM3B_TenFileDai {
            get {
                return ResourceManager.GetString("TM3B_TenFileDai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tháng.
        /// </summary>
        public static string TM3B_Thang {
            get {
                return ResourceManager.GetString("TM3B_Thang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tiếng.
        /// </summary>
        public static string TM3B_Tieng {
            get {
                return ResourceManager.GetString("TM3B_Tieng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xem thông tin đơn.
        /// </summary>
        public static string TM3B_XemThongTinDon {
            get {
                return ResourceManager.GetString("TM3B_XemThongTinDon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tìm kiếm.
        /// </summary>
        public static string WikiSearchButton {
            get {
                return ResourceManager.GetString("WikiSearchButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tìm kiếm theo tiêu đề hoặc hashtag.
        /// </summary>
        public static string WikiSearchPlaceholder {
            get {
                return ResourceManager.GetString("WikiSearchPlaceholder", resourceCulture);
            }
        }
    }
}
